modernweb-dev/web

- .changeset/warm-tigers-complain.md
- packages/test-runner-cli/src/startTestRunner.ts
When a string was used in the 'files' field the validator would throw an error.
I've changed the boolean expression for the error to be thrown to accept both Arrays and Strings that are not empty.
Boolean expression: `!(IsString || IsArray) || IsEmpty`
| IsString | IsArray | IsEmpty | Result |
| --- | --- | --- | --- |
| FALSE | FALSE | FALSE | **TRUE** | 
| FALSE | FALSE | TRUE | **TRUE** |
| FALSE | TRUE | FALSE | **FALSE** |
| FALSE | TRUE | TRUE | **TRUE** | 
| TRUE | FALSE | FALSE | **FALSE** |
| TRUE | FALSE | TRUE | **TRUE** |  
| TRUE | TRUE | FALSE | **FALSE** | 
| TRUE | TRUE | TRUE | **TRUE** | 
In this table you can see the only time the error won't be thrown, is when either the IsArray or IsString are true and the String or array is not empty.
> fix(test-runner-cli): fixed error when files is defined as string in the config file

- .changeset/three-tables-repair.md
- packages/test-runner-playwright/src/playwrightLauncher.ts
Playwright was keeping a pool of inactive pages without mapping them to a browser. This meant that rerunning a test file would rerun on different browsers at random.
> fix(test-runner-playwright): correctly map pages to browsers

- .changeset/eight-bears-do.md
- .changeset/violet-ducks-smile.md
- .changeset/warm-tigers-grab.md
- .changeset/weak-crews-own.md
- packages/test-runner-chrome/src/chromeLauncher.ts
- packages/test-runner-cli/src/cli/TestRunnerCli.ts
- packages/test-runner-cli/src/cli/getWatchCommands.ts
- packages/test-runner-cli/src/reporter/getTestProgress.ts
- packages/test-runner-core/src/runner/TestRunner.ts
- fix race condition which cleared terminal on debug
- don't require selecting files when there is only one test file
- remove multiple browsers total progress
- open debug in a larger browser window
Fixes https://github.com/modernweb-dev/web/issues/200
Fixes https://github.com/modernweb-dev/web/issues/117
> Various improvements and bugfixes

- packages/test-runner-cli/src/cli/TestRunnerCli.ts
- packages/test-runner-cli/src/terminal/BufferedConsole.ts
- packages/test-runner-cli/src/terminal/DynamicTerminal.ts
In the past we used to format all console messages as a tring, and log it all at once. Because we now rely on NodeJS to format the console output, there is a noticeable delay between removing the progress bar, adding the static logs, and adding the progress bar back. 
This change adds a BufferedConsole where the formatting is done and cached, and the raw colored strings are piped to stdout directly. There is still a flicking sometimes, but it's back to the level it was before.
> feat(test-runner-cli): improve terminal performance

- .github/workflows/release.yml
- .github/workflows/verify.yml
- package.json
The action works as follows.
- When you create a changeset and push it to master, it does not immediately publish. 
- First, the action creates a PR which contains all the information about what will be released, which dependent packages get a bump, etc. etc.
- When another PR is merged to master also containing a changeset, the auto-created PR is updated automatically by the action.
- When you merge this auto-generated PR, it will publish all the things for you 🎉 so it's a final check basically, and an easy and overview-able way to stack up intents to release.
I also added some caching to the dependencies, which in lion already sped things up significantly (>50% faster).
Lastly, I checked about linked packages. Long story short is that you don't need linked packages for technical reasons …
> chore: make use of changeset action and cache deps

- .changeset/few-fireants-hug.md
- docs/docs/dev-server/code-transformations.md
- docs/docs/dev-server/rollup.md
- packages/dev-server-core/README.md
- packages/dev-server-core/package.json
- packages/dev-server-core/src/DevServerCoreConfig.ts
- packages/dev-server-core/src/index.ts
- packages/dev-server-core/src/middleware/pluginTransformMiddleware.ts
- packages/dev-server-core/src/plugins/mimeTypesPlugin.ts
- packages/dev-server-core/src/server/DevServer.ts
- packages/dev-server-core/src/server/createMiddleware.ts
- packages/dev-server-core/src/server/createPlugins.ts
- packages/dev-server-core/src/server/createServer.ts
- packages/dev-server-core/test/tests/plugins/mimeTypesPlugin.test.ts
- packages/dev-server-rollup/README.md
- packages/dev-server-rollup/src/createRollupPluginContextAdapter.ts
- packages/dev-server-rollup/test/node/plugins/postcss.test.ts
- packages/dev-server-rollup/web-test-runner.config.js
- packages/test-runner-browserstack/package.json
- packages/test-runner-chrome/package.json
- packages/test-runner-playwright/package.json
- packages/test-runner-puppeteer/package.json
- packages/test-runner-selenium/package.json
- packages/test-runner-server/src/server/TestRunnerServerConfig.ts
- packages/test-runner-server/src/server/testRunnerServer.ts
- packages/test-runner/package.json
- packages/test-runner/src/test-runner.ts
Fixes https://github.com/modernweb-dev/web/issues/191
This adds a utility to easily set the mime type for a certain pattern of files from the server and test runner config.
For example:
```js
export default {
mimeTypes: {
// serve all json files as js
'**/*.json': 'js',
// serve .module.css files as js
'**/*.module.css': 'js',
},
}
```
This is useful when doing things like importing CSS files, and will become important as module types other than JS start to become standard. It is also useful when using exotic picture and video formats.
> feat: add an easy way to change served mime types

- docs/docs/test-runner/advanced.md
- docs/docs/test-runner/browsers/puppeteer.md
- docs/docs/test-runner/testing-in-a-ci.md
Fixes https://github.com/modernweb-dev/web/issues/326
This adds basic instructions on testing in a CI. I'd prefer to defer as much as possible to the official docs, since it's not WTR specific. But if we have practical advice, we could put it there. What do you think @Westbrook ?
> docs: add testing in a CI page

- .changeset/two-mails-rhyme.md
- packages/test-runner-mocha/src/standalone.ts
- packages/test-runner/demo/test/pass-html-1.test.html
adds a custom reporter for HTML tests, avoiding errors when debugging
> feat(test-runner-mocha): add a custom reporter for HTML tests

- package.json
- yarn.lock
This improves the sidebar navigation:
- group pages are clickable but you will be "redirected" to the first sub page
- group pages still exist for seo and for situations when javascript is disabled
- group pages content should be only one sentence and `layout: with-index.njk`
- the anchor menu now indicates the currently active "location"
- added sidebar css hover color
*Note: needed to regenerate the yarn.lock file as it did not pick up the correct dependencies of rocket*
> chore: sidebar click to submenu, anchor indicator

- docs/docs/test-runner/browsers/overview.md
- docs/docs/test-runner/browsers/writing-browser-lauchers.md
- docs/docs/test-runner/reporters/index.md
- docs/docs/test-runner/reporters/junit.md
- docs/docs/test-runner/reporters/overview.md
- docs/docs/test-runner/reporters/writing-reporters.md
- docs/docs/test-runner/test-frameworks/writing-test-frameworks.md
- packages/test-runner-core/docs/browser-launcher.md
- packages/test-runner-core/docs/server.md
- packages/test-runner-core/test/src/runner/TestRunner.test.ts
- packages/test-runner/README.md
What I did:
- Move last `docs` folder in `web-test-runner-core` into the main docs
- Make all links full URLs in the web test runner readme (so they also work on npmjs)
- Aligned to always have a "writing foo" page e.g.  `Plugins -> Write Plugins`, `Reporters -> Write Reporters`, `Browser -> Write Browser Launchers` ("Write Browsers" sounded a little too big for a single page 😅)
> chore: align docs

- .changeset/stupid-balloons-notice.md
- packages/dev-server-cli/src/logger/logStartMessage.ts
- packages/dev-server-cli/src/logger/loggerPlugin.ts
- packages/dev-server-cli/src/startDevServer.ts
- packages/dev-server/src/startDevServer.ts
When running in watch mode, we clear the terminal when you change files so that errors are not repeated.
> feat(dev-server): clear terminal on file changes

- docs/docs/test-runner/writing-tests/code-coverage.md
- docs/guides/test-runner/code-coverage/index.md
- package.json
Add documentation of `/* c8 ignore next */` to "Guides" and "Docs".
> docs(test-runner): cover ignoring uncovered lines

- .changeset/happy-hats-cry.md
- packages/dev-server/package.json
- packages/test-runner-chrome/src/ChromeLauncherPage.ts
- packages/test-runner-core/src/browser-launcher/BrowserLauncher.ts
- packages/test-runner-core/src/browser-launcher/getBrowserPageNavigationError.ts
- packages/test-runner-core/src/index.ts
- packages/test-runner-core/src/runner/TestScheduler.ts
- packages/test-runner-playwright/src/PlaywrightLauncherPage.ts
- packages/test-runner-selenium/src/WindowManager.ts
- packages/test-runner/demo/selenium.config.js
- packages/test-runner/demo/test/fail-location-href.test.js
- packages/test-runner/demo/test/fail-location-reload.test.js
- packages/test-runner/demo/test/fail-location-replace.test.js
- packages/test-runner/package.json
Fixes https://github.com/modernweb-dev/web/issues/29
This adds tracking for page reloads,  reporting it in the terminal with a helpful message:
> feat(test-runner): track and log page reloads

- docs/docs/dev-server/middleware/index.md
Code samples were using `middlewareS` instead of `middleware`
> Update middleware docs

- .changeset/tough-spies-flash.md
- packages/dev-server-core/src/server/DevServer.ts
- packages/dev-server/src/startDevServer.ts
This fixes an issue where killing the server left some background processes running because connections to the server were being kept open.
> fix(dev-server-core): properly close server on exit

- docs/docs/test-runner/browsers/saucelabs.md
According to the source code we don't need a wrapping `capabilities` object:
https://github.com/modernweb-dev/web/blob/c4b00bba39a35e0e1776c541f6ebea30f065c6e4/packages/test-runner-saucelabs/test-remote/saucelabsLauncher.test.js#L53-L58
> Docs: Fix invalid SauceLabs configuration

- docs/docs/test-runner/browsers/saucelabs.md
The examples currently use different case which is not so copy-paste friendly. Let's fix this 🙂
> docs: align Sauce Labs code examples

- .changeset/selfish-badgers-sip.md
- packages/dev-server-rollup/package.json
Moved test runner dependencies to dev dependencies
> fix(dev-server-rollup): moved test runner dependencies to dev dependencies

- docs/guides/going-buildless/css.md
> docs: fix buildless css guide

- docs/docs/test-runner/cli-and-configuration.md
Looks like the docs need to be updated to reflect actual config.
> docs: update test timeout config options

- .changeset/tricky-drinks-juggle.md
- packages/test-runner-saucelabs/src/SauceLabsLauncher.ts
- packages/test-runner-saucelabs/src/SauceLabsLauncherManager.ts
This improves the logic which closes the saucelabs proxy. The connection is now available synchronously so that we can close the proxy ASAP. Also added listeners to for SIGINT and SIGTERM to ensure the proxy is always closed.
> fix(test-runner-saucelabs): improve handling of closing proxy

- .changeset/thirty-guests-invent.md
- packages/test-runner-saucelabs/src/SauceLabsLauncher.ts
This closes the webdriver instance before closing the saucelabs proxy, improving stability.
> fix(test-runner-saucelabs): close webdriver before proxy

- .changeset/itchy-cherries-press.md
- packages/test-runner-selenium/src/seleniumLauncher.ts
- packages/test-runner-selenium/src/utils.ts
This improves the logic used to generate the browser name, reading different fields until a match is found.
> feat(test-runner-selenium): improve generating browser name

- .changeset/silent-months-carry.md
- packages/test-runner-core/src/server/plugins/serveTestRunnerHtmlPlugin.ts
- packages/test-runner-saucelabs/src/SauceLabsLauncher.ts
- packages/test-runner-saucelabs/src/createSauceLabsLauncher.ts
- packages/test-runner-saucelabs/test-remote/saucelabsLauncher.test.js
- packages/test-runner-selenium/src/IFrameManager.ts
- packages/test-runner-selenium/src/seleniumLauncher.ts
- packages/test-runner/demo/selenium.config.js
This adds an experimental iframes mode for the selenium test launchers. This should reduce overhead creating and switching between pages on browserstack and saucelabs. I'm going to test it out on some different projects first to see if this is a significant enough improvement.
> feat(test-runner): added experimental iframes mode

- docs/docs/test-runner/browser-launchers/saucelabs.md
Replacing "browserstack" (which appears to be a copy paste) with Sauce Labs.
> docs: fix copy-paste from another page

- .changeset/smart-plums-cheat.md
- packages/test-runner-browserstack/src/browserstackLauncher.ts
- packages/test-runner-browserstack/src/browserstackManager.ts
- packages/test-runner-core/src/runner/TestRunner.ts
- packages/test-runner-core/src/runner/TestScheduler.ts
- packages/test-runner-saucelabs/src/SauceLabsLauncher.ts
- packages/test-runner-saucelabs/src/SauceLabsLauncherManager.ts
- packages/test-runner-saucelabs/test-remote/saucelabsLauncher.test.js
- packages/test-runner/demo/saucelabs.config.mjs
This improves the logic of closing browsers when testing ends, and makes the logic around closing the browstack/saucelabs proxy more paranoid. This hopefully improves stability and reduces zombie proxies staying opened.
> feat(test-runner): improve browser close logic

- .changeset/cuddly-pugs-type.md
- packages/test-runner/src/startTestRunner.ts
It looks like the `--puppeteer` and `--playwright` flags overwrite the user defined browsers option without notifying the user.
This change throws an error to the user, as there is confusion about the user's intent. The flags should only be used as a shorthand to set up the defaults.
> feat(test-runner): throw when combining browser config and flags

- docs/docs/dev-server/node-api.md
In my extension of web-dev-server I have my own CLI arguments that need to work on top of the web-dev-server CLI arguments.
E.g. `my-dev-server --port 8080 --foo="bar"`
```js
if (opts.argv) {
const myServerDefinitions = [
{
name: 'foo',
type: String,
description:
'Foobar',
},
];
myConfig = {
...myConfig,
...commandLineArgs(myServerDefinitions, { argv: opts.argv }),
};
}
```
This would error because it does not recognize `port` as a valid CLI argument.
The fix would be importing the WDS option definitions:
```js
if (opts.argv) {
const myServerDefinitions = [
...optionDefinitions, // <-- adding the WDS definitions
{
name: 'foo',
type: String,
description:
'Foobar',
},
];
myConfig = {
...myConfig,
...commandLineArgs(myServerDefinitions, { argv: opts.argv }),
};
}
```
Although not necessary …
> feat(dev-server): export option definitions & readCliArgs for Node API

- .changeset/clever-bears-nail.md
- packages/test-runner-mocha/src/autorun.ts
Updated test-runner-mocha to avoid using `document.baseURI` since this is not supported in IE11.
> fix(test-runner-mocha): avoid using document.baseURI in IE11

- .changeset/seven-avocados-sing.md
- packages/test-runner-mocha/package.json
1. Mocha didn't get included in the breaking version bump.
> chore(test-runner-mocha): new version

- .changeset/honest-phones-kneel.md
- packages/test-runner-cli/src/reporter/reportTestsErrors.ts
Fixes https://github.com/modernweb-dev/web/issues/557
> feat(test-runner): always print stack traces in errors

- .changeset/wild-fans-tickle.md
- packages/test-runner-core/src/browser-launcher/BrowserLauncher.ts
- packages/test-runner-core/src/runner/TestScheduler.ts
- packages/test-runner-playwright/src/PlaywrightLauncher.ts
- packages/test-runner-playwright/src/index.ts
- packages/test-runner/demo/groups.config.mjs
When testing on firefox some tests can fail because firefox requires the browser window to be focused to fire focus/blur events. 
This adds an experimental mode for the playwright launcher where you can mark a browser launcher to be launched in a special "focus" mode. We first run all other tests, and then at the end launch the firefox browser and run tests with a concurrency of 1 to ensure the window is focused.
It's experimental so that we can test it out and see if it works. Then we can later unflag it.
> feat(test-runner-playwright): add experimental window focus mode

- .changeset/rich-comics-grow.md
- docs/docs/test-runner/browser-launchers/chrome.md
- docs/docs/test-runner/browser-launchers/playwright.md
- docs/docs/test-runner/browser-launchers/puppeteer.md
- packages/test-runner-chrome/src/ChromeLauncher.ts
- packages/test-runner-chrome/src/index.ts
- packages/test-runner-core/src/browser-launcher/BrowserLauncher.ts
- packages/test-runner-core/src/runner/TestScheduler.ts
- packages/test-runner-playwright/src/PlaywrightLauncher.ts
- packages/test-runner-playwright/src/index.ts
- packages/test-runner-puppeteer/src/puppeteerLauncher.ts
- packages/test-runner/demo/focus.config.mjs
- packages/test-runner/demo/test/focus/focus-a.test.js
- packages/test-runner/demo/test/focus/focus-b.test.js
- packages/test-runner/demo/test/focus/focus-c.test.js
- packages/test-runner/demo/test/focus/focus-d.test.js
- packages/test-runner/demo/test/focus/focus-e.test.js
- packages/test-runner/demo/test/focus/focus-f.test.js
- packages/test-runner/demo/test/focus/focus-g.test.js
- packages/test-runner/demo/test/focus/focus-h.test.js
- packages/test-runner/demo/test/focus/focus-i.test.js
- packages/test-runner/demo/test/focus/focus-j.test.js
- packages/test-runner/demo/test/focus/focus-k.test.js
- packages/test-runner/demo/test/focus/focus-l.test.js
- packages/test-runner/demo/test/focus/focus-m.test.js
- packages/test-runner/demo/test/focus/focus-n.test.js
- packages/test-runner/demo/test/focus/focus-o.test.js
- packages/test-runner/demo/test/focus/focus-p.test.js
- packages/test-runner/package.json
Concurrency can now be configured per browser launcher, for the chrome, puppeteer and playwright launchers. 
Among other things, this is needed for firefox because it doesn't allow testing focus on tabs which are backgrounded. Setting a concurrency of 1 fixes that.
Fixes https://github.com/modernweb-dev/web/issues/238
> feat(test-runner): allow setting concurrency per browser

- .changeset/cool-mails-rescue.md
- docs/docs/dev-server/node-api.md
- packages/dev-server-core/src/web-sockets/WebSocketsManager.ts
1. make the webSocketServer property of the WebSocketsManager public, so it can be used by users of Node API for WDS
2. add documentation about this
> feat(dev-server-core): expose websockets server on the manager

- docs/docs/test-runner/overview.md
Some of the links on https://modern-web.dev/docs/test-runner/overview/ result in 404s. I fixed the links to the plugins, but the links in the 1st bullet point are incorrect, too:
> Headless browsers with [Puppeteer](https://modern-web.dev/docs/test-runner/browsers/puppeteer/), [Playwright](https://modern-web.dev/docs/test-runner/browsers/playwright/), or [Selenium](https://modern-web.dev/docs/test-runner/browsers/selenium/)
But I don't know where they should link to
> docs(test-runner): fix links to esbuild/rollup plugins in overview

- .changeset/gentle-glasses-reflect.md
- packages/test-runner-mocha/src/autorun.ts
- packages/test-runner-mocha/src/mochaSetup.ts
- packages/test-runner-mocha/src/standalone.ts
Disabled the in-browser reporter during regular test runs, improving performance.
Defaulted to the spec reporter instead of the HTML reporter in the browser when debugging. This avoids manipulating the testing environment by default.
You can opt back into the old behavior by setting the mocha config:
```js
export default {
testFramework: {
config: { reporter: 'html' },
},
};
```
Fixes https://github.com/modernweb-dev/web/issues/720
> feat(test-runner-mocha): default to use spec reporter

- .changeset/odd-crabs-nail.md
- packages/rollup-plugin-copy/src/copy.js
Adds the copied files to the rollup watch list, this enables 'watched' rollup bundle scripts.
> fix(rollup-plugin-copy): adds copied files to watch list

- .changeset/shiny-gorillas-smash.md
- docs/docs/test-runner/cli-and-configuration.md
- integration/test-runner/index.ts
- integration/test-runner/tests/config-groups/browser-tests/test-runner-html-a.test.js
- integration/test-runner/tests/config-groups/browser-tests/test-runner-html-b.test.js
- integration/test-runner/tests/config-groups/runConfigGroupsTest.ts
- packages/test-runner-browserstack/test-remote/browserstackLauncher.test.ts
- packages/test-runner-chrome/test/chromeLauncher.test.ts
- packages/test-runner-core/src/config/TestRunnerGroupConfig.ts
- packages/test-runner-core/src/runner/createSessionGroups.ts
- packages/test-runner-core/src/server/plugins/serveTestRunnerHtmlPlugin.ts
- packages/test-runner-core/src/test-session/TestSessionGroup.ts
- packages/test-runner-playwright/test/playwrightLauncher.test.ts
- packages/test-runner-puppeteer/test/puppeteerLauncher.test.ts
- packages/test-runner-saucelabs/test-remote/saucelabsLauncher.test.ts
- packages/test-runner-selenium/test/seleniumLauncher.test.ts
Added the ability to configure the test runner HTML per test group. This is useful for running the same tests multiple times in different HTML pages, for instance loading different polyfils.
This fixes a part of https://github.com/modernweb-dev/web/issues/678
> feat(test-runner): allow configuring test runner HTML per group

- .changeset/short-months-look.md
- .changeset/smart-spiders-smash.md
- .changeset/sweet-starfishes-laugh.md
- packages/dev-server-core/src/plugins/transformModuleImportsPlugin.ts
- packages/dev-server-core/src/server/addPlugins.ts
- packages/dev-server-core/src/server/createPlugins.ts
- packages/dev-server-core/src/server/createServer.ts
- packages/dev-server-import-maps/test/resolving.test.ts
- packages/dev-server-legacy/package.json
- packages/dev-server-legacy/src/babelTransform.ts
- packages/dev-server-legacy/src/constants.ts
- packages/dev-server-legacy/src/injectPolyfillsLoader.ts
- packages/dev-server-legacy/src/legacyPlugin.ts
- packages/dev-server-legacy/test/transform-html.test.ts
- packages/dev-server-legacy/test/transform-js.test.ts
- packages/dev-server/src/config/parseConfig.ts
- packages/test-runner/src/startTestRunner.ts
1. Only transform es modules to systemjs
2. Ensure user plugins are always run after builtin plugins
Fixes https://github.com/modernweb-dev/web/issues/726
Fixes https://github.com/modernweb-dev/web/issues/725
> [dev-server-legacy] Only transform modules to system js

- .changeset/twelve-vans-cross.md
- packages/dev-server-esbuild/src/EsbuildPlugin.ts
1. filter unsupported sourcemap warnings
Fixes https://github.com/modernweb-dev/web/issues/582
> feat(dev-server-esbuild): filter unsupported sourcemap warnings

- docs/docs/dev-server/plugins/import-maps.md
1. Fixed a typo in `include` key of importMapsPlugin documentation.
> docs(dev-server): fix typo

- .changeset/dull-years-smile.md
- packages/parse5-utils/README.md
- packages/parse5-utils/src/index.js
Fixes parse5-utils export syntax to ensure the generated type declarations are correct.
> fix(parse5-utils): export using direct assignment

- .changeset/modern-chairs-dream.md
- packages/test-runner-cli/src/reporter/getCodeCoverage.ts
1. Add message when coverage not met for a specific type of threshold as discussed in https://github.com/modernweb-dev/web/issues/688
Tested with: https://github.com/Bubbit/web/blob/example/coverage/packages/test-runner/demo/babel-coverage.config.js#L12
Which results in:
> feat: add coverage failure per type when below threshold

- docs/guides/test-runner/using-typescript.md
`npx typescript --init` doesn't work; it is `npx tsc --init`
1. fix CLI command in docs
> fix cli command for typescript init

- .changeset/stale-pandas-boil.md
- packages/dev-server-storybook/src/html/createPreviewHtml.ts
1. Fixed a bug where loading multiple stories creates invalid syntax
> fix(dev-server-storybook): fix loading multiple stories

- .changeset/strong-moles-approve.md
- packages/rollup-plugin-html/src/assets/utils.ts
- packages/rollup-plugin-html/test/src/input/extract/extractAssets.test.ts
1. Updated the `isAsset` test to return `false` when the path to the file pointed to a remote location.
> fix(rollup-plugin-html): prevent remote URLs from counting as assets

- .changeset/thin-fireants-scream.md
- packages/rollup-plugin-polyfills-loader/src/createPolyfillsLoaderConfig.ts
- packages/rollup-plugin-polyfills-loader/src/rollupPluginPolyfillsLoader.ts
- packages/rollup-plugin-polyfills-loader/test/fixtures/entrypoint-a.js
- packages/rollup-plugin-polyfills-loader/test/fixtures/entrypoint-b.js
- packages/rollup-plugin-polyfills-loader/test/fixtures/shared.js
- packages/rollup-plugin-polyfills-loader/test/snapshots/multiple-entrypoints.html
- packages/rollup-plugin-polyfills-loader/test/snapshots/no-polyfills.html
- packages/rollup-plugin-polyfills-loader/test/snapshots/systemjs.html
- packages/rollup-plugin-polyfills-loader/test/src/rollupPluginPolyfillsLoader.test.ts
Fixed preloading of non-module entrypoints, using the correct crossorigin attribute.
> fix(rollup-plugin-polyfills-loader): correctly preload non-module entrypoints

- .changeset/small-readers-mix.md
- packages/rollup-plugin-html/demo/spa/index.html
- packages/rollup-plugin-html/demo/spa/src/no-module.js
- packages/rollup-plugin-html/src/assets/utils.ts
- packages/rollup-plugin-html/src/input/extract/extractModules.ts
- packages/rollup-plugin-html/test/fixtures/assets/no-module.js
- packages/rollup-plugin-html/test/src/input/extract/extractAssets.test.ts
- packages/rollup-plugin-html/test/src/input/extract/extractModules.test.ts
- packages/rollup-plugin-html/test/src/output/injectedUpdatedAssetPaths.test.ts
- do not touch `<script>` tags with inline content/code
- treat `<script src="...">` tags as assets
> fix(rollup-plugin-html): handle none module script tags

- docs/docs/test-runner/cli-and-configuration.md
Guess this makes the example clearer. Hope I'm seeing it in the correct way :)
Otherwise we could have only one group `package-a` and improving the glob to something like `'packages/{a,b}/test/**/*.test.js'`
1. Renamed the group name to `package-b` in order to match the directory example.
> docs: group example naming consistency

- .github/workflows/verify-browserstack.yml
- .github/workflows/verify-saucelabs.yml
Any pull request from a fork will fail to run the BrowserStack and Sauce Labs tests, because secrets are not shared with actions run on forks.
Change the behavior of the BrowserStack and Sauce Labs tests to run only when the PR is from the `modernweb-dev/web` repository.
> fix: don't run actions that need secrets on pull requests

- renovate.json5
Created a config file for Renovate, which we can use to automatically update our dependencies.
Alternative to #801, closes #780.
> Create Renovate config file

- .changeset/thirty-maps-double.md
- docs/docs/dev-server/plugins/hmr.md
- packages/dev-server-hmr/src/hmrClientScript.ts
Fixes #805.
This separates the 'catch all' accept() we have right now to:
```ts
acceptDeps([dep1, dep2], ([dep1, dep2]) => { ... });
accept((module) => { ... });
```
this does mean we've diverged from the esm-hmr repo but i will feed back into that as vite has also done this same implementation.
> [dev-server-hmr] add acceptDeps callback to hmr client

- .changeset/chilly-lemons-learn.md
- packages/dev-server-hmr/src/HmrPlugin.ts
In the `_dependencyTree` you seem to rely on paths being converted to how they look on the OS for Windows this is look a bit different, hence why we can't use posix here.
> (web-dev-hmr) - Windows compatability

- .changeset/afraid-carrots-guess.md
- packages/dev-server-hmr/src/HmrPlugin.ts
- packages/dev-server-hmr/src/hmrClientScript.ts
Fixes a syntax issue in the client script and bubbling by not eagerly clearing deps
Fixes: https://github.com/modernweb-dev/web/issues/883
> (dev-server-hmr) - fix hmr bubbling and a syntax issue in the hmrClientScript

- package.json
- packages/dev-server-hmr/test/HmrPlugin.test.ts
- packages/dev-server-import-maps/test-browser/test/import-map-a.test.html
- packages/dev-server-import-maps/test-browser/test/mocks/postData.js
- packages/dev-server-import-maps/test-browser/web-test-runner.config.mjs
- packages/dev-server-import-maps/test/resolving.test.ts
- packages/dev-server-rollup/package.json
- packages/dev-server-rollup/test/node/unit.test.ts
- packages/rollup-plugin-import-meta-assets/test/integration.test.js
- packages/test-runner-core/package.json
- packages/test-runner-core/test/src/runner/TestRunner.test.ts
- packages/test-runner-core/test/src/runner/TestScheduler.test.ts
- yarn.lock
Here's the branch i mentioned recently, trying to drop sinon for its size.
If its something you're interested in, let me know.
Note that because how some of the tests in this repo are written, they may look a bit more complex now. it would be solved by better keeping track of stubs/spies rather than using the "override" style sinon uses (`real.method.callCount`).
Also sinon is still referenced in the test runner docs and what looks like an example file/repo from those docs.
> remove sinon in place of smaller module

- packages/dev-server-core/package.json
- packages/dev-server-esbuild/package.json
- packages/dev-server-rollup/package.json
- renovate.json5
1. Changed the version string for `node-fetch` to remove the "v" (https://github.com/renovatebot/renovate/issues/7755)
2. Automatically merge minor updates that aren't `0.x` (patch updates will always be merged)
> Renovate: automerge minor updates that aren't 0.x

- .changeset/sweet-insects-buy.md
- packages/test-runner-cli/src/config/readConfig.ts
Ensures that minimal concurrency is 1. On small VM (with 1 cpu), max concurrency could be 0.5 so the test suite never starts.
> fix(test-runner-cli): avoid under 1 concurrency

- .changeset/spotty-dolphins-sin.md
- packages/test-runner-selenium/src/seleniumLauncher.ts
1. Added heartbeat timeout to `test-runner-selenium` for keeping connection alive in SauceLabs
Fixes #945 
Note: it would make more sense to implement this in `@web/test-runner-saucelabs` but that would require some refactoring, e.g. we need to expose `driver` instance, which is currently private, to setup the heartbeat interval.
> feat(test-runner-selenium): add heartbeat timeout

- .changeset/smooth-feet-care.md
- packages/test-runner-selenium/src/seleniumLauncher.ts
1. Moved the logic related to clearing the heartbeat interval to `stop` method
2. Moved the inialization of the interval to ensure it is only performed once
> fix(test-runner-selenium): clear heartbeat properly

- .changeset/heavy-swans-arrive.md
- packages/dev-server/package.json
- packages/tsconfig.project.json
1. Removed obsolete `@wev/dev-server-cli` dependency to get rid of warning:
```sh
$ npm i @web/dev-server -D
npm WARN deprecated @web/dev-server-cli@0.0.3: This packages is merged into @web/dev-server
```
> chore: cleanup dev-server-cli leftovers

- docs/docs/test-runner/writing-tests/html-tests.md
Add a package to the imports so that `expect` will be defined.
> docs(html-tests): fix error when following the docs

- .changeset/chilled-otters-stare.md
- packages/dev-server-hmr/src/HmrPlugin.ts
- packages/dev-server-hmr/test/HmrPlugin.test.ts
This is a slight cleanup of the hmr bubbling logic.
We had cases where the update method could return without emitting a message. I have now removed this so we can assume if an update runs, a message is ultimately triggered one way or another.
This now means the recent check that was added (`dependents.size === 0`) is valid since, if we reach that point, it is guaranteed nothing else has emitted a message.
> fix(hmr): clean up bubbling logic

- .changeset/shy-olives-arrive.md
- packages/test-runner/src/startTestRunner.ts
Run node-resolve after using plugins, so that another plugin can resolve imports instead of node-resolve.
> fix(test-runner): run node-resolve after using plugins

- .changeset/metal-terms-poke.md
- packages/test-runner-webdriver/src/webdriverLauncher.ts
1. Updated type from `wdio` to `webdriver` (this will be used later in the visual regression plugin)
> fix(test-runner-webdriver): rename launcher type

- .changeset/young-ducks-raise.md
- packages/test-runner-visual-regression/package.json
- packages/test-runner-visual-regression/src/visualRegressionPlugin.ts
- packages/test-runner-visual-regression/tsconfig.json
- tsconfig.json
1. Added Webdriver launcher support to `@web/test-runner-visual-regression`.
This feature is recommended to be used with `concurrency: 1` to avoid permanent switching between iframes.
> feat(test-runner-visual-regression): add webdriver support

- .changeset/unlucky-ads-share.md
- packages/dev-server/src/logger/createLogger.ts
- packages/test-runner-cli/src/terminal/DynamicTerminal.ts
- Updated the ANSI escape codes in `dev-server` and `test-runner-cli` so it doesn't clear the scrollback history.
When I'm developing, I sometimes need to scroll up to see the results of a previous command. This isn't possible if `dev-server` clears the scrollback history. In addition, my terminal emulator (iTerm) blocks this escape code from working by default and displays a warning message. I think `dev-server` should not try to clear the scrollback history.
The ANSI escape codes used are the following:
- `\x1B[2J`: clear entire screen
- `\x1B[3J`: clear entire screen and erase scrollback history
- `\x1B[H`: move the cursor to the top-left corner
I deleted the second escape code. This still clears the screen and moves the cursor, but it doesn't erase the scrollback history.
I verified …
> fix: don't clear scrollback history

- .changeset/strong-mayflies-cheat.md
- packages/test-runner-visual-regression/src/pixelMatchDiff.ts
- packages/test-runner-visual-regression/src/visualDiffCommand.ts
The generated artifacts for the failed and diff images couldn't be viewed.
The diff image was written both as the failed and as the diff.
The diff image was written incorrectly.
1. Fixed bugs for diff and failed images generated by the visual-regression package
> Visual regression diff fix

- .changeset/green-ligers-fold.md
- .changeset/polite-planes-wash.md
- package.json
- packages/dev-server-rollup/package.json
- packages/dev-server-storybook/package.json
- packages/dev-server-storybook/src/build/rollup/createRollupConfig.ts
- packages/dev-server/package.json
- packages/dev-server/src/plugins/nodeResolvePlugin.ts
- packages/rollup-plugin-workbox/package.json
- yarn.lock
Updates all packages to use node-resolve v11, which added support for package "exports" and "imports"fields. This is a breaking change, since it changes the resolve logic for some packages.
Do not merge this until https://github.com/rollup/plugins/pull/693 is merged.
> feat: update to node-resolve v11

- .changeset/four-seals-refuse.md
- .eslintignore
- .gitignore
- packages/dev-server-core/package.json
- packages/dev-server-core/src/middleware/serveFilesMiddleware.ts
- packages/dev-server-core/src/server/createMiddleware.ts
- packages/dev-server-core/test/fixtures/outside-root-dir/node_modules/foo/index.js
- packages/dev-server-core/test/helpers.ts
- packages/dev-server-core/test/middleware/serveFilesMiddleware.test.ts
- packages/dev-server-rollup/src/rollupAdapter.ts
- packages/dev-server-rollup/src/utils.ts
- packages/dev-server-rollup/test/node/unit.test.ts
- packages/dev-server/demo/node-resolve/config.mjs
- packages/test-runner/demo/test/chai.js
- yarn.lock
This fixes a long-standing issue with es-dev-server, web dev server and web test runner where it can't serve modules outside of the root directory of the web server.
When we encounter a file resolved to a path outside of the root dir we rewrite it with the following pattern:
```
/__wds-outside-root__/${depth}/${originalPath}
``` 
When we see an import with this path server side, we look at the depth walk up the file system with the specified depth:
```js
const newRootDir = path.join(rootDir, '../'.repeat(depth));
```
This avoids dumping the whole file path in the browser URL.
Resolving modules becomes a more plug-and-play experience. Users won't need to expand the root directory anymore in monorepo projects (`--root-dir ../../`) and for demo pages the URL doesn't need to include the …
> feat(dev-server-core): handle modules resolved outside root dir

- packages/dev-server-esbuild/src/esbuildPluginFactory.ts
Kinda surprised when I call `hmrPlugin()` and found this error
```
@web/dev-server-esbuild/dist/esbuildPluginFactory.js:7
const target = (_a = args.target) !== null && _a !== void 0 ? _a : 'auto';
^
TypeError: Cannot read property 'target' of undefined
```
Although calling `hmrPlugin({})` works fine.
1. add `{}` as default args since all keys are optional
> fix(dev-server-esbuild): handle calling without parameters

- .changeset/twenty-camels-train.md
- packages/test-runner-webdriver/src/webdriverLauncher.ts
Lazily create webdriver connection. This avoids opening a connection for each browser from the start, instead creating them only when we start running tests on a browser.
> fix(test-runner-saucelabs): lazily create webdriver connection

- .changeset/thick-teachers-fry.md
- packages/test-runner/src/reporter/utils/createStackLocationRegExp.ts
- packages/test-runner/src/reporter/utils/getRelativeStackFilePath.ts
When resolving source maps for logged stack traces, we now include the URL parameters which are important for example for the legacy and import map plugins.
> fix(test-runner): include URL params when resolving stack traces

- .changeset/soft-ants-confess.md
- packages/dev-server-core/src/plugins/mimeTypesPlugin.ts
1. Match dotfiles when resolving mimetypes fixes https://github.com/modernweb-dev/web/issues/1125
> fix(dev-server-core): match dotfiles when resolving mimetypes

- .changeset/tender-houses-repair.md
- packages/dev-server/src/config/parseConfig.ts
- packages/test-runner/src/config/parseConfig.ts
Dev server and test runner now filter out non-object plugins from the config. This allow patterns like `foo && myPlugin` or `foo ? myPlugin : undefined`.
> feat: filter out non-object plugins from config

- .changeset/six-moons-film.md
- packages/test-runner-core/src/cli/terminal/DynamicTerminal.ts
Reverts https://github.com/modernweb-dev/web/pull/1024 because it was creating double logs when scrolling up. I notice that both Jest and TSC also don't allow scrolling up either. Perhaps they use a different method, something to look into.
> fix(test-runner-core): add clear scrollback history back

- .changeset/six-moons-film.md
- packages/test-runner-core/src/cli/TestRunnerCli.ts
- packages/test-runner-core/src/runner/TestRunner.ts
- packages/test-runner/demo/tsc/config.mjs
- packages/test-runner/demo/tsc/test/chai.ts
- packages/test-runner/demo/tsc/test/pass-1.test.ts
- packages/test-runner/demo/tsc/test/pass-10.test.ts
- packages/test-runner/demo/tsc/test/pass-11.test.ts
- packages/test-runner/demo/tsc/test/pass-12.test.ts
- packages/test-runner/demo/tsc/test/pass-13.test.ts
- packages/test-runner/demo/tsc/test/pass-14.test.ts
- packages/test-runner/demo/tsc/test/pass-15.test.ts
- packages/test-runner/demo/tsc/test/pass-16.test.ts
- packages/test-runner/demo/tsc/test/pass-17.test.ts
- packages/test-runner/demo/tsc/test/pass-18.test.ts
- packages/test-runner/demo/tsc/test/pass-19.test.ts
- packages/test-runner/demo/tsc/test/pass-2.test.ts
- packages/test-runner/demo/tsc/test/pass-20.test.ts
- packages/test-runner/demo/tsc/test/pass-3.test.ts
- packages/test-runner/demo/tsc/test/pass-4.test.ts
- packages/test-runner/demo/tsc/test/pass-5.test.ts
- packages/test-runner/demo/tsc/test/pass-6.test.ts
- packages/test-runner/demo/tsc/test/pass-7.test.ts
- packages/test-runner/demo/tsc/test/pass-8.test.ts
- packages/test-runner/demo/tsc/test/pass-9.test.ts
- packages/test-runner/demo/tsc/test/shared-a.ts
- packages/test-runner/demo/tsc/test/shared-b.ts
- packages/test-runner/demo/tsc/tsconfig.json
- packages/test-runner/package.json
1. Reduce delay when clearing the terminal between test runs. This prevents flickering of test logs
> fix(test-runner-core): reduce delay when clearing terminal between test runs

- .changeset/good-cycles-tickle.md
- packages/dev-server-core/src/middleware/pluginTransformMiddleware.ts
- packages/dev-server-core/src/middleware/serveFilesMiddleware.ts
- packages/dev-server-core/src/utils.ts
- packages/dev-server-rollup/src/rollupAdapter.ts
fix handling of paths resolved outside the root dir. we now correctly use the resolved path when resolving relative imports and when populating the transform cache
> fix(dev-server): fix handling of paths outside root dir

- .github/workflows/verify-browserstack.yml
- .github/workflows/verify-node.yml
- .github/workflows/verify-saucelabs.yml
- .github/workflows/verify-windows.yml
- renovate.json
After discussion with @LarsDenBakker, we are trying to reduce noise by only opening PRs for major updates and catching minor updates with the weekly lock file maintenance. I also included a couple improvements to the configuration.
Specific changes:
1. Disabled minor (> 0.x) and patch updates
1. Disabled running CI on Renovate branches (since we aren't doing branch automerging anymore, we only need CI on PRs)
1. Replaced `separateMinorPatch` rule with equivalent `:separatePatchReleases` preset
1. Replaced `lockFileMaintenance` rule with equivalent `:maintainLockFilesWeekly` preset
1. Added `:separateMultipleMajorReleases` preset to separate each available major version of dependencies into individual PRs
1. Added `:widenPeerDependencies` preset to always widen `peerDependencies` semver …
> chore: Update Renovate config

- .changeset/flat-eyes-join.md
- packages/dev-server-esbuild/src/EsbuildPlugin.ts
Just found out that `define` option is not being used by dev-server-esbuild despite it's declared in the `EsBuildPluginArgs` and `EsbuildConfig` interface
1. pass `esbuildconfig.define` to esbuild transform function
> fix(dev-server-esbuild): pass `esbuildconfig.define` to esbuild transform function

- docs/docs/test-runner/browser-launchers/playwright.md
1. Updated the lines changed by #1151 which added some Puppeteer mentions to the Playwright page.
> docs: restore launch options link for Playwright

- .changeset/blue-laws-hide.md
- docs/docs/building/rollup-plugin-html.md
- packages/rollup-plugin-html/src/RollupPluginHTMLOptions.ts
- packages/rollup-plugin-html/src/assets/utils.ts
- packages/rollup-plugin-html/src/input/extract/extractAssets.ts
- packages/rollup-plugin-html/src/input/extract/extractModules.ts
- packages/rollup-plugin-html/src/input/extract/extractModulesAndAssets.ts
- packages/rollup-plugin-html/src/input/getInputData.ts
- packages/rollup-plugin-html/src/output/createHTMLOutput.ts
- packages/rollup-plugin-html/src/output/getOutputHTML.ts
- packages/rollup-plugin-html/src/output/injectedUpdatedAssetPaths.ts
- packages/rollup-plugin-html/src/rollupPluginHTML.ts
- packages/rollup-plugin-html/test/rollup-plugin-html.test.ts
If you are using absolute URLs for your assets and want to deploy to a sub directory then all your absolute links/urls will need to start with `/my-sub-directory/`. To still be able to find the actual assets you need to provide this `absolutePathPrefix`.
PS: the only relevant codechange is this
```js
const _browserPath =
absolutePathPrefix && browserPath[0] === '/'
? '/' + path.relative(absolutePathPrefix, browserPath)
: browserPath;
```
the rest is only to pass around `absolutePathPrefix`
> feat(rollup-plugin-html): add absolutePathPrefix for subfolder deployment

- .changeset/fifty-flies-study.md
- packages/test-runner-browserstack/package.json
- packages/test-runner-chrome/package.json
- packages/test-runner-cli/package.json
- packages/test-runner-commands/package.json
- packages/test-runner-core/package.json
- packages/test-runner-coverage-v8/package.json
- packages/test-runner-junit-reporter/package.json
- packages/test-runner-mocha/package.json
- packages/test-runner-playwright/package.json
- packages/test-runner-puppeteer/package.json
- packages/test-runner-saucelabs/package.json
- packages/test-runner-selenium/package.json
- packages/test-runner-visual-regression/package.json
- packages/test-runner-webdriver/package.json
- packages/test-runner/package.json
Drop support for node v10 and v11 in the test runner.
> feat(test-runner): drop support for node v10 and v11

- .changeset/wise-owls-bake.md
- packages/dev-server-rollup/src/rollupAdapter.ts
allow resolving extensionless absolute file paths
> fix(dev-server-rollup): allow resolving extensionless absolute file paths

- docs/docs/test-runner/cli-and-configuration.md
Update docs to reflect the right defaults
See:
https://github.com/modernweb-dev/web/blob/master/packages/test-runner/src/config/parseConfig.ts#L35
> chore: fix timeout docs for wtr

- .changeset/lazy-grapes-call.md
- packages/rollup-plugin-workbox/README.md
- packages/rollup-plugin-workbox/src/index.ts
- remove `@web` usage in the README.md
- remove `mode` from the config that is passed to workbox.
> Remove "mode" from passed workbox config. Remove @web from import statements.

- .changeset/quiet-mice-call.md
- packages/test-runner-core/package.json
- packages/test-runner-coverage-v8/package.json
- packages/test-runner/package.json
When running web-test-runner with yarn v2, PnP module resolution warns about imports of packages not declared as dependencies in the module:
```
$ yarn web-test-runner --puppeteer
(node:47320) [MODULE_NOT_FOUND] Error: debug tried to access supports-color (a peer dependency) but it isn't provided by its ancestors; this makes the require call ambiguous and unsound.
(Use `node --trace-warnings ...` to show where the warning was created)
(node:47320) [MODULE_NOT_FOUND] Error: @web/test-runner-core tried to access chokidar, but it isn't declared in its dependencies; this makes the require call ambiguous and unsound.
(node:47320) [MODULE_NOT_FOUND] Error: @web/test-runner-core tried to access convert-source-map, but it isn't declared in its dependencies; this makes the require call ambiguous …
```
> Fix undeclared dependencies

- .changeset/perfect-onions-roll.md
- packages/dev-server/src/config/parseConfig.ts
- packages/test-runner/src/config/parseConfig.ts
Adds backwards compatibility for "middlewares" property, this helps migrating configs written for es-dev-server where the config option was misspelled a `middlewares`.
> chore: add backwards compatibility for "middlewares" property

- .changeset/rude-countries-pretend.md
- docs/docs/test-runner/cli-and-configuration.md
- packages/test-runner-core/src/cli/writeCoverageReport.ts
- packages/test-runner-core/src/config/TestRunnerCoreConfig.ts
- packages/test-runner/src/config/parseConfig.ts
- packages/test-runner/src/reporter/getCodeCoverage.ts
1. add a reporters option for coverageConfig allowing to use [alternative istanbul reporters](https://istanbul.js.org/docs/advanced/alternative-reporters/) for code coverage
> feat(test-runner): add coverageConfig.reporters configuration option

- package.json
- yarn.lock
1. Rocket checks links already so the separate remark task to check them is no longer needed
> chore: remove remark lint as rocket has link checking

- .changeset/mighty-clocks-relax.md
- packages/test-runner-webdriver/src/IFrameManager.ts
1. Use `executeAsync` when setting the iframe src to an empty page, and wait until the load (or error) event fires before returning the frame to `inactiveFrames`
This appears to resolve the intermittent `testsStartTimeout` timeouts we've seen on Safari when running on Sauce, reported in #1216.
Fixes #1216
> fix(test-runner-webdriver) Wait until the page unloads before reusing frame

- .changeset/heavy-rabbits-sin.md
- packages/test-runner/src/reporter/getTestProgress.ts
As discussed in #1234. Some notes:
- The contributing documentation didn't include any specific notes on how to run tests for the repository, but I think I got them to work via `yarn build && yarn test`. At least one test complained about Selenium not being able to start up; maybe it would be nice to have some documentation on how to get things up and running (or provide an install script that installs required system dependencies.)
- It didn't look like there was a specific test for this functionality, and considering the simplicity of the change, I did not bother adding one.
> Don't use red text color when there are 0 failures

- .changeset/long-ads-drum.md
- packages/browser-logs/src/parseStackTrace.ts
- packages/test-runner-core/src/server/plugins/serveTestFrameworkPlugin.ts
- packages/test-runner-mocha/package.json
- packages/test-runner-mocha/rollup.config.js
- rollup.browser.config.js
- yarn.lock
This change filters out stack traces of internal packages, such as `@web/test-runner-mocha` and `@web/test-runner-core/browser/session.js`
> feat(test-runner): filter out internal stack traces

- docs/docs/test-runner/browser-launchers/playwright.md
Fixes #1243
1. Found links to https://github.com/microsoft/playwright/blob/master/docs/* and replaced them with the proper links to https://playwright.dev
> docs: update playwright dev documentation links

- .changeset/breezy-ducks-give.md
- packages/test-runner-coverage-v8/src/index.ts
When converting coverage from v8 to istanbul, webpack bundled files are returned with a specific webpack protocol. This is because of the inline source maps. We can't fetch the source maps for these files back from the server, so we skip them entirely for now.
> feat(test-runner): skip non-http test coverage files

- .changeset/nine-pears-invent.md
- packages/parse5-utils/src/index.js
- packages/parse5-utils/test/index.test.js
1. Replaced comments passed to `isHtmlFragment` with empty string.
```
function isHtmlFragment(html) {
let htmlWithoutComments = html.replace(//g, '');
return !REGEXP_IS_HTML_DOCUMENT.test(htmlWithoutComments);
}
```
2. Add test which checks `isHtmlFragment('<!DOCTYPE><my-element></my-element>')` is false.
> fix(parse5-utils): ignore comments in isHtmlFragment

- .changeset/cold-flowers-laugh.md
- packages/dev-server-core/src/web-sockets/webSocketsPlugin.ts
- packages/test-runner-core/src/server/plugins/api/testRunnerApiPlugin.ts
Falls back to fetch instead of using a websocket on IE11. Let's see if this improves stability.
> fix(test-runner): fallback to fetch on IE11

- .changeset/friendly-forks-pull.md
- .changeset/warm-bears-check.md
- packages/test-runner-saucelabs/package.json
- packages/test-runner-webdriver/package.json
- packages/test-runner-webdriver/src/IFrameManager.ts
- packages/test-runner-webdriver/src/SessionManager.ts
- packages/test-runner-webdriver/src/webdriverLauncher.ts
- yarn.lock
1. Updated `webdriverio` too v7 and fixed TypeScript compilation errors
@LarsDenBakker please note, the tests for the package are still skipped.
Closes #1285
> feat(webdriver): update webdriverio to v7

- package.json
- yarn.lock
1. Updated `@types/mocha` to  get rid of the following warning:
```
warning Pattern ["@types/mocha@^8.0.01"] is trying to unpack in the same destination "/Users/sergey/Library/Caches/Yarn/v6/npm-@types-mocha-8.2.0-3eb56d13a1de1d347ecb1957c6860c911704bc44-integrity/node_modules/@types/mocha" as pattern ["@types/mocha@^8.2.0"]. This could result in non-deterministic behavior, skipping.
```
> chore: update mocha types to remove warning

- .changeset/smart-humans-remember.md
- packages/parse5-utils/src/index.js
- packages/parse5-utils/test/index.test.js
1. Allow break lines when checking isHtmlFragment
Reference: https://github.com/modernweb-dev/web/pull/1284#issuecomment-777316386
> fix(parse5-utils): allow break lines when checking isHtmlFragment

- .changeset/mighty-pandas-brake.md
- packages/polyfills-loader/src/createPolyfillsLoader.ts
- packages/polyfills-loader/src/types.ts
- packages/polyfills-loader/test/createPolyfillsLoader.test.ts
- packages/polyfills-loader/test/snapshots/createPolyfillsLoader/custom-polyfills-dir.js
- packages/polyfills-loader/test/snapshots/createPolyfillsLoader/polyfills-initializer.js
- packages/polyfills-loader/test/snapshots/createPolyfillsLoader/polyfills-module.js
- packages/polyfills-loader/test/snapshots/createPolyfillsLoader/relative-polyfills-dir.js
- packages/rollup-plugin-polyfills-loader/src/rollupPluginPolyfillsLoader.ts
- packages/rollup-plugin-polyfills-loader/src/types.d.ts
- packages/rollup-plugin-polyfills-loader/test/fixtures/non-flat/index.html
- packages/rollup-plugin-polyfills-loader/test/snapshots/flattened.html
- packages/rollup-plugin-polyfills-loader/test/snapshots/non-flattened.html
- packages/rollup-plugin-polyfills-loader/test/src/rollupPluginPolyfillsLoader.test.ts
1. Added optional `relativePathToPolyfills` config option to `@web/polyfills-loader`
2. Changed `@web/rollup-plugin-polyfills-loader` to set `relativePathToPolyfills` based on the relative path between `polyfillsDir` and the input html file.
Fixes #1290
> fix(rollup-plugin-polyfills-loader): fix relative paths to polyfills with flattenOutput: false

- packages/rollup-plugin-workbox/README.md
This brings the missing `=` in the README examples.
> Fix JS syntax in readme examples

- packages/test-runner-playwright/package.json
- yarn.lock
1. Re-floor the playwright dependency to force consumers onto a version that supports macOS11
1. Confirm Monday whether any further changes here are needed to ensure stability in this OS
> chore: update Playwright dependency

- .changeset/nasty-actors-laugh.md
- packages/rollup-plugin-polyfills-loader/src/rollupPluginPolyfillsLoader.ts
1. Remove relative path because importPath is already relative.
What was wrong?
- Trying to build a project in a folder close to system root (`/`) for example: `/app` when you try to calculate the `patToRoot` of `entrypoint.importPath = '../../../[hash].js' you always get `..` because it's relative to /app and there are no more directories. The correct way is to calculate direct the dirname of the entrypoint, because it's actually relative to index.html.
> fix(rollup-plugin-polyfills-loader): calculate pathToRoot correctly

- .changeset/sharp-birds-build.md
- packages/rollup-plugin-polyfills-loader/src/createPolyfillsLoaderConfig.ts
- packages/rollup-plugin-polyfills-loader/src/rollupPluginPolyfillsLoader.ts
- packages/rollup-plugin-polyfills-loader/test/snapshots/customize-filetype-multi-output.html
- packages/rollup-plugin-polyfills-loader/test/snapshots/customize-filetype.html
- packages/rollup-plugin-polyfills-loader/test/snapshots/flattened.html
- packages/rollup-plugin-polyfills-loader/test/src/createPolyfillsLoaderConfig.test.ts
- packages/rollup-plugin-polyfills-loader/test/src/rollupPluginPolyfillsLoader.test.ts
1. Allows changing the output filetype when using only a modern build
```js
polyfillsLoader({
modernOutput: { name: 'modern', type: 'systemjs' },
polyfills: { webcomponents: true, fetch: true },
}),
```
> fix(rollup-plugin-polyfills-loader): allow changing filetype of only modern output

- .changeset/few-sloths-grin.md
- packages/test-runner-visual-regression/src/config.ts
- packages/test-runner-visual-regression/src/pixelMatchDiff.ts
- packages/test-runner-visual-regression/src/visualDiffCommand.ts
1. Move mismatched size error up into diff command.
2. When images mismatch create two new images of the largest width/height from the initial screenshots.
3. Copy the original images into the new images.
4. Diff the synthetic screenshots.
In this was the following baseline, current, and diff screenshots will be created by the test pass:
> fix(test-runner-visual-regression): allow mismatched screenshot sizes to be diffed

- .changeset/famous-snakes-beg.md
- packages/rollup-plugin-import-meta-assets/src/rollup-plugin-import-meta-assets.js
Fixes #1366 by outputting [hi-res sourcemaps](https://github.com/Rich-Harris/magic-string#sgeneratemap-options-).
> fix(rollup-plugin-import-meta-assets): fix outputted sourcemaps

- .changeset/happy-balloons-speak.md
- packages/polyfills-loader/package.json
- packages/test-runner-mocha/package.json
- packages/test-runner/package.json
- packages/test-runner/src/config/parseConfig.ts
This PR addresses #1374 by modifying the config merge for `coverageConfig` to use object spread assignment.
> fix(test-runner): fixes coverageConfig merge with default by switching to object spread

- .changeset/lovely-cats-draw.md
- packages/rollup-plugin-import-meta-assets/src/rollup-plugin-import-meta-assets.js
Fixes https://github.com/modernweb-dev/web/issues/1379 by skipping sourcemap generation when the plugin has not modified the code (per recommendation at https://rollupjs.org/guide/en/#source-code-transformations).
> fix(rollup-plugin-import-meta-assets): skip unnecessary sourcemap generation

- .changeset/healthy-lizards-attack.md
- packages/dev-server-rollup/src/rollupAdapter.ts
- packages/dev-server-rollup/src/utils.ts
- packages/dev-server-rollup/test/node/fixtures/resolve-outside-dir/node_modules/module-a/index.js
- packages/dev-server-rollup/test/node/fixtures/resolve-outside-dir/node_modules/module-a/package.json
- packages/dev-server-rollup/test/node/fixtures/resolve-outside-dir/src/app.js
- packages/dev-server-rollup/test/node/plugins/node-resolve.test.ts
Right now, files outside the root dir are not correctly served when using a rollup plugin in combination with the node resolve option. Multiple `resolveImport` passes result in `/__wds-outside-root__/<n>/__wds-outside-root__/<n>/<module>/<file>`.
1. Added a check for already resolved files outside the `rootDir`
> Do not resolve multiple times outside root files

- .changeset/friendly-eels-fetch.md
- packages/dev-server-core/src/web-sockets/webSocketsPlugin.ts
WebSocket should be created using the server url instead of the runtime location (script may be imported from a differente origin).
1. Stored the server url using the `serverStart` hook
2. Replaced the url argument of the `WebSocket` constructor
> Detect websocket url from server

- .changeset/strange-chefs-raise.md
- packages/dev-server-esbuild/src/esbuildPluginFactory.ts
Esbuild plugin overrides the js loader passed by options if target has been passed as well.
1. Added a check for js loader configuration
> Do not override js loader with esbuild target

- .changeset/sixty-mugs-float.md
- packages/dev-server-esbuild/package.json
- packages/dev-server-esbuild/src/EsbuildPlugin.ts
- packages/dev-server-esbuild/test/target.test.ts
- packages/dev-server-esbuild/test/ts.test.ts
- yarn.lock
Since version 0.9.0, esbuild removed the service api, that is no longer needed.
1. Updated constraint and lock
2. Replaced service calls
3. Updated tests
> Upgrade to esbuild ^0.11.0

- .changeset/violet-adults-brake.md
- packages/browser-logs/package.json
- packages/dev-server-hmr/package.json
- packages/dev-server-hmr/test/browser.test.ts
- packages/dev-server/package.json
- packages/test-runner-chrome/package.json
- packages/test-runner-chrome/src/ChromeLauncher.ts
- packages/test-runner-chrome/src/index.ts
- packages/test-runner-puppeteer/package.json
- packages/test-runner-puppeteer/src/puppeteerLauncher.ts
- packages/test-runner-visual-regression/src/visualRegressionPlugin.ts
- yarn.lock
1. Updated `puppeteer-core` and `puppeteer` versions to 8.0.0
Closes #1254 
Closes #1255 
Closes #1260
Closes #1261
Closes #1322 
Closes #1323
> feat: update puppeteer and puppeteer-core to 8.0.0

- packages/dev-server-core/src/plugins/transformModuleImportsPlugin.ts
- packages/dev-server-esbuild/package.json
- packages/dev-server-esbuild/test/ts.test.ts
Since version 0.4.0, `es-module-lexer` exposes a `n` property for each import specifier with its unescaped source. This is useful (and more accurate) for virtual modules like `\0commonHelpers`.
1. try to use the `n` property of the specifier, fallback to the previous version if missing.
> Use unescaped import specifier

- packages/dev-server-esbuild/src/browser-targets.ts
The purpose of this PR is to update the wording when certain browsers are not found, so the end user knows which specific browser was not found.
1. Updated wording to reflect the browser names of what wasn't found.
> Updated browser-targets.ts wording

- .changeset/good-dolphins-attend.md
- packages/browser-logs/src/deserialize.ts
- packages/browser-logs/test/serialize-deserialize.test.ts
Bound function were not correctly handled by the browser logs module.
1. Convert `bound fn` to `fn` in order to avoid syntax errors
> Deserialize bound function from browser logs

- .changeset/many-pans-judge.md
- packages/test-runner-core/src/coverage/getTestCoverage.ts
Fixes https://github.com/modernweb-dev/web/issues/689
See also https://github.com/istanbuljs/v8-to-istanbul/issues/121
1. This PR updates `addingMissingCoverageItems` to also add missing functions. This can occur when a function is defined in another function, and the outer function is not called in every test run. For example methods defined on a class using arrow functions `=>` are only created when the constructor runs. Specifically, I have moved the code inside the loops out into their own functions, so they can be called with the branch coverage data and the function coverage data.
> fix(test-runner): fix error when function metadata varies between tests

- .changeset/tidy-ads-help.md
- packages/dev-server-rollup/src/rollupAdapter.ts
- packages/dev-server-rollup/test/node/fixtures/private-imports/import-private-directly.html
- packages/dev-server-rollup/test/node/fixtures/private-imports/index.html
- packages/dev-server-rollup/test/node/fixtures/private-imports/internal-a.js
- packages/dev-server-rollup/test/node/fixtures/private-imports/package.json
- packages/dev-server-rollup/test/node/plugins/node-resolve.test.ts
- yarn.lock
1. Support for subpath imports
👉 `my-pkg/package.json`
```json
{
"name": "my-pkg",
"imports": {
"#internal-a": "./path/to/internal-a.js"
}
}
```
👉 `my-pkg/src/file.js`
```js
import { private } from '#internal-a';
```
Subpath imports are not available to users of your package
👉 `other-pkg/src/file.js`
```js
// both will fail
import { private } from 'my-pkg#internal-a';
import { private } from 'my-pkg/path/to/internal-a.js';
```
closes https://github.com/modernweb-dev/web/issues/1321
> fix(dev-server-rollup): support private imports

- .changeset/tall-jokes-wave.md
- packages/rollup-plugin-html/src/output/getOutputHTML.ts
Adds the missing publicPath argument to the _injectedUpdatedAssetPaths_ call, so linked assets also get the prefix applied. Previously the default of './' was always used.
Fixes #1302
> fix(rollup-plugin-html): use publicPath for emitting assets

- .changeset/young-wolves-worry.md
- docs/docs/building/rollup-plugin-html.md
- packages/rollup-plugin-html/package.json
- packages/rollup-plugin-html/src/RollupPluginHTMLOptions.ts
- packages/rollup-plugin-html/src/output/getOutputHTML.ts
- packages/rollup-plugin-html/test/src/output/getOutputHTML.test.ts
- yarn.lock
Adds a default minify option to the HTML plugin. We didn't want to do this initially, but I see a good use case for it now. We don't allow customizing the options, so we're not coupled to a specific implementation. If users need customization, they can still implement their own minifier.
> feat(rollup-plugin-html): add minify option

- .changeset/two-mangos-allow.md
- packages/test-runner-junit-reporter/src/junitReporter.ts
> fix(test-runner-junit-reporter): strip invalid XML characters in stdout

- .changeset/mighty-chicken-invite.md
- docs/docs/test-runner/commands.md
- packages/test-runner-commands/src/sendKeysPlugin.ts
- packages/test-runner-commands/test/send-keys/browser-test.js
Currently it is not possible to send a key combination using the sendKeys command in all test runners that the plugin supports. The original PR states in the [changeset](https://github.com/modernweb-dev/web/commit/ce90c7c36dc53b03ba98fe47f83eadf427009137#diff-ae1d797ecb266266783436e2ef62e5ed325be942cf34b476e82c72490b651bdaR10) that combinations such as `Shift-Tab` are supported by the `press` command, which is not true from my testing (also there are no tests to verify this). My understanding is that Playwright supports it, but Puppeteer does not.
To solve this, this change introduces two additonal actions / properties to the sendKeys command: `down` and `up`. These allow to hold down a key, and then release a key. This effectively allows pressing key combinations or trigger other …
> Add support for holding and releasing keys to the sendKeys command

- .changeset/plenty-kangaroos-design.md
- docs/docs/building/rollup-plugin-copy.md
- packages/rollup-plugin-copy/src/copy.js
- packages/rollup-plugin-copy/src/listFiles.js
- packages/rollup-plugin-copy/src/patternsToFiles.js
Added `exclude` option for rollup-plugin-copy.
Example: Exclude single directory:
```js
copy({ pattern: '**/*.svg', exclude: 'node_modules' })
```
Example: Exclude multiple globs:
```js
copy({ pattern: '**/*.svg', exclude: ['node_modules', 'src/graphics'] })
```
> feat(rollup-plugin-copy): exclude

- .changeset/angry-pandas-fry.md
- integration/test-runner/tests/test-failure/browser-tests/fail-circular-error.test.js
- integration/test-runner/tests/test-failure/runTestFailureTest.ts
- packages/dev-server-core/src/web-sockets/webSocketsPlugin.ts
- yarn.lock
1. use code from `fast-safe-stringify` to stringify error messages across the ws channel.
2. Since `fast-safe-stringify` is cjs, I just copy-pasted.
BEFORE:
AFTER:
This comes up often in apollo-elements, since ApolloClient has circular references, and it causes tests to hang without logging useful information to the console. If the user 'debugs' in a live browser, they can read the logs in the devtools console, but they might not think to do that.
Also relevant to highcharts, other circular objects
> fix(test-runner): handle test exceptions with circular components

- .changeset/cuddly-buttons-turn.md
- docs/docs/building/rollup-plugin-import-meta-assets.md
- packages/rollup-plugin-import-meta-assets/src/rollup-plugin-import-meta-assets.js
- packages/rollup-plugin-import-meta-assets/test/integration.test.js
- packages/rollup-plugin-import-meta-assets/test/snapshots/transform-bundle-ignored.js
This allows users who pre-process a subset of assets separately to
skip processing the assets via this plugin.
As part of https://crrev.com/c/2939994 I am working on optimizing
our SVG assets dynamically. However, we also have other image
formats in our source tree, including `.png` and `.avif`. These images
are pre-optimized and we aren't sure yet whether we want to
dynamically optimize this during build time (as that tends to be
computationally expensive work).
However, when trying to integrate the plugin, I discovered that our
build system (GN + Ninja) started complaining about files being
out-of-date. I then discovered that the `.png` and `.avif` assets
were double copied: once by us in GN and once in the plugin.
I then attempted to include only the SVG files using `include` and was …
> feat(rollup-plugin-import-meta-assets): allow transform to skip processing asset

- .changeset/small-timers-sort.md
- packages/test-runner-junit-reporter/src/junitReporter.ts
1. gated the replace behind the presence of replace
I know there has to be something underlying this issue, but I can't seem to find it... this change safely allows the use of replace without seeming to break anything else, so I'd like your thoughts.
> fix: allow stripXMLInvalidChars when replace it not available

- .changeset/silly-pans-prove.md
- packages/browser-logs/src/logUncaughtErrors.ts
add extra logging when catching an unhandled rejection
> feat(browser-logs): add extra logging when catching an unhandled rejection

- .changeset/shy-frogs-hug.md
- .changeset/ten-pens-tease.md
- packages/test-runner-core/src/coverage/getTestCoverage.ts
1. Add a `findEncompassingKey` function to `getTestCoverage.ts`
2. Use this instead of `findKey` in `patchCoverageItems`
Those two changes allow `patchCoverageItems` to fallback to an encompassing branch coverage status when adding an unreported branch to a session report.
The reasoning for this change is described here: https://github.com/modernweb-dev/web/issues/1468#issuecomment-864518266.
This Pull Request fixes #1468.
I came up with this solution through trial & error, analysing the output of `coverage` maps received from the various sessions. I'm not sure whether this fix is proper or only a patchwork on a patchwork.
I tested the solution on a large codebase and only saw positive consequences, but I cannot guarantee that this does not bring unintended side-effects. I'd really …
> Fix coverage branch fusion

- .changeset/famous-turtles-compete.md
- packages/test-runner-commands/src/snapshotPlugin.ts
- packages/test-runner/demo/test/__snapshots__/pass-snapshot.test.snap.js
When dynamically importing a module using a data URL, it cannot start with a comment on firefox on safari. On Chrome it works fine. It's quite a strange bug.
This change uses a variable instead for the version marker.
> fix(test-runner): make snapshots work on all browsers

- .changeset/curly-cheetahs-argue.md
- packages/dev-server-rollup/src/rollupAdapter.ts
1. Fully resolve `resolvedImportPath` for files outside of the root before passing to plugins.
Using rollup plugins like `@rollup/plugin-commonjs` in a monorepo environment. In these cases we can be serving dependencies from outside of the 'root' (where we're executing the test runner or WDS). In these cases we were previously passing the `/__wds-outside-root__/` prefix to the plugins which was causing them to not resolve the files being processed properly. Doing full path resolution seems to fix it.
> fix(dev-server): fixes #1536, correctly handle outside-root paths

- .changeset/little-fans-shake.md
- docs/docs/building/rollup-plugin-html.md
- packages/rollup-plugin-html/src/RollupPluginHTMLOptions.ts
- packages/rollup-plugin-html/src/input/getInputData.ts
- packages/rollup-plugin-html/test/fixtures/rollup-plugin-html/exclude/assets/partial.html
- packages/rollup-plugin-html/test/fixtures/rollup-plugin-html/exclude/index.html
- packages/rollup-plugin-html/test/rollup-plugin-html.test.ts
1. add `exclude` option to rollup-plugin-html
User wishes to exclude assets (for example, 11ty html file _includes_, `playground-elements/playground-service-worker-proxy.html`) from the build.
in`rocket.config.js`
```js
setupBuildPlugins: [
adjustPluginOptions('html', {
ignore: ['**/_assets/**/*.html', '**/_merged_assets/**/*.html'],
}),
],
```
> feat(rollup-plugin-html): exclude files

- .changeset/curvy-actors-dance.md
- packages/test-runner-commands/src/snapshotPlugin.ts
- packages/test-runner-commands/test/snapshot/__snapshots__/browser-test.snap.js
- packages/test-runner-commands/test/snapshot/snapshotPlugin.test.ts
- packages/test-runner-commands/test/snapshot/src/__snapshots__/nested-test.snap.js
- packages/test-runner/demo/test/__snapshots__/pass-snapshot.test.snap.js
1. I changed the way markers are done in snapshots because Firefox and Webkit have some problems with line comments, and using block comments seems to work properly.
> fix(test-runner): use block comments in snapshots to make them work in all browsers

- .changeset/thin-pigs-call.md
- packages/test-runner-commands/browser/commands.mjs
- packages/test-runner-commands/test/snapshot/browser-test.js
1. First, I modified the test to be able to reproduce the issue. In order to do that I had to add an option to avoid the use of the snapshots memory cache, and secondly, add a random number in the file content before import it to avoid browser cache.
2. Then, I escaped the carriage returns in the snapshot. Otherwise, Firefox and Webkit seem to have problems.
> fix(test-runner): escape snapshots to make them work in firefox and webkit

- .changeset/spotty-llamas-sit.md
- package.json
- packages/dev-server-rollup/package.json
- packages/dev-server-storybook/package.json
- packages/dev-server/package.json
- packages/rollup-plugin-workbox/package.json
- packages/test-runner-commands/test/snapshot/snapshotPlugin.test.ts
- yarn.lock
1. Reverted the #1433 by downgrading `@rollup/plugin-node-resolve` to 11.x
2. Removed the `describe.only` to make sure all the tests are executed
Fixes #1568 
Closes #1567
> fix: downgrade @rollup/plugin-node-resolve

- docs/docs/dev-server/plugins/import-maps.md
1. Fix typo in config file name
> docs(import-maps): fix typo in web dev server config file name

- .changeset/tall-mice-shout.md
- packages/test-runner-saucelabs/package.json
- packages/test-runner-webdriver/package.json
- packages/test-runner-webdriver/src/webdriverLauncher.ts
- yarn.lock
1. Updated `webdriverio` dependency to 7.9.0
2. Added type casts to get rid of the following TS error:
```
Argument of type 'BrowserAsync | undefined' is not assignable to parameter of type 'BrowserAsync'.
```
3. Removed an accidentally added and unneeded dependency.
> feat: bump webdriverio version to 7.9.0

- .changeset/chatty-zebras-dress.md
- packages/test-runner-chrome/package.json
- packages/test-runner-core/package.json
1. Moved `@types/babel__code-frame` from `@web/test-runner-chrome` dev dependencies to the `@web/test-runner-core` where this dependency is actually used, and added it to `dependencies` to align with the other types dependencies.
> fix: move Babel types to the correct package

- docs/guides/test-runner/typescript.md
This question has come up frequently in the last few days, so it makes sense to highlight it in the docs
1. Add a short 'guides' page detailing how to test ts sources using `esbuildPlugin`
> docs: add esbuild plugin to test-runner docs

- .changeset/seven-rocks-judge.md
- package.json
- packages/dev-server-rollup/package.json
- packages/dev-server-rollup/test/node/rollupBundlePlugin.test.ts
- yarn.lock
1. Updated Rollup dependency to 2.56.2
2. Fixed tests to align with the change landed in 2.55 - https://github.com/rollup/rollup/pull/4182 (see [this article](https://jakearchibald.com/2021/export-default-thing-vs-thing-as-default/) for an overview of how the mutable live bindings work).
> fix: update Rollup dependency to 2.56.2

- .changeset/four-owls-smash.md
- .changeset/moody-taxis-cheat.md
1. Removed `@web/dev-server` from the changeset
Both @web-padawan and @abdonrd caught this inclusion in #1625 Hard to track where it came in as this package is no longer touched by the changes listed in that closed PR. I've remove it from the changeset to prevent it bumping version.
> Fix up changeset to only include @web/dev-server-storybook

- .changeset/six-camels-knock.md
- packages/rollup-plugin-workbox/package.json
- packages/rollup-plugin-workbox/src/index.ts
- packages/rollup-plugin-workbox/tsconfig.json
- yarn.lock
1. Updated `workbox-build` to the latest version which comes with types: https://github.com/GoogleChrome/workbox/pull/2867
2. Removed no longer needed `@types/workbox-build`
3. Updated the `generateSw` and `injectManifest` types. Note, `RollupPartial` is used to align with [`WebpackPartial`](https://github.com/GoogleChrome/workbox/blob/0074b20b17b8047a6d9ecd7d9082778a61ad0468/packages/workbox-build/src/types.ts#L169-L179).
> feat: update workbox-build dependency to 6.2.4

- .changeset/happy-singers-own.md
- packages/test-runner-visual-regression/src/visualDiffCommand.ts
this makes it easy and quick to open the diff from the CLI, inspect the results, and work out what went wrong
1. Append file path for diff image to existing error message
> feat(test-runner-visual-regression): output diff file path on failure

- .changeset/gold-needles-jump.md
- packages/test-runner-visual-regression/README.md
- packages/test-runner-visual-regression/src/config.ts
- packages/test-runner-visual-regression/src/visualDiffCommand.ts
- packages/test-runner-visual-regression/src/visualRegressionPlugin.ts
by supplying test name to each of the extensibility points, it becomes easier to store images relative to the test itself.
For example, this will store snapshot images in a directory adjacent to the test file:
```js
visualRegressionPlugin({
getBaselineName: ({ name, browser, testFile }) =>
path.join(testFile, "..", "screenshots", browser, "baseline", name),
getDiffName: ({ browser, name, testFile }) =>
path.join(testFile, "..", "screenshots", browser, "failed", `${name}-diff`),
getFailedName: ({ browser, name, testFile }) =>
path.join(testFile, "..", "screenshots", browser, "failed", name),
});
```
1. Added `testFile` property to `GetNameArgs`
2. Passed `session.testFile` from plugin through to extensibility points like `getBaselineName` etc
3. Updated README
> feat(test-runner-visual-regression): add testName to GetNameArgs

- docs/docs/dev-server/cli-and-configuration.md
- docs/docs/test-runner/cli-and-configuration.md
1. Both the dev server and test runner docs were missing CLI flags. I documented them using the description from the `--help` output.
2. I reordered the CLI flag documentation to match the order output by `--help`
3. Fix documented type for `--open` and `--app-index` for the dev server (was listed as boolean, is actually string)
> docs: add missing flags and match --help ordering

- .changeset/cuddly-snails-beg.md
- packages/browser-logs/src/deserialize.ts
- packages/browser-logs/test/serialize-deserialize.test.ts
fixes https://github.com/modernweb-dev/web/issues/1557
1. The serializer currently crashes on function names containing a hyphen (in objects, e.g. `{'a-b': ()=>{}}`, because the deserializer tries to revive them like so:
```js
new Function(`return function my-function() {}`);
```
which is invalid
> fix: support method names in objects containing a dash

- .changeset/pink-lobsters-develop.md
- packages/test-runner-commands/browser/commands.mjs
- packages/test-runner-commands/test/snapshot/browser-test.js
Fix #1690 by using `encodeURIComponent` to escape the snapshot content before building the data url instead of just escaping the line breaks. Please let me know if there's a better way to do this.
> fix: use encodeURIComponent to escape snapshot content

- docs/guides/going-buildless/serving.md
Updated the incorrect url as `help.html` should not be impacted.
> docs: rename incorrect url in serving guide

- docs/docs/building/rollup-plugin-html.md
1. Swapped lines in documentation to match correct spec in https://github.com/modernweb-dev/web/blob/master/packages/rollup-plugin-html/src/RollupPluginHTMLOptions.ts
> docs: update TransformAssetFunction docs to match type

- docs/guides/going-buildless/css.md
as discussed at WICG/webcomponents#945
still not a broadly supported
1. should note that?
2. is it even applicable due to lack of support?
1. added documentation on how to prevent custom elements from piercing
> docs(css): registering properties inheritance

- packages/test-runner-webdriver/test/webdriverLauncher.test.ts
1. Changed to use specific `geckodriver` version as `latest` does not seem to work.
> test: enable Webdriver launcher tests in Firefox

- .changeset/olive-trees-refuse.md
- packages/dev-server-core/src/web-sockets/webSocketsPlugin.ts
1. makes sure websockets also work for iframes in csp protected environments
Error I got
PS: this will enable usage of web dev sever in VS Code extensions 💪
> fix(dev-server-core): support iframes in a csp protected environment

- .changeset/shy-kangaroos-clap.md
- packages/dev-server-esbuild/src/EsbuildPlugin.ts
- packages/dev-server-esbuild/test/target.test.ts
1. dev-server-esbuild: fix "importmap" or other non-js type in html file
> fix: do not process scripts with non-JS type attribute

- .github/workflows/verify-node.yml
1. Added Node 16 LTS to the testing matrix.
> chore: add Node 16 LTS to GitHub Actions

- .github/workflows/release.yml
1. Updated Node version to 16, maybe this helps to run the release workflow (for now it is always skipped).
> chore: update release workflow to Node 16 LTS

- .changeset/curly-cameras-deliver.md
- packages/test-runner-visual-regression/src/visualDiffCommand.ts
1. in cases where diff percentage was very small the output would be like `New screenshot is 0.00% different` which is confusing
2. i kept formatting to 2 decimal places when the value is large enough, otherwise output the raw value
3. this avoid cases as in (1)
> fix(test-runner-visual-regression): improve output when very small diff percentage

- .changeset/real-oranges-protect.md
- package.json
- packages/test-runner-commands/browser/commands.d.ts
- packages/test-runner-commands/browser/commands.mjs
- packages/test-runner-commands/src/index.ts
- packages/test-runner-commands/src/sendMousePlugin.ts
- packages/test-runner-commands/test/selenium-server.ts
- packages/test-runner-commands/test/send-mouse/browser-test.js
- packages/test-runner-commands/test/send-mouse/sendMousePlugin.test.ts
- packages/test-runner-webdriver/src/IFrameManager.ts
- packages/test-runner-webdriver/src/SessionManager.ts
- packages/test-runner-webdriver/src/webdriverLauncher.ts
```ts
function sendMouse(payload: {
type: 'move',
position: [number, number]
}): Promise<void>;
```
```ts
function sendMouse(payload: {
type: 'click',
position: [number, number],
button?: 'left' | 'middle' | 'right'
}): Promise<void>;
```
```ts
function sendMouse(payload: {
type: 'down',
button?: 'left' | 'middle' | 'right'
}): Promise<void>;
```
```ts
function sendMouse(payload: {
type: 'up',
button?: 'left' | 'middle' | 'right'
}): Promise<void>;
```
It is possible to extend the command's API in the future to also support sending a sequence of mouse actions, e.g.:
```js
await sendMouse([
{ type: 'move', position: [100, 100] },
{ type: 'move', position: [200, 200] }
]);
```
> feat: add sendMouse command

- .changeset/fluffy-mugs-cheat.md
- packages/dev-server-storybook/package.json
- yarn.lock
1. Update `@web/storybook-prebuilt`
2. Update `storybook-addon-markdown-docs`
Now using Storybook v6.4!
And bye bye to `next` and `alpha` versions.
> chore(deps): update @web/storybook-prebuilt

- .changeset/shy-singers-love.md
- packages/test-runner-commands/browser/commands.d.ts
- packages/test-runner-commands/browser/commands.mjs
- packages/test-runner-commands/src/sendMousePlugin.ts
- packages/test-runner-commands/test/send-mouse/browser-test.js
- packages/test-runner-webdriver/src/webdriverLauncher.ts
This PR adds a `resetMouse` command intended to be used after mouse manipulations by the `sendMouse` command to reset the mouse state and avoid potential side effects caused by the mouse being at a certain position or a mouse button being held down.
Here is an example of the command usage:
```js
it('does something with the mouse', () => {
await sendMouse({ type: 'move', position: [150, 150] });
await sendMouse({ type: 'down', button: 'middle' });
});
afterEach(() => {
await resetMouse();
});
```
A follow-up on #1783
1. Extended `sendMousePlugin` to support a `resetMouse` command.
2. Added unit tests.
> feat: add resetMouse command

- .changeset/purple-hounds-yawn.md
- docs/docs/test-runner/commands.md
1. Added documentation for the `sendMouse` command.
2. Added documentation for the `resetMouse` command.
A follow-up on https://github.com/modernweb-dev/web/pull/1783
Related to https://github.com/modernweb-dev/web/pull/1808#issuecomment-994404709
> docs: document sendMouse command

- docs/docs/test-runner/commands.md
It turns out that I didn't close correctly `<details>` tag when writing docs for the `resetMouse` command in #1816. In consequence, all the content following the command became hidden. So I'm fixing that here in this PR.
> docs: close details tag in commands docs

- .changeset/hot-ladybugs-tan.md
- .changeset/long-adults-compare.md
- .github/workflows/verify-windows.yml
- packages/test-runner-core/src/test-helpers.ts
- packages/test-runner-junit-reporter/src/junitReporter.ts
- packages/test-runner-junit-reporter/test/fixtures/multiple/expected.xml
- packages/test-runner-junit-reporter/test/fixtures/nested/expected.xml
- packages/test-runner-junit-reporter/test/fixtures/simple/expected.xml
- packages/test-runner-junit-reporter/test/fixtures/simple/simple-source.js
- packages/test-runner-junit-reporter/test/fixtures/simple/simple-test.js
- packages/test-runner-junit-reporter/test/junitReporter.test.ts
- packages/test-runner-selenium/test/seleniumLauncher.test.ts
- packages/test-runner-webdriver/test/webdriverLauncher.test.ts
1. update the XML format with line numbers
2. add a test case that includes a source file (for stack traces)
3. fix tests to run properly
4. run all windows node tests against the production build
> [test-runner-junit-reporter] Add filepaths and line numbers to output

- .changeset/lucky-starfishes-attend.md
- docs/docs/test-runner/cli-and-configuration.md
- packages/test-runner-core/src/runner/collectTestFiles.ts
- packages/test-runner-core/test/src/runner/TestRunner.test.ts
1. evaluate test runner `files` config as a glob array
> fix(test-runner-core): evaluate files globs together

- .github/workflows/canary.yml
- .github/workflows/release.yml
- .github/workflows/verify-browserstack.yml
- .github/workflows/verify-node.yml
- .github/workflows/verify-saucelabs.yml
- .github/workflows/verify-windows.yml
Added a workaround for cache issue that causes GitHub Actions to fail:
```
Post job cleanup.
/usr/local/bin/yarn --version
1.22.17
/usr/local/bin/yarn cache dir
/home/runner/.cache/yarn/v6
Error: Cache folder path is retrieved for yarn but doesn't exist on disk: /home/runner/.cache/yarn/v6
```
See https://github.com/TryGhost/Ghost/commit/aec14e5cf34bbb96720e303c32e1cae3fc884169
See https://github.com/actions/setup-node/issues/317#issuecomment-929694556
> chore: disable FORCE_COLOR on GitHub Actions

- .changeset/kind-owls-rest.md
- packages/test-runner/src/config/parseConfig.ts
This PR adds `sendMousePlugin` to the default test runner config so that it will load automatically. This will fix the error that occurs when trying to use the `sendMouse` or `resetMouse` command:
> Error: Error while executing command reset-mouse: Unknown command reset-mouse. Did you install a plugin to handle this command?
> fix: add sendMousePlugin to the default test runner config

- docs/docs/dev-server/writing-plugins/hooks.md
1. Added custom HTTP response header creation to the transform hook examples.
> docs: Add transform hook example for custom HTTP headers

- .changeset/chilled-tables-obey.md
- packages/polyfills-loader/src/createPolyfillsData.ts
- packages/polyfills-loader/test/createPolyfillsData.test.ts
1. actually always load es-module-shims if the `'always'` configuration option is used
> fix: always load EMS for config option 'always'

- docs/docs/test-runner/test-frameworks/write-your-own.md
1. this commit fixes two small typos in the first line of the page:
- 'wrap' to 'wrapping'
- 'once' to 'one'
> docs: fix typos in write your own test framework page

- .changeset/tough-cups-report.md
- packages/dev-server-storybook/package.json
- yarn.lock
1. Hopefully this cleans up some of the dependency vulnerabilities, but it's also the first step of a larger (read breaking) change to `storybook-addon-markdown-docs` that will convert it to ESM and upgrade a number of similarly converted/breaking dependencies.
> fix: use latest "storybook-addon-markdown-docs"

- .changeset/unlucky-radios-peel.md
- packages/test-runner-core/src/config/TestRunnerCoreConfig.ts
- packages/test-runner-core/src/server/TestRunnerServer.ts
1. Passed http2/ssl configuration options from WTR into the underlying DevServer instance to allow tests served over HTTPS
> feat(test-runner-core): allow http2/ssl opts in config

- .changeset/hungry-tomatoes-rescue.md
- packages/dev-server-esbuild/package.json
- yarn.lock
1. Changed the semver from `^0.12.21` to `^0.12 || ^0.13 || ^0.14`.
I'm not sure how to check for all possible incompatibilities, but all tests still run when checking with the latest `0.12.x`, `0.13.x` and `0.14.x` version.
> Relax esbuild semver dependency

- .changeset/check-tty-stop-early-exit.md
- packages/test-runner-core/src/cli/terminal/DynamicTerminal.ts
- Husky was running WTR but would exit early with error level 0 before running any tests.
- Found out that process.stdin.isTTY was undefined when running with husky since it runs in a non-tty environment.
- Noticed that after doing anything with process.stdin, node would crash or exit (no error report or notice). 
- Also experienced the same problem when setting up CI in TeamCity.
- add a check for isTTY to be true so that non-tty environments do not crash or exit the process with error level 0.
> fix: check isTTY to prevent node from crashing/exiting early

- packages/dev-server-storybook/package.json
The changelog is not added by NPM as a default: https://docs.npmjs.com/cli/v7/configuring-npm/package-json#files
The file is quite handy to have though for quick reference when updating dependencies to check what has changed.
> Add CHANGELOG to publish output

- .changeset/modern-plants-return.md
- .github/workflows/verify-windows.yml
- packages/dev-server-rollup/package.json
- packages/dev-server-rollup/test/node/plugins/node-resolve.test.ts
1. Update `@rollup/plugin-node-resolve` to v13 to support node entry points containing stars
Fixes https://github.com/modernweb-dev/web/issues/1376
Fixes https://github.com/modernweb-dev/web/issues/1443
Fixes https://github.com/modernweb-dev/web/issues/1575
Fixes https://github.com/modernweb-dev/web/issues/1568
This is an iteration of https://github.com/modernweb-dev/web/pull/1633
> fix: support node entry points containing stars

- .changeset/ninety-eyes-attack.md
- packages/dev-server-rollup/src/rollupAdapter.ts
- packages/dev-server-rollup/test/node/fixtures/resolve-outside-dir-foo/index.js
- packages/dev-server-rollup/test/node/fixtures/resolve-outside-dir-foo/package.json
- packages/dev-server-rollup/test/node/fixtures/resolve-outside-dir-foo/resolve-outside-dir-foo
- packages/dev-server-rollup/test/node/fixtures/resolve-outside-dir/node_modules/resolve-outside-dir-foo
- packages/dev-server-rollup/test/node/fixtures/resolve-outside-dir/src/app.js
- packages/dev-server-rollup/test/node/plugins/node-resolve.test.ts
Appends a path separator to the rootDir to ensure we are actually testing that the resolved import path is inside the directory of the current rootDir. This then allows packages with common name prefixes to work properly.
NOTE: to test this I have committed a symlink that links the `node_modules/resolve-outside-dir-foo` package into the fixture for the test. This is necessary so that the node_module resolution happens, and so that the resolved file is a sibling folder of the rootDir.
fixes https://github.com/modernweb-dev/web/issues/1944
> fix(dev-server-rollup): fix rootDir test for packages with common names

- docs/docs/test-runner/cli-and-configuration.md
The example given for excluding `node_modules` has a typo in it.
1. changed '!**/node_module/**/*' ->  '!**/node_modules/**/*'
> Fix small typo in cli-and-configuration.md

- .changeset/cold-avocados-greet.md
- packages/test-runner-coverage-v8/src/index.ts
1. Added a guard for external urls when collecting coverage
2. Fixed some linting errors
> Ignore external urls from coverage

- .changeset/polite-shoes-tap.md
- packages/dev-server-storybook/src/shared/config/readStorybookConfig.ts
Fix a small typo in the readStorybookConfig
> fix: typo in error message thrown in readStorybookConfig

- .changeset/light-months-attend.md
- packages/test-runner-commands/package.json
Explicitly tell it to look for the types in `commands.d.ts`. Fixes compile error with `"moduleResolution": "node16"` in typescript 4.7.
> Fix node16 module resolution.

- .changeset/slimy-scissors-learn.md
- packages/test-runner/package.json
1. Added types in exports map
This allows types to be imported when using "moduleResolution": "Node16" in TypeScript.
> fix: add types field to package.json exports

- docs/guides/going-buildless/serving.md
1. `cd` into the path mentioned in the text.
> docs: fix files outside the web root example

- .changeset/chatty-ghosts-argue.md
- packages/dev-server-rollup/package.json
- packages/dev-server-rollup/src/createRollupPluginContextAdapter.ts
- packages/dev-server-rollup/src/rollupAdapter.ts
- yarn.lock
1. Updated `rollup` dependency range to `^2.67.0` to get latest version `2.75.5` installed
2. Added the new `moduleSideEffects` flag in addition to the the [deprecated `hasModuleSideEffects`](https://github.com/rollup/rollup/pull/4379)
3. Added the `null` check to fix ` Property 'code' does not exist on type 'void | SourceDescription'.`
> fix: update Rollup, use moduleSideEffects flag

- .changeset/popular-oranges-share.md
- packages/dev-server-core/src/web-sockets/WebSocketsManager.ts
dev-server use websocket for reloading.
When I use other websocket connections, it failed because dev-server handle all upgrade requests regardless of url.
1. Add if statement to handle upgrade requests only for dev-server.
> fix(dev-server-core): handle upgrade requests only for matched url

- .changeset/tough-bikes-study.md
- packages/test-runner-selenium/src/IFrameManager.ts
- packages/test-runner-webdriver/src/IFrameManager.ts
- packages/test-runner-webdriver/src/SessionManager.ts
This PR replaces navigations to `data:,` with `about:blank`. This lets the Safari extension installed by the version of Selenium used in Saucelabs' Safari 9 and 10 environments [recognize that it should not run](https://github.com/SeleniumHQ/selenium/blob/selenium-2.48.0/javascript/safari-driver/inject/tab.js#L234).
(Fixes #1986)
> Replace navigations to `data:,` with `about:blank`.

- .changeset/grumpy-badgers-raise.md
- packages/test-runner-playwright/src/PlaywrightLauncher.ts
- packages/test-runner-playwright/src/PlaywrightLauncherPage.ts
Fixed playwright memory leaks by ensuring that we use a new BrowserContext and Page for each test session:
* Create a BrowserContext per Page
* Removed reusing of Pages (since this would retain temporary objects in Playwright and leak memory since we'd be reusing the same BrowserContext).
> fix(test-runner-playwright): create BrowserContext per test page

- docs/docs/test-runner/testing-in-a-ci.md
The link to the Playwright manual was broken.
The use of the `microsoft/playwright-github-action` is discouraged ([You don't need this GitHub Action](https://github.com/microsoft/playwright-github-action#%EF%B8%8F-you-dont-need-this-github-action-%EF%B8%8F)). The recommended way is to install dependencies using the Playwright CLI commands.
> docs: update link to Playwright CI docs

- .changeset/long-schools-wink.md
- packages/dev-server-storybook/src/shared/stories/injectExportsOrder.ts
Using capital "D" `Default` is a super common pattern in Storybook creation. While we're pushing for `Regular` or similar in some of our CLI tooling, not allowing it at all is a surprising side effect for consumers of this package.
1. Remove `toLowerCase()` from export filtering.
> Keep "Default" stories

- docs/docs/test-runner/commands.md
Some browser commands are availble by default, but a11ysnapshot is not.
The error message reads: `Error: Error while executing command a11y-snapshot: Unknown command a11y-snapshot. Did you install a plugin to handle this command?` This is OK for someone who is familiar with Web Test Runner, but users getting started with testing could perhaps use a little bit more assistance. That's why I am proposing to add this section to the documentation.
1.
> docs: Instructions for enabling a11snapshot

- .changeset/proud-apples-give.md
- docs/docs/test-runner/commands.md
- packages/test-runner-commands/browser/commands.mjs
- packages/test-runner-commands/src/selectOptionPlugin.ts
- packages/test-runner-commands/test/select-option/playwright-test.js
- packages/test-runner-commands/test/select-option/puppeteer-test.js
- packages/test-runner-commands/test/select-option/selectOptionPlugin.test.ts
**Background**
Having written a few tests where selecting an option in a `<select>` was necessary, I've always found that the "normal" method of setting a select's value then programmatically triggering the events with `dispatchEvent` kinda breaks the testing paradigm of "interact like a user would" in the case of e2e tests. Using a driver based "select option" command, imo, better fits the model of interacting like a user, since the test code doesn't manually emit events then test if they fired. Tests can just call the `selectOption` command, and the browser will act as if the user clicked an option on the page.
Playwright and Puppeteer both implement a browser driver command for option selection that automatically emits native `change` and `input` events. This PR adds those commands as …
> Add selectOption command in test-runner-commands

- docs/docs/test-runner/overview.md
I feel like it is worth mentioning WebdriverIO as option for running tests.
> Mention WebdriverIO as option for headless browser testing

- .changeset/unlucky-turtles-fold.md
- packages/test-runner-visual-regression/src/config.ts
- packages/test-runner-visual-regression/src/pixelMatchDiff.ts
- packages/test-runner-visual-regression/src/visualDiffCommand.ts
1. add config option for setting a failure threshold by percent or number of pixels
2. check this value when diffing the image, and return appropriate message
3. improve console output when image size mismatch
> feat: add support for configuring the failure threshold

- docs/guides/test-runner/typescript.md
1. Fixes a small casing issue in the documentation.
> fix(readme): fix typescript.md typo

- docs/docs/dev-server/plugins/rollup.md
Using rollup-plugin-typescript-paths works great for resolving custom imports; like `@interal/helpers` via TS config paths.
Example usage:
```js
import { esbuildPlugin } from '@web/dev-server-esbuild';
import { fromRollup } from '@web/dev-server-rollup';
import rollupCommonjs from '@rollup/plugin-commonjs';
import { typescriptPaths as rollupTypescriptPaths } from 'rollup-plugin-typescript-paths';
import { chromeLauncher } from '@web/test-runner';
const commonjs = fromRollup(rollupCommonjs);
const typescriptPaths = fromRollup(rollupTypescriptPaths);
export default {
files: ['src/**/*.test.ts'],
coverage: true,
nodeResolve: true,
testFramework: {
config: {
ui: 'bdd',
timeout: '20000',
},
},
browsers: [
chromeLauncher({ launchOptions: { args: ['--no-sandbox'] } })
],
plugins: [ …
```
> Document possibility for TypeScript path resolving

- .changeset/loud-bugs-move.md
- packages/dev-server-core/package.json
- packages/dev-server/package.json
- packages/test-runner-browserstack/package.json
- packages/test-runner-core/package.json
- packages/test-runner-playwright/package.json
- packages/test-runner-saucelabs/package.json
- packages/test-runner/package.json
- yarn.lock
Updated `portfinder` version to `^1.0.32` to ensure it gets version of `async` with a vulnerability fix.
See https://github.com/caolan/async/pull/1828#issuecomment-1098568048 and https://github.com/http-party/node-portfinder/issues/126#issuecomment-1202005607.
Fixes #1934
> fix: update portfinder dependency to 1.0.32

- .changeset/wild-seas-sort.md
- packages/dev-server-storybook/src/shared/config/readStorybookConfig.ts
This PR checks if there's a `main.cjs` file and loads that as the storybook configuration file if it exists instead of `main.js`.
Closes https://github.com/modernweb-dev/web/issues/1832
Closes https://github.com/modernweb-dev/web/pull/1831
> [dev-server-storybook] Load a CommonJS config if one exists

- packages/dev-server-core/src/index.ts
- packages/dev-server-core/src/plugins/Plugin.ts
- packages/dev-server-rollup/src/createRollupPluginContextAdapter.ts
- packages/dev-server-rollup/src/rollupAdapter.ts
- packages/dev-server-rollup/test/node/plugins/commonjs.test.ts
It is possible a rollup plug injects its own child plugins by hooking into the rollup `options` hook and mutating the options to have extra plugs.
This change introduces a check for such plugins and calls them before the host plugin in case they successfully resolve a path first.
Similarly, the `resolve` method of plugins receives an options object to hold state for the resolution plugins. We currently lose this object when calling through to `resolveImport`, which can confuse third-party plugins/resolvers heavily.
To fix this, `resolveImport` now also accepts a `resolverOptions` so we can pass it on when calling child plugins.
cc @lucaelin as discussed in #1700
this was an incredibly deep rabbit hole of spaghetti code (outside modernweb), thanks a lot to lucaelin for figuring a bunch of …
> fix (dev-server-rollup): support child plugins in resolution algorithm

- .changeset/tasty-balloons-pay.md
- .github/workflows/canary.yml
- packages/dev-server-core/src/index.ts
- packages/dev-server-core/src/plugins/Plugin.ts
- packages/dev-server-rollup/src/createRollupPluginContextAdapter.ts
- packages/dev-server-rollup/src/rollupAdapter.ts
- packages/dev-server-rollup/test/node/plugins/commonjs.test.ts
1. Accepted @43081j's updates and pre-released them.
2. Users are testing them in https://github.com/modernweb-dev/web/issues/1700#issuecomment-1432372016
3. It's possible (though I'm likely lying to myself) that this support avoiding some of the failures in https://github.com/modernweb-dev/web/pull/2114
> Prepare release of CJS and Node Resolution updates

- .changeset/two-ants-explode.md
- packages/dev-server-rollup/src/rollupAdapter.ts
This is a second attempt to close #2078 (with #2079 being the first attempt).
The issue is that an absolute Windows path prefixed with a null byte is not a valid absolute file path, but it is (apparently) a valid URL (the null byte gets eaten as white space, and then the `C:` is interpreted as the URL scheme). However, in the context of processing Rollup plugins, the null byte is a signal that this path should be treated in a special way.
This fix explicitly checks for the null byte to avoid this issue, as discussed with @giamir and @43081j.
> fix(dev-server-rollup): fix rollup adapter resolution for virtual modules on Windows

- .changeset/kind-cycles-listen.md
- packages/dev-server-esbuild/package.json
- yarn.lock
Version `0.3.3` of `@web/dev-server-esbuild` uses `0.14.54` of esbuild. This version has a bug that breaks experimental typescript decorators. Apparently this has been known quite a while and the workaround is to fix the version to `0.2.16` of dev-server-esbuild.
This PR updates the esbuild dependency to 0.16 || 0.17.
All tests still pass.
fixes https://github.com/modernweb-dev/web/issues/1929
> Update `esbuild` dependency of `@web/dev-server-esbuild` to fix bug with decorators

- .changeset/seven-avocados-try.md
- packages/test-runner/src/index.ts
I cherry-picked the commit from https://github.com/modernweb-dev/web/pull/2113 since we need to land that before we can import the function in `browser-logs`
> Export the `formatError` function from test-runner

- .github/workflows/verify-node.yml
- packages/dev-server-import-maps/test/resolving.test.ts
Basically move to the current stable versions of node
also had to loosen up a test just because the error text changes between node versions slightly
> chore: bump node ci to 16/18/19

- .changeset/smooth-zoos-provide.md
- packages/rollup-plugin-workbox/package.json
- yarn.lock
As raised in #2212, this reverts #2208, which upgraded `pretty-bytes` from 5.6.0 to 6.1.0.
In that major version bump, `pretty-bytes` became an ESM-only package. Based on [their description](https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c), this package would also need to convert to ESM in order to adopt it, hence the revert.
Dependabot will likely attempt to upgrade this again, so not sure if you'd like me to add this to its ignore list?
> fix(rollup-plugin-workbox): revert back to non-ESM version of pretty-bytes

- .changeset/neat-toes-nail.md
- docs/docs/building/polyfills-loader.md
- packages/polyfills-loader/README.md
- packages/polyfills-loader/package.json
- packages/polyfills-loader/src/createPolyfillsData.ts
- packages/polyfills-loader/src/types.ts
- packages/polyfills-loader/test/createPolyfillsData.test.ts
- yarn.lock
1. Added support for the Scoped CustomElementRegistry polyfill https://github.com/webcomponents/polyfills/blob/master/packages/scoped-custom-element-registry/README.md
> feat(polyfills-loader): add support for Scoped CustomElementRegistry polyfill

- scripts/lint-versions.js
1. fix the `lint-versions.js` script
1. add a `--fix` flag to `lint-versions.js`
Seems to work, but I'm not sure how to handle the `newVersions` object that's returned from `compareVersions`, so this script might not be 100% correct
Closes #2245
> chore: lint versions --fix

- package.json
I also moved from `--require ts-node/register` to `--loader ts-node/esm` which will make the ESM upgrade easier.
> Move mocha options to config in package.json

- .changeset/great-fans-turn.md
- package.json
- packages/dev-server-storybook/package.json
- packages/rollup-plugin-workbox/package.json
- yarn.lock
[`rollup-plugin-terser`](https://www.npmjs.com/package/rollup-plugin-terser) has been deprecated.
> Replace `rollup-plugin-terser` with `@rollup/plugin-terser`

- .changeset/breezy-crabs-watch.md
- package.json
- packages/dev-server-storybook/package.json
- packages/rollup-plugin-workbox/package.json
- packages/test-runner-coverage-v8/src/index.ts
@web/test-runner-coverage-v8 0.6.0 introduces a performance improvement when calculating code coverage by caching coverage converters between browser sessions. (coverage converters are creating by loading the original file from disk)
Unfortunately, converters will alter their own state when applying the coverage from a specific session. This means that next sessions will be "poisoned" by previous ones.
This PR will ensure converters are reset (to their initial state of zero coverage) before applying a new one.
Ideally we would use a clone of the converter before using. But as there is no stable, ootb, way to create a clone (without also knowing the internals of the object), this workaround will just reset the internally used variables.
/cc: @43081j @koddsson
> fix: reset coverage result converters between Chrome session runs

- .changeset/quick-files-visit.md
- packages/test-runner-coverage-v8/src/index.ts
fixes #2258 
long story short, the object we pass into v8-to-istanbul is basically `{sources, sourceMap, originalSource?}`
if we set `originalSource`, we can avoid v8-to-istanbul loading the source file itself each time we call it
we're just moving the problem there though, so i repurposed the cache to cache these loaded files in memory with a limit of 50mb
> fix: cache sourcemap objects rather than converter instances

- .changeset/tasty-candles-juggle.md
- packages/test-runner-chrome/src/ChromeLauncherPage.ts
Fixes #2223 
puppeteer comes with an option to retrieve raw v8 coverage entries now, so we no longer need to do cdp calls ourselves
> feat (test-runner-chrome): use built in puppeteer coverage

- .changeset/tasty-timers-think.md
- packages/rollup-plugin-workbox/src/index.ts
Because the input of esbuild should always be the output of workbox, and the output of esbuild should be as configured via workbox
> fix: esbuild options shouldnt override swsrc and swdest

- .changeset/silent-hats-invite.md
- packages/test-runner-coverage-v8/src/index.ts
> fix(@web/test-runner-coverage-v8): ensure the size of source files is calculcated correctly when caching them

- .changeset/itchy-socks-rule.md
- packages/test-runner-chrome/src/ChromeLauncherPage.ts
- packages/test-runner-chrome/test/chromeLauncher.test.ts
- packages/test-runner-puppeteer/test/puppeteerLauncher.test.ts
This PR will add a workaround for an issue in the new headless mode of Puppeteer https://github.com/puppeteer/puppeteer/issues/10350.
The PR implements the proposal in the issue by patching the functions that are timing out (`window.requestIdleCallback` and `window.requestAnimationFrame`)
I'm not to sure yet what the best approach is to add tests for this.
> fix: add workaround for headless issue

- .changeset/orange-ducks-change.md
- package-lock.json
- packages/test-runner-chrome/package.json
- packages/test-runner-chrome/src/ChromeLauncherPage.ts
This is a potential fix for the timeout issues when running test code in parallel that is requiring to be run in an active tab.
> fix(test-runner-chrome): add mutex when bringing tabs to front

- .changeset/fluffy-snails-share.md
- docs/docs/dev-server/node-api.md
- package-lock.json
- packages/dev-server-core/package.json
- packages/dev-server-core/src/plugins/Plugin.ts
- packages/dev-server-core/src/server/DevServer.ts
- packages/dev-server-core/src/server/DevServerCoreConfig.ts
- packages/dev-server-core/src/server/createServer.ts
- packages/dev-server-core/test/server/DevServer.test.ts
- packages/dev-server-core/test/web-sockets/WebSocketsManager.test.ts
- packages/dev-server-hmr/test/HmrPlugin.test.ts
- packages/dev-server-hmr/test/browser.test.ts
1. add `middlewareMode` option to dev server config, make `hostname` and `port` optional in types
2. implement middleware mode to prevent starting an actual HTTP/S server
3. make `server` optional on `DevServer` which also has an impact on Plugin API
4. add test and docs
Theoretically it's a breaking change for Plugin API since now `serverStart` hook might not have a param `server`.
It won't impact the codebase immediately since you need to first activate `middlewareMode` to actually break stuff if any plugin depends on `server` existence, but type wise it might break compilation of such plugins right away.
As agreed with @thepassle we decided to take an easy path and not create a SemVer mess with a minor update as the impact of this is too small.
> feat(dev-server-core): support middleware mode

- .github/workflows/canary.yml
- .github/workflows/release.yml
- .github/workflows/verify-browserstack.yml
- .github/workflows/verify-node.yml
- .github/workflows/verify-saucelabs.yml
- .github/workflows/verify-windows.yml
- package-lock.json
- package.json
- packages/browser-logs/test/serialize-deserialize.test.ts
- packages/rollup-plugin-polyfills-loader/src/rollupPluginPolyfillsLoader.ts
- packages/rollup-plugin-polyfills-loader/test/snapshots/flattened.html
- packages/rollup-plugin-polyfills-loader/test/snapshots/multiple-entrypoints-retain-attributes.html
- packages/rollup-plugin-polyfills-loader/test/snapshots/multiple-entrypoints.html
- packages/rollup-plugin-polyfills-loader/test/snapshots/no-polyfills-retain-attributes.html
- packages/rollup-plugin-polyfills-loader/test/snapshots/no-polyfills.html
- packages/rollup-plugin-polyfills-loader/test/snapshots/non-flattened.html
- packages/rollup-plugin-polyfills-loader/test/snapshots/systemjs.html
- packages/test-runner-commands/test/emulate-media/browser-test.js
> chore: reenable all tests and update snapshots

- .changeset/cyan-days-buy.md
- packages/test-runner-visual-regression/package.json
This package has types but it does not provide them, this commit adds the missing types to the exports in the package.json.
> Added types to exports in package.json

- .changeset/fuzzy-hornets-marry.md
- packages/dev-server-storybook/package.json
- packages/dev-server-storybook/tsconfig.json
1. Added `"type": "module"` to the package.json of `dev-server-storybook`.
2. Changed `"module"` to `"nodenext"` in the `tsconfig.json`.
3. Made sure to add the `types` field in the exports field.
> Convert `@wev/dev-server-storybook` to ES Module

- .changeset/stale-cooks-cover.md
- packages/dev-server-storybook/src/build/build.ts
- packages/dev-server-storybook/src/build/cli.ts
- packages/dev-server-storybook/src/build/rollup/createRollupConfig.ts
- packages/dev-server-storybook/src/build/rollup/injectExportsOrderPlugin.ts
- packages/dev-server-storybook/src/build/rollup/mdxPlugin.ts
- packages/dev-server-storybook/src/index.ts
- packages/dev-server-storybook/src/serve/storybookPlugin.ts
- packages/dev-server-storybook/src/shared/config/readStorybookConfig.ts
- packages/dev-server-storybook/src/shared/config/validatePluginConfig.ts
- packages/dev-server-storybook/src/shared/html/createManagerHtml.ts
- packages/dev-server-storybook/src/shared/html/createPreviewHtml.ts
- packages/dev-server-storybook/src/shared/mdx/transformMdxToCsf.ts
- packages/dev-server-storybook/src/shared/stories/findStories.ts
- packages/dev-server-storybook/tsconfig.json
Set `moduleResolution` to `node16` so that TypeScript will output ES Modules and changed the `module` property so that it's not a moving target.
Fixes #2405
> Fix output format of `@web/dev-server-storybook`

- .changeset/small-rivers-carry.md
- package-lock.json
- packages/test-runner-core/package.json
1. make-dir 3.x.x was vulnerable (transitive dep), patched in istanbul-lib-report 3.0.1.
> fix: security vulnerability make-dir

- .changeset/large-hairs-count.md
- packages/test-runner-chrome/src/ChromeLauncher.ts
1. Fix debug mode by passing `headless: false`
This most likely was broken by upgrading to puppeteer 20.
My OS:
Ubuntu 22
To reproduce:
1. Run a test using the ChromeLauncher
2. Press `D` in the terminal
Actual:
No browser window opened
Expected:
Browser window to open
> fix(test-runner-chrome): fix debug mode

- .changeset/thirty-planes-arrive.md
- package-lock.json
- packages/rollup-plugin-import-meta-assets/src/rollup-plugin-import-meta-assets.js
- packages/rollup-plugin-import-meta-assets/test/fixtures/backticks.js
- packages/rollup-plugin-import-meta-assets/test/integration.test.js
- packages/rollup-plugin-import-meta-assets/test/snapshots/backticks.js
1. allow simple backticks strings (Template Literals with 1 quasi and 0 expressions), since those are statically analyzable.
> fix(rollup-plugin-import-meta-assets): allow simple backticks strings

- .changeset/strong-fans-invent.md
- packages/test-runner-core/src/server/plugins/api/createSourceMapFunction.ts
1. Cleanup the caching code for readability
2. Destroy the consumer to prevent a leak that causes errors to not be displayed correctly
When running tests against a folder containing source maps, the source maps will point to the place where the actual error was thrown. When the source map is really big and the tests are run a lot of times (this problem persists during watch mode reruns) there is overflow happening somewhere. I have created an small reproduction repo here: https://github.com/remcovaes/source-map-bug-web-test-runner
Also, the consumer caching was broken, because it the cache was only filled after a promise was resolved, which means that multiple promises where started and all those promises had cache misses. I think removing the consumer cache will not result a performance …
> fix(test-runner-core): destroy consumer after usage to prevent a leak

- .changeset/beige-spiders-eat.md
- packages/rollup-plugin-import-meta-assets/src/rollup-plugin-import-meta-assets.js
- packages/rollup-plugin-import-meta-assets/test/fixtures/directories-and-simple-entrypoint.js
- packages/rollup-plugin-import-meta-assets/test/fixtures/five
- packages/rollup-plugin-import-meta-assets/test/fixtures/simple-entrypoint.js
- packages/rollup-plugin-import-meta-assets/test/integration.test.js
- packages/rollup-plugin-import-meta-assets/test/snapshots/directories-ignored.js
- packages/rollup-plugin-import-meta-assets/test/snapshots/five
- packages/rollup-plugin-import-meta-assets/test/snapshots/simple-bundle.js
Makes rollup-plugin-import-meta-assets ignore references to directories such as e.g. `new URL('./', import.meta.url)`
> fix(rollup-plugin-import-meta-assets): fix #2421

- package.json
I ran into the following issue in our CI (e.g. in https://github.com/modernweb-dev/web/actions/runs/6073283198/job/16474903432?pr=2437)
```
Run npm run build
> build
> rimraf --glob packages/*/tsconfig.tsbuildinfo && tsc --build
Error: packages/storybook-framework-web-components/src/types.ts(2,[1](https://github.com/modernweb-dev/web/actions/runs/6073283198/job/16474903432?pr=2437#step:6:1)5): error TS2305: Module '"@web/storybook-builder"' has no exported member 'BuilderOptions'.
Error: packages/storybook-framework-web-components/src/types.ts(2,31): error TS2305: Module '"@web/storybook-builder"' has no exported member 'StorybookConfigWds'.
Error: Process completed with exit code 2.
```
which I couldn't reproduce locally until I made a clean repository clone.
The reason is that we don't …
> chore: make local build closer to CI

- .github/workflows/canary.yml
- .github/workflows/release.yml
- .github/workflows/verify-node.yml
- .github/workflows/verify-windows.yml
- package.json
I made a wrong assumption about how `npm run build:production` works.
It only builds certain packages, not all, so we shouldn't clean `dist` before it.
So I reverted that part of the previous PR #2441 and clarified what this command is for in the step names.
> fix: production builds

- packages/dev-server-hmr/test/browser.test.ts
I noticed that these tests are running really slow and wanted to see if I could make them faster. A few removals of some waiting calls and they are running faster (on my machine).
```
✔ should bubble when bubbles is true (2063ms)
✔ should hot replace a module (2074ms)
✔ should hot replace a bubbled module (3073ms)
✔ hot replaces multiple bubbled modules (3109ms)
✔ reloads the page when a module has no hot replacable parent (4091ms)
5 passing (15s)
```
```
✔ should bubble when bubbles is true (2058ms)
✔ should hot replace a module (81ms)
✔ should hot replace a bubbled module (73ms)
✔ hot replaces multiple bubbled modules (68ms)
✔ reloads the page when a module has no hot replacable parent (90ms)
5 passing (3s)
```
> Speed up browser tests

- packages/dev-server-core/src/test-helpers.ts
- packages/dev-server-core/test/server/DevServer.test.ts
I didn't see any other test and I figured a simple smoke-test would be good.
> Add a test for the `http2` server functionality

- .changeset/blue-ducks-care.md
- packages/mocks/registerMockRoutes.js
- packages/mocks/storybook/decorator.js
1. Append `*` for endpoints that start with a `/` so it also matches api calls made with an `api.` prefix
2. Add a check to see if Mocks are an array before trying to iterate over them
> fix: api prefix

- .changeset/pink-socks-look.md
- CONTRIBUTING.md
- package-lock.json
- packages/test-runner-commands/browser/commands.d.ts
- packages/test-runner-commands/plugins.mjs
- packages/test-runner-commands/src/index.ts
- packages/test-runner/src/config/parseConfig.ts
- Resurrected [this old closed PR](https://github.com/modernweb-dev/web/pull/2047) to correctly add the `selectOption` command exports and plugin. This work never got merged, but is still needed iirc.
- Updated the CONTRIBUTING.md to correct the `npm run install` to `npm install` because there's no `install` npm script.
> chore: add selectOption plugin correctly

- .changeset/tidy-spoons-work.md
- packages/dev-server/demo/export-conditions/config.mjs
- packages/dev-server/demo/export-conditions/index.html
- packages/dev-server/src/plugins/nodeResolvePlugin.ts
- packages/dev-server/test/integration.test.mjs
- packages/test-runner-commands/browser/commands.d.ts
fixes #2413 
1. removed exportConditions config from the deepmerge
2. handle exportConditions separately and allow the user config of exportConditions to fully replace the default array if present.
3. Add an export-conditions test case
> feat(dev-server): don't deepmerge exportConditions. allow user config to fully replace the default

- .changeset/smart-mice-relax.md
- packages/dev-server-core/src/server/createServer.ts
I am experiencing network errors. It is due to the large number of files my page is loading (300 to 400 hundred).
The number of files shouldn't be a problem, especially in a project that advocate ESM, importmap, modulepreload, http2/3 multiplexing, etc...
Raise-up the maxSessionMemory of the http2 server from the default value (10) to 20
> Avoid network errors when a large number of files are served with http2 ERR_HTTP2_PROTOCOL_ERROR

- packages/browser-logs/test/serialize-deserialize.test.ts
These keep flaking on CI on Windows which makes them kind of useless. A quick fix for us is to just increase the timeout.
> Increase timeout for serialise/deserialise tests

- integration/test-runner/tests/basic/browser-tests/timers.test.js
- integration/test-runner/tests/basic/runBasicTest.ts
- packages/test-runner-chrome/src/ChromeLauncherPage.ts
Since we patched these timer methods, we forgot to return the actual timer result (e.g. `requestIdleCallback` returns a number).
This breaks all sorts of code right now which depends on a number being returned (e.g. for debouncers and what not).
cc @koddsson @Westbrook
> fix (test-runner-chrome): return inner timer result

- .changeset/green-arachnid-crossing.md
- .changeset/orange-octopus-murmurs.md
- packages/dev-server-core/src/server/DevServer.ts
- packages/dev-server-core/src/server/DevServerCoreConfig.ts
- packages/dev-server/src/startDevServer.ts
- packages/storybook-builder/src/index.ts
1. Accept an external server when running in middleware mode.
2. Pass the server from Storybook Builder as an external server.
3. Use the external server, when available, to hang the web socket needed to watch changes.
Fixes #2471
> Allow web socket based refresh in middleware mode

- .changeset/spicy-kangaroos-search.md
- packages/test-runner-core/src/config/TestRunnerCoreConfig.ts
- packages/test-runner-core/src/server/plugins/api/parseBrowserLogs.ts
- packages/test-runner-core/test/src/runner/TestRunner.test.ts
1. added the TestSession as an arg to filterBrowserLogs so that I can only print logs for failed sessions, see #2450 
2. updated paths in one of the test-runner-core tests to be package relative so that the test would pass for me (not sure if something about my env makes these fail, but those paths should be package-relative anyway IMO... commands run within a workspace context have CWD set to that package's root, not the multi-package root)
> Add TestSession to filterBrowserLogs args to enable filtering by session result

- docs/docs/test-runner/writing-tests/code-coverage.md
adds documentation to show how cobertura can be added to the coverageConfig for enhanced reporting
Closes #1548
> docs: adds code coverage reporter config example

- .changeset/twenty-pants-draw.md
- package-lock.json
- packages/test-runner-mocha/package.json
Having an `@types/*` package with global symbols like `it` and `describe` forces these global types on downstream consumers which may not use them. TypeScript is fairly aggressive at pulling in globals from transitive dependencies, meaning that `@types/mocha` is applied to application code, which can cause challenges. For example, Jasmine types overlap and conflict with Mocha types, but transitively including `@types/mocha` through `@web/test-runner-mocha` makes Jasmine impossible to use with Web Test Runner. See [this commit](https://github.com/angular/angular-cli/pull/25860/commits/d95bb6325951a19e69a3da9790b0fa0873ee0600) for a motivating example.
One potential alternative solution I did not explore here but want to state for posterity: I think it is debatable whether …
> fix(test-runner-mocha): move `@types/mocha` to dev dependency

- .changeset/giant-countries-beam.md
- package-lock.json
- packages/dev-server-esbuild/package.json
- packages/dev-server-hmr/package.json
- packages/dev-server/package.json
- packages/mocks/package.json
1. Split all versions of lit dependencies for consumption of ^2 || ^3.
> Use split versions for all lit dependencies

- package-lock.json
- package.json
- packages/dev-server-core/package.json
- packages/dev-server-core/src/test-helpers.ts
- packages/dev-server-core/test/middleware/basePathMiddleware.test.ts
- packages/dev-server-core/test/middleware/etagCacheMiddleware.test.ts
- packages/dev-server-core/test/middleware/historyApiFallbackMiddleware.test.ts
- packages/dev-server-core/test/middleware/pluginFileParsedMiddleware.test.ts
- packages/dev-server-core/test/middleware/pluginMimeTypeMiddleware.test.ts
- packages/dev-server-core/test/middleware/pluginServeMiddleware.test.ts
- packages/dev-server-core/test/middleware/pluginTransformMiddleware.test.ts
- packages/dev-server-core/test/middleware/serveFilesMiddleware.test.ts
- packages/dev-server-core/test/plugins/mimeTypesPlugin.test.ts
- packages/dev-server-core/test/plugins/transformModuleImportsPlugin.test.ts
- packages/dev-server-core/test/server/DevServer.test.ts
- packages/dev-server-core/test/web-sockets/webSocketsPlugin.test.ts
- packages/dev-server-esbuild/package.json
- packages/dev-server-esbuild/test/banner-footer.test.ts
- packages/dev-server-esbuild/test/json.test.ts
- packages/dev-server-esbuild/test/jsx.test.ts
- packages/dev-server-esbuild/test/target.test.ts
- packages/dev-server-esbuild/test/ts.test.ts
- packages/dev-server-esbuild/test/tsx.test.ts
- packages/dev-server-hmr/test/HmrPlugin.test.ts
- packages/dev-server-rollup/package.json
- packages/dev-server-rollup/test/node/plugins/node-resolve.test.ts
We don't need `node-fetch` any more as the platform (nodejs) has caught up with standards and has `fetch` as a built-in global variable since node v18.
> Remove node-fetch since fetch is already implemented in node

- packages/dev-server-core/src/server/DevServer.ts
- packages/dev-server-core/src/server/DevServerCoreConfig.ts
- packages/dev-server/src/config/parseConfig.ts
1. Added option to provide chokidar Watchoptions to the web dev server watcher. This is due to numerous errors with especially windows environments not being able to utilize the dev server due to watch/file update errors.
Examples of said error happening
- https://github.com/facebook/create-react-app/issues/10253
- https://github.com/paulmillr/chokidar/issues/1297
- https://github.com/modernweb-dev/web/issues/2221
With this, we are able to provide a non-changed environment for all users, but provide extra configurability to the file watchers ( and therefore to caching, watchers, etc.) through the chokidarOptions tag.
---
Is there any other parts of the codebase this should touch? I'm not too familiar with changesets etc so please advice
> feat: Add option to modify chokidar watchOptions with @web/dev-server

- .changeset/friendly-seahorses-serve.md
- packages/mocks/browser.js
1. Works around the breaking change caused by `msw@2.1.0` https://github.com/mswjs/msw/issues/1981
> fix: mocks timing issue

- .changeset/grumpy-foxes-laugh.md
- package-lock.json
- packages/dev-server/package.json
- packages/test-runner-browserstack/package.json
- packages/test-runner-core/package.json
- packages/test-runner-saucelabs/package.json
Update `ip` dependency to latest version containing the fix.
> N.B. I added this as a patch release, since ip is [only used internally (for the address method)](https://github.com/search?q=repo%3Amodernweb-dev%2Fweb%20%27ip%27%3B&type=code). Also, it needs to reach as many consumers as possible, since it's quite a critical vulnerability: https://github.com/advisories/GHSA-78xj-cgh5-2h22
> fix: remove vulnerability by updating `ip` package

- .changeset/sweet-sloths-crash.md
- packages/storybook-builder/src/generate-iframe-html.ts
- packages/storybook-builder/src/index.ts
- packages/storybook-builder/src/rollup-plugin-prebundle-modules.ts
- packages/storybook-builder/static/iframe-template.html
1. improved security by not allowing to bundle all env vars, especially unnecessarily
2. move env.NODE_ENV to globals defined in the preview index.html, so that rare packages that require it can use it dynamically and rollup can optimise it later as a whole when bundling for production
3. removed prebundling of `tiny-invariant` as it's not needed anymore which was one of the goals of above changes
> fix(storybook-builder): define only necessary process.env globally

- packages/storybook-builder/src/rollup-plugin-prebundle-modules.ts
1. small refactor to simplify maintenance of the prebundle candidates
> chore(storybook-builder): group prebundle candidates by purpose

- .changeset/four-scissors-greet.md
- packages/storybook-builder/src/esbuild-plugin-commonjs-named-exports.ts
- packages/storybook-builder/src/rollup-plugin-prebundle-modules.ts
1. (storybook-builder): fix tocbot default import by @storybook/blocks
At least before 7.4.0 the Storybook used `default` import from `tocbot`.
I noticed that when testing in #2485
At some point it was changed to named `init` and `destroy`, therefore I didn't noticed this in my manual test earlier with later versions.
For backwards compatibility it's best to fix this.
> fix(storybook-builder): fix tocbot default import by @storybook/blocks

- .changeset/nervous-bugs-rhyme.md
- docs/docs/building/rollup-plugin-html.md
- package-lock.json
- packages/rollup-plugin-html/package.json
- packages/rollup-plugin-html/src/RollupPluginHTMLOptions.ts
- packages/rollup-plugin-html/src/assets/utils.ts
- packages/rollup-plugin-html/src/input/extract/extractAssets.ts
- packages/rollup-plugin-html/src/input/extract/extractModulesAndAssets.ts
- packages/rollup-plugin-html/src/input/getInputData.ts
- packages/rollup-plugin-html/src/output/emitAssets.ts
- packages/rollup-plugin-html/src/output/getOutputHTML.ts
- packages/rollup-plugin-html/src/output/injectedUpdatedAssetPaths.ts
- packages/rollup-plugin-html/test/fixtures/assets/image-d.png
- packages/rollup-plugin-html/test/fixtures/assets/image-d.svg
- packages/rollup-plugin-html/test/fixtures/assets/styles-with-referenced-assets.css
- packages/rollup-plugin-html/test/rollup-plugin-html.test.ts
Fixes #811
1. Added a plugin option for providing glob patterns in order to exclude assets from being extracted.
Very useful for stuff that already lives in a `public` folder and are copied as-is.
`extractAssets` is all or nothing.
`transformAssets` doesn't provide a way to skip an asset.
Also related: #2631
> feat(rollup-plugin-html): glob patterns exclusion for external assets

- README.md
- docs/_data/footer.json
- docs/discover/discord.md
- docs/discover/slack.md
1. Added a Discord page to replace the Slack page, since the channel is no longer active
2. Updated the Slack page to point to a new Discord page
3. Removed a link to the old Lit & Friends group since that's also no longer active
There isn't much content on the Discord page, so feel free to add whatever else you'd like to put there.
> Update Slack page and add link to Discord

- .changeset/warm-poems-watch.md
- package-lock.json
- packages/storybook-builder/package.json
- packages/storybook-builder/src/esbuild-plugin-commonjs-named-exports.ts
- packages/storybook-builder/src/rollup-plugin-prebundle-modules.ts
1. simplify and speed up the CommonJS to ESM transformation
2. make React conditional reexports work in production
3. remove `@chialab/esbuild-plugin-commonjs` and use low-level `cjs-module-lexer`
2nd caused a bug when I started working on MDX and created a static build of the storybook, which made React break with missing reexports like `import { createContext } from 'react';`
this was due to a lack of support in `@chialab/esbuild-plugin-commonjs` for conditional CommonJS reexports, specifically in this file https://www.runpkg.com/?react@18.2.0/index.js
```js
// react@18.2.0/index.js
'use strict';
if (process.env.NODE_ENV === 'production') {
module.exports = require('./cjs/react.production.min.js');
} else {
module.exports = require('./cjs/react.development.js');
}
```
after hours of …
> fix(storybook-builder): simplify and speed up the CommonJS to ESM transformation

- docs/docs/test-runner/writing-tests/helper-libraries.md
...instead of the deprecated one.
1. I followed the link, saw that the NPM.js page touted the chai plugin in the successor library
2. Changed the wording, the link
> helper-libraries.md: mention semantic-dom-diff instead

- package-lock.json
- packages/storybook-framework-web-components/tests/fixtures/all-in-one/.storybook/main.js
1. updated deps (because e.g. `tocbot` issue was only visible with the latest version)
2. write the storybook config which I use in the tests in such a way that warnings cause an error, but add some exceptions
3. add `tocbot` as an exception for now while I'm trying to fix it in a better way (see https://github.com/tscanlin/tocbot/issues/337) - this is not critical for us at the moment, but will be critical later when more people start to use `autodocs` and MDX and enable `toc` in the their storybooks
> Improve storybook builder static build tests

- .changeset/tricky-schools-unite.md
- packages/storybook-builder/src/rollup-plugin-prebundle-modules.ts
1. clean up .prebundled_modules before creating new bundles
Using it as a cache is currently not supported and requires programming the logic to do checks of the original files, or relying on esbuild internal caching mechanism (if any), which is yet to be investigated and implemented.
For now this folder accumulates old bundled files and creates a lot of confusion when debugging it, that results in really poor DX when working on the library, so I decided to remove it between runs before the cache is implemented.
> fix(storybook-builder): clean up .prebundled_modules before creating new bundles

- .changeset/clean-olives-fly.md
- package-lock.json
- packages/storybook-builder/src/rollup-plugin-mdx.ts
1. Fixed issue when an MDX file is compiled with a wrong module path (`"./../../../node_modules/@storybook/addon-docs/dist/shims/mdx-react-shim"`) without an extension, which is coming from `@storybook/addon-essentials` https://github.com/storybookjs/storybook/blob/v7.6.17/code/addons/essentials/src/docs/preset.ts#L10
```js
/*@jsxRuntime automatic @jsxImportSource react*/
import {Fragment as _Fragment, jsxDEV as _jsxDEV} from "./../../../node_modules/.prebundled_modules/react/jsx-dev-runtime.mjs";
import {
useMDXComponents as _provideComponents
} from "./../../../node_modules/@storybook/addon-docs/dist/shims/mdx-react-shim"; // this is a bug
function _createMdxContent(props) {
const _components = Object.assign({
h1: "h1",
p: "p",
code: "code",
pre: "pre"
}, _provideComponents(), …
```
> fix(storybook-builder): fix providerImportSource extension when using @storybook/addon-essentials

- .changeset/pretty-walls-develop.md
- packages/mocks/README.md
- packages/mocks/package.json
- packages/mocks/storybook-addon/manager.js
- packages/mocks/storybook-addon/preset.js
- packages/mocks/storybook-addon/preview.js
For Storybook 7+ (`@web/storybook-builder`):
1. make a single entry point `@web/mocks/storybook-addon` with automatic setup
2. explain how to setup interceptor without using the argument `interceptor` in `mockRollupPlugin({ interceptor })`
3. clarify in docs in which files changes are not necessary
because people now just copy the code, even if it says it's for Storybook 6
This is pretty hard to support 2 docs for very different setup side-by-side, I hope to deprecate the Storybook 6 one soon and release @web/mocks v2 without it.
> feat(mocks): improve addon setup for storybook-builder

- packages/rollup-plugin-html/test/rollup-plugin-html.test.ts
> fix: windows tests

- docs/docs/building/polyfills-loader.md
- docs/docs/building/rollup-plugin-html.md
- docs/docs/building/rollup-plugin-import-meta-assets.md
- docs/docs/dev-server/cli-and-configuration.md
- docs/docs/dev-server/plugins/esbuild.md
- docs/docs/test-runner/browser-launchers/browserstack.md
- docs/docs/test-runner/browser-launchers/saucelabs.md
- docs/docs/test-runner/commands.md
- docs/docs/test-runner/writing-tests/code-coverage.md
- docs/docs/test-runner/writing-tests/html-tests.md
- docs/guides/dev-server/using-plugins.md
- docs/guides/going-buildless/es-modules.md
- docs/guides/test-runner/code-coverage/index.md
- docs/guides/test-runner/typescript.md
1. Fixed grammar and typos in docs.
2. Addressed some Markdown issues (`test-runner/typescript.md`) where it looked like content was meant to be its own paragraph.
> docs: fix grammar and spelling errors in documentation.

- .changeset/witty-ways-occur.md
- packages/dev-server-rollup/src/rollupAdapter.ts
- packages/dev-server-rollup/test/node/fixtures/monorepo-import-inside-from-outside/node_modules/storybook/index.js
- packages/dev-server-rollup/test/node/fixtures/monorepo-import-inside-from-outside/node_modules/storybook/package.json
- packages/dev-server-rollup/test/node/fixtures/monorepo-import-inside-from-outside/src/packages/subpackage/app.js
- packages/dev-server-rollup/test/node/fixtures/monorepo-import-inside-from-outside/src/packages/subpackage/node_modules/.prebundled_modules/react.mjs
- packages/dev-server-rollup/test/node/unit.test.ts
- for rollup adapter I deduped imports from outside root dir, so they are loaded from same URL as when requested by modules inside root dir
> check unit test for even more descriptive example
Same file was imported by a module inside `rootDir` and a module outside `rootDir` in such a way that from the browser perspective it's 2 different files.
I ran into this when playing with MDX in the `storybook-builder`, where some deps located in root monorepo node_modules were importing React in a different way to the way I was importing in my subpackage (where subpackage was a root dir).
As a result, prebundled React was loaded twice from 2 different URLs:
For `rootDir=packages/storybook-builder/` browser requests looked like:
- for a module `inside `: …
> fix(dev-server-rollup): dedupe imports from outside root

- .changeset/modern-planes-yawn.md
- packages/test-runner/src/reporter/summaryReporter.ts
Presently, when a test is skipped, the visual representation uses a red "X" symbol, while the written summary denotes the skip with a gray label. 
To enhance understanding and cognitive accessibility, I suggest introducing a new visual symbol, “-,” rendered in a subdued color, to complement the existing skipped label. This alignment of visual and written representations aims to improve clarity and consistency.
- https://www.w3.org/WAI/WCAG2/supplemental/patterns/o4p10-status-feedback/
> fix(test-runner): unify visual-written representation of skipped tests

- .changeset/cool-terms-exercise.md
- integration/test-runner/tests/test-failure/browser-tests/fail-readonly-actual.test.js
- integration/test-runner/tests/test-failure/runTestFailureTest.ts
- packages/dev-server-core/src/web-sockets/webSocketsPlugin.ts
Fixes #2728 
1. Add integration test for error reporting with readonly / frozen objects
2. Create a structuredClone of messages when running stringification with (mutating) circurlar reference removal
> fix(dev-server-core): fix readonly error serialization

- .changeset/hot-dodos-push.md
- packages/storybook-framework-web-components/src/preset.ts
1. set `watch: true` to enable auto-reload by default
We implemented the baseline for auto-reload here https://github.com/modernweb-dev/web/pull/2482
But I overlooked the fact that `watch: true` wasn't set by default.
It should be, because it's expected of the Storybook to have this behavior by default, e.g. `@storybook/web-components-vite` has it.
If we make a stable HMR implementation and test it extensively, we can in the future enable that instead by default (these is what frameworks presets are for, also the one I patch here). For now it's just a simple page reload.
> fix(storybook-framework-web-components): watch code changes and auto-reload by default

- .changeset/plenty-llamas-cross.md
- package-lock.json
- packages/mocks/storybook/addon/register-addon.js
1. Use hsla values for background and border color so it works for both - light and dark mode:
2. Slightly improve styles when loading / no mocks:
> feat(mocks): update mocks addon styles to support dark mode

- .changeset/lemon-suns-sneeze.md
- package-lock.json
- packages/dev-server/package.json
- packages/dev-server/src/logger/logStartMessage.ts
- packages/test-runner-browserstack/package.json
- packages/test-runner-browserstack/src/browserstackLauncher.ts
- packages/test-runner-core/package.json
- packages/test-runner-core/src/cli/getManualDebugMenu.ts
- packages/test-runner-saucelabs/package.json
- packages/test-runner-saucelabs/src/SauceLabsLauncher.ts
- packages/test-runner-saucelabs/src/SauceLabsLauncherManager.ts
Fixes #2747 
`ip` package is now archived on GitHub https://github.com/indutny/node-ip/
PRs with a fix won't be released
> fix: replace ip dependency due to security bug CVE-2024-29415

- .changeset/angry-hairs-bathe.md
- package-lock.json
- packages/dev-server-rollup/package.json
1. Update the version of the whatwg-url to ^14.0.0 which will resolve [this issue](https://github.com/modernweb-dev/web/issues/2755) with the deprecation warning.
> chore(dev-server-rollup): Bump the version of whatwg-url.

- docs/docs/test-runner/cli-and-configuration.md
Probably dont want people running in browser quirks mode (like we have in Shoelace 🙈 )
1. Changed documentation of testRunnerHTML to include a `<!DOCTYPE html>` so that users dont run their test suite in quirks mode.
> Update cli-and-configuration.md to not be in quirks mode

- .changeset/heavy-pianos-beam.md
- packages/test-runner/src/reporter/summaryReporter.ts
1. make the summary reporter list the suite names when flatten is true
Before:
```
✓ imperatively instantiates [Chromium]
✓ should upgrade [Chromium]
✓ should be hidden on init [Chromium]
✓ should not be accessible [Chromium]
✓ should be visible [Chromium]
✓ should be accessible [Chromium]
✓ should focus the component [Chromium]
✓ should be visible [Chromium]
✓ should be accessible [Chromium]
✓ should focus the component [Chromium]
✓ should be hidden [Chromium]
✓ should be visible [Chromium]
✓ should be hidden on init [Chromium]
✓ should be visible [Chromium]
✓ should have a label of "Back to top" [Chromium]
✓ should have a label of "Back to top" [Chromium]
✓ should have a label of "Return to top" [Chromium]
✓ should have a label of "Return to top" [Chromium]
```
After:
```
✓ …
```
> fix(test-runner): show suites for summaryReporter({ flatten: true })

- docs/guides/going-buildless/serving.md
It became distracting at some point when examples changed from `my-domain.dev` to `my-domain.com` This page includes 10 examples, 7 of them are `my-domain.com` and 3 of them are `my-domain.dev`. I made them more consistent.
target page: https://modern-web.dev/guides/going-buildless/serving/
> docs: "Serving": more consistent examples

- .changeset/gentle-masks-film.md
- .changeset/six-lions-sin.md
- package-lock.json
- packages/storybook-framework-web-components/package.json
- packages/storybook-framework-web-components/tests/all-in-one.spec.js
- packages/storybook-framework-web-components/tests/fixtures/all-in-one/.storybook/main.js
- packages/storybook-framework-web-components/tests/fixtures/all-in-one/README.md
- packages/storybook-framework-web-components/tests/fixtures/all-in-one/stories/my-page.mdx
- packages/storybook-utils/README.md
- packages/storybook-utils/index.mjs
- packages/storybook-utils/src/index.js
- packages/storybook-utils/src/mdx-file-loader.js
1. add MDXFileLoader to load and render non-JS files in MDX
2. fix exports of the utils packages
> feat(storybook-utils): add MDXFileLoader to load and render non-JS files in MDX

- .eslintignore
Added `_side-dev` and `docs/_merged_assets` folders to `.eslintignore` to fix warnings I'm getting locally:
```
> lint:eslint
> eslint --ext .ts,.js,.mjs,.cjs .
/Users/serhii/cf/modernweb/_site-dev/guides/going-buildless/css/__mdjs-stories.js
43:2  error  Unnecessary semicolon  @typescript-eslint/no-extra-semi
```
```
> lint:prettier
> node node_modules/prettier/bin-prettier.js "**/*.{ts,js,mjs,cjs,md}" --check --ignore-path .eslintignore
Checking formatting...
[warn] docs/_merged_data/site.cjs
[warn] Code style issues found in the above file. Forgot to run Prettier?
```
> chore: add _site-dev and _merged_assets to .eslintignore

- .changeset/popular-sheep-rush.md
- packages/config-loader/package.json
Fixes https://github.com/modernweb-dev/web/issues/2793
Set `type` to `commonjs` to avoid test failure due to Node 22.7 experimental module syntax detection.
> chore: set type to commonjs in config-loader package.json

- .changeset/rude-scissors-provide.md
- docs/docs/test-runner/browser-launchers/puppeteer.md
- package-lock.json
- package.json
- packages/test-runner-chrome/package.json
- packages/test-runner-chrome/src/ChromeLauncher.ts
- packages/test-runner-chrome/src/ChromeLauncherPage.ts
- packages/test-runner-puppeteer/package.json
- packages/test-runner-visual-regression/src/visualRegressionPlugin.ts
Upgraded `puppeteer-core` and `puppeteer` to v23. This includes the following breaking changes:
- Renamed `product` to `browser`, see https://github.com/puppeteer/puppeteer/pull/12757
- Changed return type of `page.screenshot()`, see https://github.com/puppeteer/puppeteer/pull/12823
> feat: upgrade puppeteer and puppeteer-core to v23

- .changeset/giant-games-count.md
- package-lock.json
- packages/dev-server-core/package.json
- packages/dev-server-core/src/server/DevServerCoreConfig.ts
- packages/test-runner-core/package.json
1. Bumped chokidar to v4.0.1 which removes 11 dependencies and has better TypeScript support
local test pass, and it builds locally as well
> Bump chokidar v4

- .github/workflows/verify-node.yml
1. While Node 23 and 24 are being relesed, we start getting errors on them and we lost Node 22 testing which is probably most important at the moment, so I added it to the suite explicitely.
Node 18 is still required since it's in official maintenance until 2025-04-30
https://nodejs.org/en/about/previous-releases
https://github.com/nodejs/release#release-schedule
> fix: test on Node 22 explicitely

- .changeset/tasty-pugs-buy.md
- package-lock.json
- packages/dev-server-esbuild/package.json
- packages/rollup-plugin-workbox/package.json
- packages/storybook-builder/package.json
This just bumps esbuild to 0.20.x
it'll help de-dupe a lot of my dependency tree since many of our other dependencies are using esbuild 0.20.x 👀
> chore: upgrade esbuild to 0.24.x

- .github/workflows/canary.yml
- .github/workflows/lint.yml
- .github/workflows/release.yml
- .github/workflows/verify-browser.yml
- .github/workflows/verify-node.yml
- .github/workflows/verify-storybook-builder.yml
1. Pinned Ubuntu version since the `latest` now refers to the `ubuntu-24.04` and that has some problems. See https://github.com/vaadin/web-components/pull/8375 for more context.
> chore: pin Ubuntu version in GitHub Actions to 22.04

- package-lock.json
- package.json
I run into the compilation error (see blow) related to the native dependency
- [libvips-8.10.6-darwin-arm64v8.tar.br](https://github.com/lovell/sharp-libvips/releases/download/v8.10.6/libvips-8.10.6-darwin-arm64v8.tar.br)
- downloaded by the NPM package `sharp@0.29.3`
My setup:
- Apple M1 Pro
- macOS 15.2 
- tried Node versions 18, 20, 22
Next sharp version `sharp@0.30.7` solves it, looks backwards compatible, so I figured that for now "overrides" would be OK solution.
Proper solution is to update `@rocket/cli` which now uses the old version of `@11ty/eleventy-img` which results in a broken `sharp@0.29.3`, but I can't just update it, it requires refactoring the entire documentation setup, so not smth I have time for now.
Log of the error that I'm fixing:
```
npm error code 1
npm error …
```
> chore: fix sharp native dependency compilation of libvips 8.10.6

- .changeset/grumpy-meals-kick.md
- docs/docs/test-runner/browser-launchers/saucelabs.md
- package-lock.json
- packages/test-runner-commands/test/send-mouse/sendMousePlugin.test.ts
- packages/test-runner-saucelabs/package.json
- packages/test-runner-saucelabs/src/SauceLabsLauncher.ts
- packages/test-runner-saucelabs/src/createSauceLabsLauncher.ts
- packages/test-runner-webdriver/package.json
- packages/test-runner-webdriver/src/IFrameManager.ts
- packages/test-runner-webdriver/src/SessionManager.ts
- packages/test-runner-webdriver/src/utils.ts
- packages/test-runner-webdriver/src/webdriverLauncher.ts
- packages/test-runner-webdriver/test/webdriverLauncher.test.ts
1. Upgraded `webdriverio` to v9 and changed the saucelabs launcher accordingly
2. Removed logic and docs related to JWP capabilities as these have been dropped
Tested locally by running tests for `@web/test-runner-webdriver` package. These don't currently run in CI as they were skipped long ago, in particular due to https://github.com/webdriverio/selenium-standalone/issues/788 - that issue is now fixed but unfortunately the fix landed in a version that dropped Node 18 support.
> feat: upgrade WebdriverIO to v9, drop JWP capabilities

- .github/workflows/verify-node.yml
1. when Node 23 fails now, we still want to know if others work, but now if Node 23 fails earlier than others, everything stops and we don't know the result
> chore: continue tests on other Node versions if one fails

- .changeset/chatty-rings-tease.md
- packages/test-runner-saucelabs/src/createSauceLabsLauncher.ts
1. Fixed type for providing a `SauceLabsCapabilities` object to `createSauceLabsLauncher`
The parameter is specifically for providing SauceLabs capabilities and is destructured into `sauce:options` in the final capabilities object:
https://github.com/modernweb-dev/web/blob/12d0de49e05f38db32745448ec06f5033b07b431/packages/test-runner-saucelabs/src/createSauceLabsLauncher.ts#L48-L51
Thus the type should also reflect that the parameter should contain Sauce Labs capabilities and not all Web Driver capabilities. You can see this being an issue in `packages/test-runner-saucelabs/test-remote/saucelabsLauncher.test.ts` for example, which doesn't compile ATM.
> fix(test-runner-saucelabs): use correct SauceLabsCapabilities type

- .changeset/perfect-lies-rush.md
- package-lock.json
- packages/test-runner-saucelabs/package.json
- packages/test-runner-saucelabs/src/SauceLabsLauncherManager.ts
- packages/test-runner-saucelabs/src/createSauceLabsLauncher.ts
1. Bump `saucelabs` to `9.0.0` to make use of Sauce Connect 5
2. Adapt to breaking changes in newer version
For some background, `test-runner-saucelabs` currently uses `saucelabs@^7.2.0`, which downloads Sauce Connect version 4. That version has already reached [EOL](https://docs.saucelabs.com/secure-connections/sauce-connect/lifecycle/) and starting May 5, 2025 SauceLabs will [stop accepting traffic](https://docs.saucelabs.com/secure-connections/sauce-connect/) from that version. That means that at that point `test-runner-saucelabs` would stop working as well.
SauceLabs users need to upgrade to Sauce Connect 5 instead. To support that SauceLabs have now released `saucelabs@9.0.0`, which downloads and runs the newer version. That version contains **breaking changes** in terms of API and …
> feat(test-runner-saucelabs): add support for Sauce Connect 5

- .github/workflows/verify-storybook-builder.yml
1. Migrated from `upload-artifact@v3` to `upload-artifact@v4`, it contains breaking changes, so I updated accordingly
`upload-artifact@v3` was deprecated in November 2024 and completely stopped working in one of recent PRs failing the build, so I needed to do that to bring Storybook Builder tests back to a working state
3. Combined Linux & Windows builds of Storybook Builder into a matrix, just saw an example how to do that keeping the flow the same, so DRYed it
4. Bumped Node to 22 in Storybook Builder tests
> chore: migrate from deprecated upload-artifact

- .github/workflows/verify-storybook-builder.yml
1. prevent puppeteer download issues from blocking storybook-builder tests
puppeteer is not used in storybook-builder tests anyway, so no need to download it, and it's probably better for perf also
Issues look like this, I could only found that it's probably due to some server availability where puppeteer binaries are downloaded from, I saw these multiple times lately, often 2nd restart helped to resolve, so this proves the theory.
> fix: prevent puppeteer download issues from blocking storybook-builder tests

- .changeset/tasty-emus-sort.md
- packages/dev-server-polyfill/tsconfig.json
- packages/dev-server-polyfill/tsconfig.override.json
- packages/storybook-framework-web-components/tsconfig.json
- tsconfig.json
> fix: publish polyfill plugin as esm instead of commonjs

- .changeset/nice-guests-invent.md
- packages/config-loader/src/importOrRequireConfig.js
Currently when a config has an explicit extension, the config-loader still tries resolving/traversing for a `package.json` file. This can be slow, and also break in some environments with sandboxing; especially when used in combination with Bazel.
It doesn't seem investigating why the calls are stuck, if the logic should not run in general when an explicit extension is provided.
> refactor(config-loader): do not lookup `package.json` with explicit extensions

- package-lock.json
1. update puppeteer to latest in the lock file to resolve issues with downloading the browsers
2. needed to temporarily remove "webdriverio", then install "puppeteer", then readd "webdriverio", because otherwise the "puppeteer" was partially installed from the peerDependencies of "webdriverio" as 22.x.x and partially as 24.x.x, resulting in the root "puppeteer" and "puppeteer-core" being different and creating more unnecessary duplicates, NPM is weird in such cases
Releasing this is not needed, as all requirements remain the same. I also don't do this to bring any new features, this is really just to minimize issues like `Error: ERROR: Failed to set up chrome-headless-shell v133.0.6943.53! Set "PUPPETEER_SKIP_DOWNLOAD" env variable to skip download.`
> chore: update locked puppeteer and webdriverio

- .changeset/kind-schools-rule.md
- .changeset/shaggy-chefs-dance.md
- package-lock.json
- packages/test-runner-chrome/package.json
- packages/test-runner-chrome/src/ChromeLauncherPage.ts
- packages/test-runner/src/startTestRunner.ts
See individual commit descriptions.
> fix(test-runner-chrome): remove focus browser patches 

- .changeset/hungry-sheep-live.md
- package-lock.json
- packages/storybook-utils/package.json
1. allow React 19 storybook-utils, not only React 18, since Storybook allows it and we support both too
2. test everything with React 19
This will simplify the dependencies graph, because currently due to how dependencies are resolve, most `@storybook/*` packages will install React 19, so our `@web/storybook-utils` will unnecessarily required React 18 to be installed in nested node_modules, however this is not really needed and we can rely on the root React 19 too.
> fix(storybook-utils): allow React 19 and test with it

- .changeset/tiny-apes-protect.md
- packages/test-runner/src/reporter/summaryReporter.ts
1. Added back support for reporting a summary of errors in summaryReporter
2. Added option to turn off error reporting in summaryReporter
3. Added option to turn off log reporting in summaryReporter
I found that in #2126 the option to add log reporting was enabled but it also replaced the logger with the reportTestFileResults BufferedLogger. However this logger flushes its log buffer as soon as reportTestFileResults stage finishes and then this logger is used for Error reporting in onTestRunFinished() and this reporting now just goes to a buffer that is never flushed.  I resolved this issue by moving the error reporting logging back to TestRunnerLogger. This change could be a breaking change to some users who have worked around the lack of error reporting so I have added a flag so it can …
> fix(summaryReporter): add back broken error reporting and make log reporting optional for summaryReporter
