- .github/workflows/release.yml
fixes https://github.com/modernweb-dev/web/issues/18
> chore: format after changeset publish

- .changeset/four-beans-run.md
- packages/test-runner-dev-server/src/createDevServer.ts
Fixes https://github.com/modernweb-dev/web/issues/12
> feat(test-runner-dev-server): log 404s even when session never starts

- .changeset/quick-carrots-tap.md
- packages/test-runner-chrome/src/chromeLauncher.ts
- packages/test-runner-chrome/src/findExecutablePath.ts
Fixes https://github.com/modernweb-dev/web/issues/45
> fix(test-runner-chrome): speed up the lookup for chrome installation on mac

- .changeset/six-sheep-dress.md
- packages/test-runner-core/src/runner/TestRunner.ts
- packages/test-runner-core/src/runner/TestScheduler.ts
- packages/test-runner-core/src/runner/createTestSessions.ts
- packages/test-runner-core/src/test-session/TestSession.ts
Fixes https://github.com/modernweb-dev/web/issues/23
> feat(test-runner-core): support multiple browser launchers

- .changeset/twelve-deers-check.md
- README.md
- packages/test-runner-chrome/README.md
- packages/test-runner-chrome/package.json
- packages/test-runner-cli/README.md
- packages/test-runner-cli/package.json
- packages/test-runner-core/README.md
- packages/test-runner-core/package.json
- packages/test-runner-dev-server/README.md
- packages/test-runner-dev-server/package.json
- packages/test-runner-framework/README.md
- packages/test-runner-framework/package.json
- packages/test-runner-mocha/README.md
- packages/test-runner-mocha/package.json
- packages/test-runner-playwright/README.md
- packages/test-runner-playwright/package.json
- packages/test-runner-puppeteer/README.md
- packages/test-runner-puppeteer/package.json
- packages/test-runner/README.md
- packages/test-runner/package.json
Fixes https://github.com/modernweb-dev/web/issues/38
Fixes https://github.com/modernweb-dev/web/issues/16
> chore: add readme, package tags and description

- .changeset/smart-moose-look.md
- .gitignore
- packages/test-runner-cli/package.json
- packages/test-runner-cli/src/TestRunnerCli.ts
- packages/test-runner-cli/src/messages/getTestCoverage.ts
- packages/test-runner-cli/src/messages/getWatchCommands.ts
- packages/test-runner-cli/src/messages/writeCoverageReport.ts
- packages/test-runner-cli/src/startTestRunner.ts
- packages/test-runner-core/src/coverage/getTestCoverage.ts
- packages/test-runner-core/src/runner/TestRunnerConfig.ts
- packages/test-runner-dev-server/package.json
- yarn.lock
Fixes https://github.com/modernweb-dev/web/issues/24
> Coverage html

- .changeset/chatty-zebras-sort.md
- packages/test-runner-mocha/package.json
Fixes https://github.com/modernweb-dev/web/issues/67
> fix(test-runner-mocha): add assets to published files

- .changeset/strong-eels-suffer.md
- packages/test-runner-framework/src/index.ts
Fixes https://github.com/modernweb-dev/web/issues/69
> fix(test-runner-framework): handle non-object errors

- .changeset/cuddly-mangos-taste.md
- packages/test-runner-cli/src/TestRunnerCli.ts
Fixes https://github.com/modernweb-dev/web/issues/68
> feat(test-runner-cli): don't log coverage in focus mode

- .changeset/purple-pets-develop.md
- packages/test-runner-cli/package.json
- packages/test-runner-cli/src/TestRunnerCli.ts
- packages/test-runner-cli/src/startTestRunner.ts
- packages/test-runner-core/src/runner/TestRunner.ts
- packages/test-runner-core/src/runner/TestRunnerConfig.ts
- packages/test-runner-dev-server/src/createDevServer.ts
- packages/test-runner/README.md
Fixes https://github.com/modernweb-dev/web/issues/70
> feat: separate coverage and coverageConfig options

- .changeset/thirty-frogs-knock.md
- packages/test-runner-cli/js/readFileConfig.d.ts
- packages/test-runner-cli/js/readFileConfig.js
- packages/test-runner-cli/src/startTestRunner.ts
Fixes https://github.com/modernweb-dev/web/issues/76
> fix(test-runner-cli): fix reading config from CLI arg

- .changeset/green-jobs-divide.md
- packages/test-runner-cli/src/startTestRunner.ts
fixes https://github.com/modernweb-dev/web/issues/87
> fix(test-runner-cli): set default rootDir

- packages/test-runner-core/src/runner/TestRunner.ts
- packages/test-runner-core/src/runner/TestScheduler.ts
Turns out the issue is not with puppeteer, but with us :)
Fixes https://github.com/modernweb-dev/web/issues/13
> fix(test-runner-core): clear all timeouts on close

- .changeset/sweet-pumas-explain.md
- packages/test-runner-browser-lib/src/index.ts
Fixes https://github.com/modernweb-dev/web/issues/90
> feat(test-runner-browser-lib): handle mocking fetch

- .changeset/khaki-boxes-ring.md
- packages/test-runner-browser-lib/src/index.ts
- packages/test-runner-browser-lib/src/stringify.ts
- packages/test-runner/demo/test/logging.test.js
- packages/test-runner/package.json
Fixes https://github.com/modernweb-dev/web/issues/52
> feat: serialize logged complex objects

- .changeset/hip-buses-compare.md
- packages/test-runner-browser-lib/src/stringify.ts
- packages/test-runner/demo/test/logging.test.js
Fixes https://github.com/modernweb-dev/web/issues/107
> Serialize url

- .changeset/few-laws-build.md
- packages/test-runner-cli/src/Terminal.ts
- packages/test-runner-cli/src/TestRunnerCli.ts
- packages/test-runner-cli/src/messages/getFileErrors.ts
- packages/test-runner-cli/src/messages/getSessionErrors.ts
- packages/test-runner-cli/src/messages/getTestFileReport.ts
- packages/test-runner-cli/src/messages/utils/formatError.ts
- packages/test-runner/demo/test/fail-custom-error.test.js
- packages/test-runner/demo/test/shared-a.js
Fixes https://github.com/modernweb-dev/web/issues/113
> fix(test-runner-cli): only remove server adress in stack trace

- .changeset/dry-bikes-punch.md
- packages/dev-server-esbuild/README.md
- packages/dev-server-esbuild/demo/jsx/app.jsx
- packages/dev-server-esbuild/demo/jsx/index.html
- packages/dev-server-esbuild/demo/jsx/server.config.js
- packages/dev-server-esbuild/demo/ts/app.ts
- packages/dev-server-esbuild/demo/ts/index.html
- packages/dev-server-esbuild/demo/ts/server.config.js
- packages/dev-server-esbuild/package.json
- packages/dev-server-esbuild/src/esbuildPlugin.ts
- packages/dev-server-esbuild/tsconfig.json
- packages/test-runner-server/README.md
- packages/test-runner/README.md
- packages/tsconfig.project.json
- scripts/update-package-tsconfig.ts
- yarn.lock
Fixes https://github.com/modernweb-dev/web/issues/20
> feat(dev-server-esbuild): first setup

- packages/test-runner/README.md
I removed a duplicate entry of config in the commands table
> fix(test-runner): removed duplicate entry in the commands table

- .changeset/cool-books-allow.md
- packages/test-runner-cli/src/TestRunnerCli.ts
- packages/test-runner-cli/src/messages/getTestFileErrors.ts
- packages/test-runner-cli/src/messages/getTestFileReport.ts
- packages/test-runner-cli/src/messages/getTestsErrors.ts
- packages/test-runner-cli/src/messages/utils/formatErrorMessage.ts
- packages/test-runner-cli/src/messages/utils/formatStackTrace.ts
- packages/test-runner-cli/src/messages/utils/getErrorLocation.ts
- packages/test-runner-cli/src/messages/utils/getRelativeStackFilePath.ts
- packages/test-runner-cli/src/messages/utils/replaceRelativeStackFilePath.ts
- packages/test-runner-cli/src/messages/utils/toBrowserPath.ts
- packages/test-runner-cli/src/messages/utils/toFilePath.ts
Fixes https://github.com/modernweb-dev/web/issues/120
> feat(test-runner-cli): resolve stack trace urls relative to root dir

- .changeset/hot-mayflies-crash.md
- packages/test-runner-server/src/testRunnerServer.ts
Fixes https://github.com/modernweb-dev/web/issues/110
> feat(test-runner-server): long term cache test runner libs

- .changeset/smooth-jeans-sip.md
- packages/dev-server-esbuild/README.md
- packages/dev-server-esbuild/package.json
- packages/dev-server-esbuild/src/esbuildPlugin.ts
- packages/dev-server-esbuild/src/isRecentModernBrowser.ts
- packages/dev-server-esbuild/test/getAutoEsTarget.test.ts
- yarn.lock
Fixes https://github.com/modernweb-dev/web/issues/140
> feat(dev-server-esbuild): add auto compatibility mode

- .changeset/tough-hotels-clap.md
- packages/test-runner-cli/src/messages/utils/formatStackTrace.ts
Fixes https://github.com/modernweb-dev/web/issues/164
> fix(test-runner-cli): remove minified test framework from stack trace

- .changeset/tame-impalas-dance.md
- packages/test-runner-cli/src/TestRunnerCli.ts
Fixes https://github.com/modernweb-dev/web/issues/155
> fix(test-runner-cli): print pending files in blue

- .changeset/funny-turkeys-sleep.md
- .changeset/stale-humans-unite.md
- .changeset/tough-phones-confess.md
- package.json
- packages/dev-server-core/package.json
- packages/dev-server-core/src/dom5/README.md
- packages/dev-server-core/src/dom5/index.ts
- packages/dev-server-core/src/dom5/iteration.ts
- packages/dev-server-core/src/dom5/modification.ts
- packages/dev-server-core/src/dom5/predicates.ts
- packages/dev-server-core/src/dom5/util.ts
- packages/dev-server-core/src/dom5/walking.ts
- packages/dev-server-core/src/event-stream/eventStreamPlugin.ts
- packages/dev-server-core/src/plugins/resolveModuleImportsPlugin.ts
- packages/dev-server-esbuild/src/esbuildPlugin.ts
- packages/dev-server-esbuild/src/getEsbuildTarget.ts
- packages/test-runner-server/package.json
- packages/test-runner/package.json
- yarn.lock
Fixes https://github.com/modernweb-dev/web/issues/7
> chore(dev-server-core): remove dependency on bulding-utils

- .changeset/afraid-pens-pull.md
- packages/test-runner-server/src/testRunnerServer.ts
Fixes https://github.com/modernweb-dev/web/issues/170
> fix(test-runner-server): run test coverage after user plugins

- .changeset/eleven-buckets-flash.md
- packages/test-runner-cli/src/messages/utils/formatStackTrace.ts
- packages/test-runner-cli/src/messages/utils/getRelativeStackFilePath.ts
Fixes https://github.com/modernweb-dev/web/issues/172
> fix(test-runner-cli): strip test session id from test file

- .changeset/cuddly-zoos-accept.md
- packages/dev-server-esbuild/package.json
- yarn.lock
Fixes https://github.com/modernweb-dev/web/issues/173
> feat(dev-server-esbuild): update to esbuild 0.6.x

- packages/dev-server-core/src/index.ts
- packages/dev-server-core/src/logger/PluginError.ts
- packages/dev-server-core/src/middleware/pluginTransformMiddleware.ts
- packages/dev-server-core/src/test-helpers.ts
- packages/dev-server-rollup/package.json
- packages/dev-server-rollup/src/rollupAdapter.ts
- packages/dev-server-rollup/src/utils.ts
- packages/dev-server-rollup/test/node/plugins/commonjs.test.ts
- packages/dev-server-rollup/test/node/test-helpers.ts
- packages/dev-server-rollup/test/node/unit.test.ts
- packages/test-runner/tsconfig.json
- packages/tsconfig.project.json
- yarn.lock
Fixes https://github.com/modernweb-dev/web/issues/189
> feat(dev-server-rollup): throw on imports resolved outside root dir

- .changeset/strong-ladybugs-provide.md
- packages/test-runner/package.json
- packages/test-runner/src/nodeResolvePlugin.ts
closes https://github.com/modernweb-dev/web/issues/184
closes https://github.com/modernweb-dev/web/issues/185
> chore: add web_modules and browser: true

- .changeset/mighty-papayas-attack.md
- packages/test-runner-chrome/package.json
- packages/test-runner-chrome/src/chromeLauncher.ts
- packages/test-runner-core/src/browser-launcher/BrowserLauncher.ts
- packages/test-runner-core/src/runner/TestRunner.ts
- packages/test-runner-core/src/runner/createTestSessions.ts
- packages/test-runner-core/test/TestRunner.test.ts
- packages/test-runner-playwright/README.md
- packages/test-runner-playwright/package.json
- packages/test-runner-playwright/src/playwrightLauncher.ts
- packages/test-runner-playwright/test/playwrightLauncher.test.ts
- packages/test-runner-puppeteer/README.md
- packages/test-runner-puppeteer/package.json
- packages/test-runner-puppeteer/src/puppeteerLauncher.ts
- packages/test-runner-selenium/src/seleniumLauncher.ts
- packages/test-runner/README.md
- packages/test-runner/src/loadLauncher.ts
- packages/test-runner/src/test-runner.ts
- yarn.lock
Fixes https://github.com/modernweb-dev/web/issues/58
Fixes https://github.com/modernweb-dev/web/issues/57
> feat: allow configuring browser launch options

- .github/workflows/release.yml
- CONTRIBUTING.md
- package.json
- packages/dev-server-core/src/test-helpers.ts
- packages/dev-server-rollup/test/node/unit.test.ts
- packages/dev-server/package.json
- packages/test-runner-browser-lib/package.json
- packages/test-runner-browserstack/package.json
- packages/test-runner-browserstack/test/browserstackLauncher.test.ts
- packages/test-runner-chrome/package.json
- packages/test-runner-chrome/test/chromeLauncher.test.ts
- packages/test-runner-cli/package.json
- packages/test-runner-core/test/TestRunner.test.ts
- packages/test-runner-coverage-v8/package.json
- packages/test-runner-helpers/package.json
- packages/test-runner-mocha/package.json
- packages/test-runner-mocha/src/collectTestResults.ts
- packages/test-runner-playwright/package.json
- packages/test-runner-playwright/test/playwrightLauncher.test.ts
- packages/test-runner-puppeteer/package.json
- packages/test-runner-puppeteer/test/puppeteerLauncher.test.ts
- packages/test-runner-selenium/package.json
- packages/test-runner-selenium/test/seleniumLauncher.test.ts
- packages/test-runner-server/package.json
- scripts/workspaces-scripts.mjs
Fixes https://github.com/modernweb-dev/web/issues/177
> chore: run tests in parallel

- .changeset/big-radios-speak.md
- packages/dev-server-core/package.json
- packages/dev-server-legacy/package.json
- packages/test-runner-browserstack/package.json
- packages/test-runner-cli/package.json
- packages/test-runner-core/package.json
- packages/test-runner-coverage-v8/package.json
- packages/test-runner-mocha/package.json
- packages/test-runner-server/package.json
- packages/test-runner/package.json
- yarn.lock
Fixes https://github.com/modernweb-dev/web/issues/205
Fixes https://github.com/modernweb-dev/web/issues/175
> chore: cleanup and sort dependencies

- .changeset/shy-oranges-judge.md
- packages/test-runner-cli/src/TestRunnerCli.ts
- packages/test-runner-cli/src/messages/getTestCoverage.ts
- packages/test-runner-cli/src/messages/getTestProgress.ts
Fixes https://github.com/modernweb-dev/web/issues/198
Fixes https://github.com/modernweb-dev/web/issues/182
Fixes https://github.com/modernweb-dev/web/issues/152
> feat(test-runner-cli): improve test coverage logging

- .changeset/happy-points-switch.md
- packages/test-runner-browser-lib/src/types.ts
- packages/test-runner-chrome/test/chromeLauncher.test.ts
- packages/test-runner-cli/src/config/readConfig.ts
- packages/test-runner-core/src/index.ts
- packages/test-runner-core/src/runner/TestRunnerCoreConfig.ts
- packages/test-runner-core/src/test-framework/TestFramework.ts
- packages/test-runner-core/test/TestRunner.test.ts
- packages/test-runner-mocha/README.md
- packages/test-runner-mocha/src/autorun.ts
- packages/test-runner-playwright/test/playwrightLauncher.test.ts
- packages/test-runner-puppeteer/test/puppeteerLauncher.test.ts
- packages/test-runner-selenium/test/seleniumLauncher.test.ts
- packages/test-runner-server/src/serveTestFrameworkPlugin.ts
- packages/test-runner-server/src/serveTestRunnerHtmlPlugin.ts
- packages/test-runner-server/src/testRunnerApiMiddleware.ts
- packages/test-runner-server/src/testRunnerServer.ts
- packages/test-runner/README.md
- packages/test-runner/demo/test/chai.js
- packages/test-runner/demo/test/mocha-options/a.test.js
- packages/test-runner/demo/test/mocha-options/config.js
- packages/test-runner/package.json
- packages/test-runner/src/test-runner.ts
Fixes https://github.com/modernweb-dev/web/issues/165
> feat: allow configuring test framework options

- .changeset/gorgeous-books-sin.md
- packages/test-runner/src/nodeResolvePlugin.ts
Fixes https://github.com/modernweb-dev/web/issues/224
> fix(test-runner): reduce .ts file extension priority

- .changeset/yellow-lions-tap.md
- packages/dev-server-rollup/src/rollupAdapter.ts
- packages/dev-server-rollup/test/node/fixtures/basic/foo.html
- packages/dev-server-rollup/test/node/fixtures/basic/multiple-inline.html
- packages/dev-server-rollup/test/node/unit.test.ts
I have some duplicate code, need to see how to clean it up a bit
> feat: handle inline scripts

- .changeset/fluffy-pots-design.md
- packages/dev-server-core/src/middleware/watchServedFilesMiddleware.ts
Fixes https://github.com/modernweb-dev/web/issues/234
> fix(dev-server-core): fix not watching files with syntax errors

- .changeset/blue-ties-admire.md
- packages/test-runner-chrome/README.md
- packages/test-runner-chrome/src/chromeLauncher.ts
- packages/test-runner-playwright/README.md
- packages/test-runner-playwright/src/playwrightLauncher.ts
- packages/test-runner-puppeteer/README.md
- packages/test-runner-puppeteer/src/puppeteerLauncher.ts
Fixes https://github.com/modernweb-dev/web/issues/245
> feat: allow customizing browser page creation

- .changeset/sweet-insects-double.md
- packages/test-runner-playwright/src/PlaywrightLauncherPage.ts
Fixes https://github.com/modernweb-dev/web/issues/262
I can't reproduce the issue anymore, it was probably something local when I was working on the code.
> chore(test-runner-playwright): remove log serialization workaround

- .changeset/fifty-students-clap.md
- packages/test-runner-coverage-v8/src/index.ts
Fixes https://github.com/modernweb-dev/web/issues/265
> feat(test-runner-coverage-v8): resolve include/exclude patterns

- .changeset/silly-seals-wave.md
- packages/test-runner-chrome/src/ChromeLauncherPage.ts
- packages/test-runner-playwright/src/PlaywrightLauncherPage.ts
Partially fixes https://github.com/modernweb-dev/web/issues/276
> fix: guard against the browser logs script being unavailable

- .changeset/hungry-radios-wait.md
- packages/dev-server-core/src/test-helpers.ts
- packages/dev-server-esbuild/package.json
- packages/dev-server-esbuild/src/esbuildPlugin.ts
- packages/dev-server-esbuild/test/fixture/a/b/bar.js
- packages/dev-server-esbuild/test/fixture/a/b/foo.ts
- packages/dev-server-esbuild/test/jsx.test.ts
- packages/dev-server-esbuild/test/target.test.ts
- packages/dev-server-esbuild/test/ts.test.ts
- packages/dev-server-esbuild/test/tsx.test.ts
- yarn.lock
Fixes https://github.com/modernweb-dev/web/issues/188
Also improves test coverage for the esbuild plugin in general.
> feat(dev-server-esbuild): support .js extensions in TS imports

- .changeset/large-oranges-wonder.md
- packages/test-runner-playwright/package.json
- yarn.lock
> feat(test-runner-playwright): update to playwright 1.3.x

- docs/about/family.md
- docs/about/sponsor.md
- docs/blog/index.md
- docs/blog/introducing-modern-web/index.md
- docs/index.md
Some general improvements, and ran some pages through grammarly.
I didn't touch the `learn` section, because @bennypowers has a PR open on that. The `docs` section will be in a separate PR as well.
> docs: general improvements and grammar check

- docs/_assets/logo-color.svg
- docs/_assets/logo.svg
- docs/_assets/style.css
- docs/_assets/variables.css
- docs/_data/site.js
- docs/learn/index.md
- docs/learn/standards-based/dom.md
- docs/learn/standards-based/es-modules.md
- docs/learn/standards-based/html.md
- docs/learn/standards-based/index.md
- docs/learn/standards-based/servers-and-clients.md
- package.json
- yarn.lock
> Learn section

- README.md
- docs/_data/site.js
- docs/blog/introducing-modern-web/index.md
- docs/index.md
This aligns the project description everywhere we use it, and I made some changes that I think reflect the position of the project. Just my opinion, of course :)
> docs: align and improve project description

- docs/_data/site.js
- package.json
- yarn.lock
relies on https://github.com/daKmoR/rocket/pull/23
> fix: github link layout

- .changeset/afraid-numbers-approve.md
- packages/test-runner-cli/package.json
- packages/test-runner-cli/src/config/readCliArgsConfig.ts
- packages/test-runner/src/test-runner.ts
Fixes https://github.com/modernweb-dev/web/issues/35
> feat(test-runner-cli): add --help command

- docs/blog/introducing-modern-web/index.md
- docs/learn/test-runner/responsive.md
- packages/test-runner-commands/README.md
closes https://github.com/modernweb-dev/web/issues/342
> chore: responsive learn to use test-runner-commands

- .changeset/young-keys-remember.md
- packages/test-runner-commands/plugins.js
Fixes https://github.com/modernweb-dev/web/issues/362
> fix(test-runner-commands): make the /plugins import work on node v10

- docs/_assets/variables.css
- docs/learn/standards-based/css.md
- docs/learn/standards-based/dom.md
- docs/learn/standards-based/html.md
- docs/learn/standards-based/javascript.md
- docs/learn/standards-based/servers-and-clients.md
also adds dark mode syntax colors from "Material Oceanic" theme.
> Edits for HTML, CSS, JS, DOM and ES Modules Guides

- docs/_assets/style.css
- docs/_assets/variables.css
depends on https://github.com/daKmoR/rocket/pull/30
> chore: add more darkmode styling

- .remarkignore
- docs/blog/introducing-modern-web/index.md
- docs/blog/introducing-web-test-runner/index.md
- docs/discover/slack.md
- docs/docs/dev-server/plugins/examples.md
- docs/docs/test-runner/browsers/overview.md
- docs/docs/test-runner/overview.md
- docs/docs/test-runner/writing-tests/js-tests.md
- docs/guides/index.md
- docs/guides/test-runner/code-coverage/index.md
- docs/guides/web-development/components.md
- docs/guides/web-development/html.md
- docs/guides/web-development/javascript.md
- docs/guides/web-development/servers-and-clients.md
- package.json
- yarn.lock
- focuses the blog post more on the general idea of Modern Web
- adds markdown linting
- fixes all linting issues including broken markdown links
> chore: split blog posts

- .changeset/gorgeous-ducks-enjoy.md
- packages/browser-logs/src/deserialize.ts
- packages/browser-logs/src/serialize.ts
- packages/browser-logs/test-browser/browser-logs.test.ts
- packages/test-runner-cli/src/reporter/reportBrowserLogs.ts
- packages/test-runner/demo/test/logging.test.js
Fixes https://github.com/modernweb-dev/web/issues/425
> fix: improve handling of undefined and null in browser logs

- .changeset/popular-hornets-hunt.md
- packages/test-runner-chrome/src/ChromeLauncherPage.ts
Fixes https://github.com/modernweb-dev/web/issues/431
> fix(test-runner-chrome): fix collecting code coverage

- .changeset/moody-turtles-promise.md
- packages/test-runner-cli/src/reporter/defaultReporter.ts
fixes https://github.com/modernweb-dev/web/issues/442
> fix(test-runner-cli): avoid instanceOf check

- .changeset/slow-dodos-love.md
- docs/docs/dev-server/plugins/legacy.md
- packages/dev-server-legacy/src/injectPolyfillsLoader.ts
- packages/dev-server-legacy/src/legacyPlugin.ts
Fixes https://github.com/modernweb-dev/web/issues/450
> fix(dev-server-legacy): set correct source filename for inline scripts

- packages/dev-server-core/package.json
- yarn.lock
Fixes https://github.com/modernweb-dev/web/issues/474
> fix(dev-server-core): add missing get-stream package

- .changeset/fuzzy-buttons-approve.md
- packages/rollup-plugin-copy/src/copy.js
missed the release before 😅
while I was at it I also improved function docu
> chore: schedule a release for rollup-plugin-copy

- .changeset/pretty-ladybugs-boil.md
- packages/dev-server-cli/package.json
- packages/dev-server-core/src/Plugin.ts
- packages/dev-server-core/src/middleware/pluginTransformMiddleware.ts
- packages/dev-server-core/src/plugins/transformModuleImportsPlugin.ts
- packages/dev-server-rollup/src/rollupAdapter.ts
- packages/dev-server-rollup/test/node/unit.test.ts
- packages/dev-server/demo/node-resolve/index.html
- packages/dev-server/demo/node-resolve/module.js
- packages/dev-server/package.json
Fixes https://github.com/modernweb-dev/web/issues/227
> feat: improve logging of resolving outside root dir

- docs/guides/going-buildless/css.md
Replace Shadom with the correct term Shadow
> Correct a typo

- docs/docs/dev-server/cli-and-configuration.md
- docs/docs/dev-server/middleware/index.md
- docs/docs/dev-server/overview.md
- docs/docs/dev-server/plugins/index.md
- docs/docs/test-runner/cli-and-configuration.md
Basic setup for the dev server docs. Will add more later.
> docs: add first dev server docs

- .changeset/three-mugs-turn.md
- docs/docs/dev-server/plugins/esbuild.md
- packages/dev-server-esbuild/src/EsbuildPlugin.ts
> feat(dev-server-esbuild): exposed strict option from esbuild

- .changeset/fifty-worms-study.md
- packages/config-loader/package.json
- fix path for module users in node
> fix(config-loader): export map entry for import needs to be valid

- .changeset/calm-mugs-train.md
- packages/test-runner/src/startTestRunner.ts
Fixes https://github.com/modernweb-dev/web/issues/233
> feat(test-runner): also report syntax errors when not using the node-resolve flag

- .changeset/great-jokes-shave.md
- packages/test-runner-coverage-v8/package.json
- yarn.lock
Fixes https://github.com/modernweb-dev/web/issues/293
> feat(test-runner-coverage-v8): update to v8-to-istanbul v5

- .changeset/tricky-crabs-pay.md
- packages/test-runner-chrome/src/ChromeLauncherPage.ts
- packages/test-runner-playwright/src/PlaywrightLauncherPage.ts
- packages/test-runner-selenium/src/WindowManager.ts
- packages/test-runner/demo/selenium.config.js
Fixes https://github.com/modernweb-dev/web/issues/544
> fix(test-runner): handle infinite loops when reloading the page

- docs/blog/introducing-modern-web/index.md
fixes some typos in the intro blog post
> docs: fix a few typos in the intro blog post

- .changeset/friendly-clocks-cheer.md
- packages/dev-server-core/src/server/createMiddleware.ts
Fixes https://github.com/modernweb-dev/web/issues/565
> fix(dev-server-core): don't serve compressed files

- .changeset/chilled-plants-lick.md
- .changeset/odd-berries-smash.md
- packages/test-runner-commands/package.json
- packages/test-runner-core/package.json
- packages/test-runner-mocha/package.json
- packages/test-runner-mocha/rollup.config.js
- packages/test-runner-mocha/tsconfig.json
- packages/test-runner-visual-regression/package.json
- yarn.lock
Fixes https://github.com/modernweb-dev/web/issues/568
> chore(test-runner-mocha): make mocha a dev dependency

- .changeset/calm-ways-invite.md
- .changeset/short-trees-kiss.md
- packages/test-runner-cli/src/config/readCliArgsConfig.ts
Fixes https://github.com/modernweb-dev/web/issues/560
> feat(test-runner): allow unknown cli args

- .changeset/old-tomatoes-scream.md
- packages/test-runner-core/src/server/utils.ts
- packages/test-runner/demo/parent-dir.mjs
- packages/test-runner/package.json
Fixes https://github.com/modernweb-dev/web/issues/593
> fix(test-runner-core): fix serving test files outside cwd

- .changeset/quiet-drinks-own.md
- packages/test-runner-saucelabs/package.json
- packages/test-runner-saucelabs/src/SauceLabsLauncherManager.ts
- packages/test-runner-saucelabs/src/createSauceLabsLauncher.ts
- packages/test-runner-saucelabs/test-remote/saucelabsLauncher.test.js
- yarn.lock
Use webdriver endpoints from sauce library instead of hardcoding the URL.
> feat(test-runner-saucelabs): use webdriver endpoints from sauce library

- .changeset/beige-chairs-help.md
- packages/test-runner-core/index.mjs
- packages/test-runner-core/src/index.ts
- packages/test-runner-core/src/server/middleware/testRunnerApiMiddleware.ts
- packages/test-runner-core/src/server/plugins/serveTestRunnerHtmlPlugin.ts
- packages/test-runner-core/src/server/utils.ts
- packages/test-runner-core/src/utils/isTestFilePath.ts
- packages/test-runner-mocha/package.json
- packages/test-runner/index.mjs
Fixes https://github.com/modernweb-dev/web/issues/594
> feat(test-runner): allow transforming test file imports

- .changeset/unlucky-impalas-tan.md
- packages/dev-server-core/src/middleware/PluginTransformCache.ts
- packages/dev-server-core/src/middleware/pluginTransformMiddleware.ts
Fixes https://github.com/modernweb-dev/web/issues/626
> fix(dev-server-core): correctly cache index.html using / path

- package.json
- rocket.config.mjs
- yarn.lock
1. Enable faster watch mode for rocket
2. Add rocket search plugin (cli only for now)
You can test it by 
```
yarn search <search term>
```
> chore: faster server, and search plugin for rocket

- .changeset/tricky-pans-search.md
- docs/docs/dev-server/plugins/legacy.md
- packages/dev-server-legacy/src/injectPolyfillsLoader.ts
- packages/dev-server-legacy/src/legacyPlugin.ts
- packages/test-runner/demo/legacy.config.mjs
- packages/test-runner/package.json
Fixes https://github.com/modernweb-dev/web/issues/659
> feat(polyfills-loader): make polyfills configurable

- docs/docs/dev-server/node-api.md
1. Added docs regarding the `stop()` command that is available on a server instance.
> docs(dev-server): include 'stop()' command

- .changeset/rich-dodos-reply.md
- packages/test-runner-playwright/src/PlaywrightLauncher.ts
1. Share browser context between pages in playwright. This should improve speed.
> feat(test-runner-playwright): share browser context across pages

- .changeset/chatty-fishes-jump.md
- packages/test-runner-core/src/server/plugins/serveTestFrameworkPlugin.ts
Fixes https://github.com/modernweb-dev/web/issues/754
> fix(test-runner): correctly encode/decode test framework url

- docs/_data/rocketLaunch.json
- docs/_data/site.js
- package.json
- yarn.lock
1. we want a nice default social media image on twitter 😬
2. also adds a colon ": " between the parent page and actual page in the page title
> chore: bring back the default social media image

- package.json
- yarn.lock
1. Update Rollup so nested folders get added to the final output build
2. Fixes missing favicon for modern-web.dev
> chore: add icons to build output

- .changeset/strange-jars-lay.md
- packages/dev-server-rollup/src/fromRollup.ts
- packages/dev-server-rollup/src/rollupAdapter.ts
- packages/dev-server/src/plugins/nodeResolvePlugin.ts
Fixes https://github.com/modernweb-dev/web/issues/597
> feat(dev-server): add error when a bare import cannot be resolved

- .changeset/chilly-dryers-attack.md
- packages/dev-server-core/package.json
- yarn.lock
Fixes https://github.com/modernweb-dev/web/issues/760
> fix(dev-server): add koa types dependency

- README.md
- docs/blog/introducing-modern-web/index.md
- docs/discover/slack.md
- docs/docs/dev-server/overview.md
- docs/docs/dev-server/writing-plugins/examples.md
- docs/docs/test-runner/browser-launchers/write-your-own.md
- docs/docs/test-runner/overview.md
- docs/docs/test-runner/reporters/write-your-own.md
- docs/docs/test-runner/writing-tests/helper-libraries.md
- docs/docs/test-runner/writing-tests/js-tests.md
- docs/faqs/html.md
- docs/faqs/javascript.md
- docs/guides/going-buildless/css.md
- docs/guides/going-buildless/serving.md
- docs/guides/test-runner/browsers.md
- packages/test-runner-browserstack/README.md
- packages/test-runner-chrome/README.md
- packages/test-runner-playwright/README.md
- packages/test-runner-puppeteer/README.md
- packages/test-runner-saucelabs/README.md
- packages/test-runner-selenium/README.md
> Fix broken links in documentation

- .changeset/small-starfishes-report.md
- packages/dev-server-storybook/demo/wc/.storybook/manager.js
- packages/dev-server-storybook/package.json
- packages/dev-server-storybook/src/build/build.ts
- packages/dev-server-storybook/src/serve/storybookPlugin.ts
- packages/dev-server-storybook/src/shared/config/StorybookConfig.ts
- packages/dev-server-storybook/src/shared/config/readStorybookConfig.ts
- packages/dev-server-storybook/src/shared/html/createManagerHtml.ts
- yarn.lock
1. Handle `.storybook/manager.js` files, including them in the manager
> feat(dev-server-storybook): handle manager.js files

- .changeset/kind-waves-dress.md
- packages/rollup-plugin-html/src/input/extract/extractModules.ts
- packages/rollup-plugin-html/test/src/input/extract/extractModules.test.ts
Fixes https://github.com/modernweb-dev/web/issues/816
> fix(rollup-plugin-html): skip scripts with absolute paths

- .changeset/dry-balloons-sip.md
- packages/test-runner-playwright/package.json
- yarn.lock
1. Update Playwright to `1.6.0` which includes the fix for Firefox focus concurrency issues microsoft/playwright#3476
> feat(test-runner-playwright): update to playwright 1.6.x

- .changeset/eight-baboons-eat.md
- packages/test-runner-core/src/server/plugins/serveTestRunnerHtmlPlugin.ts
- packages/test-runner-core/src/server/utils.ts
- packages/test-runner-core/src/utils/constants.ts
- packages/test-runner-core/src/utils/isTestFilePath.ts
Fixes https://github.com/modernweb-dev/web/issues/877
> fix(test-runner): track manual test sessions imports

- .github/workflows/verify-browserstack.yml
- .github/workflows/verify-node.yml
- .github/workflows/verify-saucelabs.yml
- .github/workflows/verify-windows.yml
- renovate.json5
1. Renovate: Automatically merge update PRs (for all except major updates) as long as they pass tests
1. Renovate: Use branch automerging (create a branch, wait for test results, and silently merge if tests pass; otherwise, open a PR)
1. Actions: Run tests on Renovate branches (to make branch automerging work)
@LarsDenBakker
> Make Renovate quieter

- package.json
- renovate.json5
- yarn.lock
1. Updated Renovate config to not automerge minor updates
1. Reverted upgrades to packages that I think broke the website
> Renovate: don't automerge minor updates, and revert @d4kmor/* updates

- .changeset/big-crabs-film.md
- packages/test-runner-coverage-v8/package.json
- yarn.lock
update v8-to-istanbul dependency
> feat(test-runner-coverage-v8): update v8-to-istanbul dependency

- .changeset/lemon-rockets-prove.md
- packages/dev-server-hmr/src/HmrPlugin.ts
- packages/dev-server-hmr/test/HmrPlugin.test.ts
Fixes https://github.com/modernweb-dev/web/issues/942
> feat(dev-server-hmr): improve dependency handling

- .changeset/six-rings-sniff.md
- packages/dev-server/src/config/parseConfig.ts
Fixes https://github.com/modernweb-dev/web/issues/967
> fix(dev-server): handle preserve-symlinks CLI arg

- .changeset/purple-shoes-tell.md
- packages/dev-server-core/package.json
- packages/dev-server-core/src/plugins/parseDynamicImport.ts
- packages/dev-server-core/src/plugins/transformModuleImportsPlugin.ts
- packages/dev-server-core/test/plugins/parseDynamicImport.test.ts
- packages/dev-server-core/test/plugins/transformModuleImportsPlugin.test.ts
Improves handling of dynamic imports, covering more edge cases with whitespace and concatenated strings.
Fix for https://github.com/modernweb-dev/web/pull/759
> feat(dev-server): improve handling of dynamic imports

- .changeset/violet-kiwis-double.md
- packages/dev-server-hmr/demo/vanilla/component.js
- packages/dev-server-hmr/demo/vanilla/sharedTemplate.js
- packages/dev-server-hmr/src/HmrPlugin.ts
- packages/dev-server-hmr/test/HmrPlugin.test.ts
1. fix resolving relative imports
> fix(dev-server-hmr): fix resolving relative imports

- .eslintignore
- packages/dev-server-hmr/package.json
- packages/dev-server-hmr/scripts/hmrClientScript.js
- packages/dev-server-hmr/src/HmrPlugin.ts
Move HMR client script to a separate file
> feat(dev-server-hmr): move HMR client script

- .changeset/seven-mice-admire.md
- packages/dev-server-hmr/src/HmrPlugin.ts
- packages/dev-server-hmr/test/HmrPlugin.test.ts
- packages/dev-server-hmr/test/browser.test.ts
- packages/dev-server-hmr/test/utils.ts
Fixes https://github.com/modernweb-dev/web/issues/984.
> feat(dev-server-hmr): update bubbled dependencies

- packages/test-runner-selenium/package.json
- yarn.lock
1. Updated `selenium-standalone` to the latest version.
Currently tests on master fail locally with Chrome 87 as the installed Chromedriver version only supports 85.
> chore(test-runner-selenium): bump selenium-standalone

- .changeset/nervous-points-travel.md
- packages/rollup-plugin-workbox/package.json
- yarn.lock
1. upgraded to workbox-build@6.0.0 in rollup-plugin-workbox
> feat: upgrade workbox-build in rollup-plugin-workbox

- packages/dev-server-storybook/tsconfig.json
- tsconfig.json
1. Run `npm run generate-ts-configs` and it performed this change.
>  chore: regenerate tsconfig.json files

- README.md
1. Added Web Dev Server to the "Our products" section in README.
> chore: add dev server to products in README

- .changeset/calm-goats-wash.md
- packages/dev-server-rollup/package.json
- packages/dev-server-rollup/src/rollupAdapter.ts
- packages/dev-server-rollup/test/node/plugins/node-resolve.test.ts
- yarn.lock
Don't throw on unresolved local imports.
> fix(dev-server-rollup): don't throw on unresolved local imports

- packages/dev-server-hmr/package.json
- packages/polyfills-loader/package.json
- packages/rollup-plugin-polyfills-loader/test/snapshots/systemjs.html
- packages/test-runner-puppeteer/package.json
- packages/test-runner-selenium/test/seleniumLauncher.test.ts
- packages/test-runner-webdriver/test/webdriverLauncher.test.ts
- yarn.lock
> chore: update dependencies

- .changeset/grumpy-avocados-wait.md
- packages/dev-server-rollup/src/rollupAdapter.ts
Fixes https://github.com/modernweb-dev/web/issues/1012
> fix(dev-server-rollup): don't handle virtual files

- docs/docs/test-runner/reporters/junit.md
> chore: align docs for junit test reporter

- packages/test-runner-webdriver/README.md
1. Added `README.md` which was missing from the `packages/test-runner-webdriver` folder I created previously.
> chore(test-runner-webdriver): add missing README

- .changeset/hot-shoes-tease.md
- packages/test-runner-saucelabs/package.json
- packages/test-runner-saucelabs/src/createSauceLabsLauncher.ts
- packages/test-runner-webdriver/package.json
- packages/test-runner-webdriver/src/utils.ts
- packages/test-runner-webdriver/src/webdriverLauncher.ts
- yarn.lock
1. adds heartbeat to webdriver launcher
2. updates webdriver packages
> feat(test-runner-webdriver): add heartbeat to webdriver launcher

- .changeset/little-terms-raise.md
- packages/dev-server-storybook/src/serve/storybookPlugin.ts
Only reload preview in watch mode
> feat(dev-server-storybook): only reload preview in watch mode

- packages/dev-server-core/architecture.md
- packages/dev-server-core/src/index.ts
- packages/dev-server-core/src/middleware/PluginTransformCache.ts
- packages/dev-server-core/src/middleware/pluginFileParsedMiddleware.ts
- packages/dev-server-core/src/middleware/pluginMimeTypeMiddleware.ts
- packages/dev-server-core/src/middleware/pluginServeMiddleware.ts
- packages/dev-server-core/src/middleware/pluginTransformMiddleware.ts
- packages/dev-server-core/src/middleware/serveFilesMiddleware.ts
- packages/dev-server-core/src/plugins/Plugin.ts
- packages/dev-server-core/src/plugins/mimeTypesPlugin.ts
- packages/dev-server-core/src/plugins/transformModuleImportsPlugin.ts
- packages/dev-server-core/src/server/DevServer.ts
- packages/dev-server-core/src/server/DevServerCoreConfig.ts
- packages/dev-server-core/src/server/addPlugins.ts
- packages/dev-server-core/src/server/createMiddleware.ts
- packages/dev-server-core/src/server/createServer.ts
- packages/dev-server-core/src/test-helpers.ts
- packages/dev-server-core/src/web-sockets/webSocketsPlugin.ts
- packages/dev-server-core/test/helpers.ts
- packages/dev-server-core/test/server/DevServer.test.ts
- packages/test-runner-core/architecture.md
This adds some docs on the architecture of the dev server and test runner. I also moved some files around for clarity.
> chore: add architecture docs

- .changeset/wet-cars-laugh.md
- docs/docs/dev-server/plugins/esbuild.md
- packages/dev-server-esbuild/package.json
- packages/dev-server-esbuild/src/EsbuildPlugin.ts
- packages/dev-server-esbuild/test/json.test.ts
- packages/dev-server-esbuild/test/ts.test.ts
Fixes https://github.com/modernweb-dev/web/issues/1098
> feat(dev-server-esbuild): set esm format non eslike loaders

- .changeset/rare-seas-flow.md
- packages/dev-server-rollup/src/rollupAdapter.ts
- packages/dev-server-rollup/test/node/unit.test.ts
Fixes https://github.com/modernweb-dev/web/issues/1093
> fix(dev-server-rollup): handle null bytes in HTML

- .changeset/late-snails-sleep.md
- packages/test-runner-chrome/src/findExecutablePath.ts
Fixes https://github.com/modernweb-dev/web/issues/281
> feat(test-runner-chrome): use fast chrome-launcher installation finder

- .changeset/tidy-trainers-chew.md
- docs/docs/building/rollup-plugin-html.md
- packages/rollup-plugin-html/src/RollupPluginHTMLOptions.ts
- packages/rollup-plugin-html/src/output/createHTMLOutput.ts
- packages/rollup-plugin-html/src/output/getOutputHTML.ts
- packages/rollup-plugin-html/src/output/injectServiceWorkerRegistration.ts
- packages/rollup-plugin-html/src/rollupPluginHTML.ts
- packages/rollup-plugin-html/test/fixtures/inject-service-worker/index.html
- packages/rollup-plugin-html/test/fixtures/inject-service-worker/sub-pure-html/index.html
- packages/rollup-plugin-html/test/fixtures/inject-service-worker/sub-with-js/index.html
- packages/rollup-plugin-html/test/fixtures/inject-service-worker/sub-with-js/sub-js.js
- packages/rollup-plugin-html/test/rollup-plugin-html.test.ts
- packages/rollup-plugin-html/test/src/output/getOutputHTML.test.ts
1. inject a service worker registration script if enabled and a swDest filepath is provided
> feat(rollup-plugin-html): option to inject a service worker registration

- docs/guides/dev-server/using-plugins.md
> Fix commonjs include paths

- .changeset/twenty-dolls-punch.md
- packages/test-runner-core/src/server/plugins/api/parseBrowserErrors.ts
- packages/test-runner-core/src/server/plugins/api/parseBrowserLogs.ts
- packages/test-runner-core/src/server/plugins/api/parseBrowserResult.ts
- packages/test-runner-core/src/server/plugins/api/testRunnerApiPlugin.ts
Normalize test framework path in stack traces
> fix(test-runner): normalize test framework path in stack traces

- .changeset/six-monkeys-shake.md
- packages/test-runner-core/src/server/plugins/api/createSourceMapFunction.ts
Fixes https://github.com/modernweb-dev/web/issues/1183
> feat(test-runner): deduplicate parallel source map requests

- .changeset/curly-teachers-admire.md
- packages/test-runner-core/src/server/plugins/api/parseBrowserLogs.ts
Fixes https://github.com/modernweb-dev/web/issues/1203
> fix(test-runner): fix regression in filterBrowserLogs function

- docs/guides/going-buildless/serving.md
1. Fixed relattive typo in Serving guide
> docs: fix relattive typo

- .changeset/strong-beans-search.md
- packages/test-runner-core/src/server/plugins/serveTestRunnerHtmlPlugin.ts
Fixes https://github.com/modernweb-dev/web/issues/1201
> fix(test-runner): fix manual testing of HTML tests

- .changeset/six-dingos-rhyme.md
- packages/dev-server-storybook/package.json
- packages/dev-server-storybook/src/shared/utils.ts
- yarn.lock
Fixes https://github.com/modernweb-dev/web/issues/1229
> fix(dev-server-storybook): fix checking path on windows

- README.md
- docs/discover/slack.md
1. Fixed capitalization of "Slack" in the docs.
> fix capitalization of "Slack"

- .changeset/fifty-coats-begin.md
- packages/dev-server-storybook/src/shared/stories/findStories.ts
Attempt nr 2 at fixing storybook windows paths
> fix(dev-server-storybook): normalize paths received from storybook

- docs/docs/building/rollup-plugin-polyfills-loader.md
1. Updated docs for rollup-plugin-html example
> Update rollup-plugin-polyfills-loader docs

- .changeset/smooth-balloons-unite.md
- packages/test-runner-chrome/src/ChromeLauncherPage.ts
- packages/test-runner-core/src/utils/fetchSourceMap.ts
- packages/test-runner-coverage-v8/src/index.ts
- packages/test-runner-playwright/src/PlaywrightLauncherPage.ts
Handle cases when user agent is not defined
> fix(test-runner): handle cases when user agent is not defined

- .changeset/violet-rivers-visit.md
- packages/dev-server-core/src/server/createServer.ts
Fixes https://github.com/modernweb-dev/web/issues/692, something that's been annoying me for a long time :)
> fix(dev-server): filter server stream errors

- .changeset/eighty-parrots-help.md
- packages/rollup-plugin-polyfills-loader/src/utils.ts
- packages/rollup-plugin-polyfills-loader/test/src/utils.test.ts
> fix: inject polyfills loader also when regeneratorRuntime is always

- .changeset/thin-mice-flash.md
- docs/docs/dev-server/cli-and-configuration.md
- packages/dev-server-core/package.json
- packages/dev-server-core/src/middleware/basePathMiddleware.ts
- packages/dev-server-core/test/middleware/basePathMiddleware.test.ts
- packages/dev-server/src/config/parseConfig.ts
- packages/dev-server/src/config/readCliArgs.ts
- packages/dev-server/src/logger/createLogger.ts
- packages/dev-server/src/openBrowser.ts
1. Add base path support to CLI args
2. Document the base path feature
3. Handle trailing / in base path
> feat(dev-server): add base path support

- .changeset/three-colts-design.md
- packages/dev-server/src/openBrowser.ts
1. Fix an incorrect reference to the base path
> fix(dev-server): correctly reference base path

- packages/test-runner/README.md
> Fix test-runner README getting started link

- docs/docs/test-runner/writing-tests/mocking.md
> chore(typo)

- docs/guides/going-buildless/getting-started.md
1. Changed "has lead many in the industry know more about" to "has lead many in the industry to know more about"
> Fixed typo

- .changeset/real-papayas-push.md
- packages/dev-server-core/src/web-sockets/webSocketsPlugin.ts
1. Replaced `sslCert` with `http2`
> Use http2 config for websocket protocol check

- packages/dev-server-core/src/middleware/pluginTransformMiddleware.ts
- packages/dev-server-core/src/plugins/transformModuleImportsPlugin.ts
- packages/dev-server-core/src/utils.ts
- packages/dev-server-core/src/web-sockets/webSocketsPlugin.ts
- packages/dev-server-esbuild/src/EsbuildPlugin.ts
- packages/dev-server-hmr/src/HmrPlugin.ts
- packages/dev-server-import-maps/src/importMapsPlugin.ts
- packages/dev-server-legacy/src/injectPolyfillsLoader.ts
- packages/dev-server-legacy/src/legacyPlugin.ts
- packages/dev-server-rollup/src/createRollupPluginContextAdapter.ts
- packages/dev-server-rollup/src/rollupAdapter.ts
- packages/dev-server-rollup/test/node/plugins/babel.test.ts
- packages/dev-server-storybook/src/serve/storybookPlugin.ts
- packages/test-runner-core/src/server/plugins/serveTestRunnerHtmlPlugin.ts
- yarn.lock
> chore: update lockfile

- .changeset/curly-dodos-suffer.md
- packages/dev-server/demo/base-path/config.mjs
- packages/dev-server/src/openBrowser.ts
- packages/dev-server/test/integration.test.mjs
Fixes https://github.com/modernweb-dev/web/issues/1389
> fix(dev-server): fix open URL with base path and app index

- docs/discover/slack.md
- previously called Polymer slack
PS: similar change to https://github.com/open-wc/open-wc/pull/2146
> Update Lit & Friends slack links

- CONTRIBUTING.md
I cleaned up the CONTRIBUTING instructions. I also filed open-wc/open-wc#2143 at Open Web Components to make the CONTRIBUTING files match.
> Clean up CONTRIBUTING and match open-wc

- .changeset/violet-penguins-suffer.md
- packages/test-runner/src/config/parseConfig.ts
1. load the `sendKeysPlugin` in the default test runner config
> fix(commands): load sendKeysPlugin

- .changeset/unlucky-buttons-chew.md
- packages/dev-server-core/src/web-sockets/webSocketsPlugin.ts
Fixes https://github.com/modernweb-dev/web/issues/1421
> fix(dev-server-core): use script origin to connect websocket

- .husky/pre-commit
- package.json
Updated husky config to new v6 format. Fixes #1370.
> chore: Update husky config to v6 format

- docs/docs/test-runner/browser-launchers/playwright.md
- Added additional notes about using Playwright in CI / Docker environments.
> docs: Add notes about CI environments

- .changeset/angry-pandas-fry.md
> chore: fix changeset

- packages/dev-server/src/config/DevServerConfig.ts
change typo 'string' into primitive type string
1. Change type 'string' into string
> Fix DevServerConfig open type

- .changeset/moody-taxis-cheat.md
- packages/dev-server-storybook/package.json
- yarn.lock
1. New Storybook version, who dis?
Also, targeting `next` to hopefully actualize the "prerelease" workflow... 🤞
> Use the latest Storybook Prebuilt which uses the latest Storybook

- .changeset/afraid-cougars-raise.md
- packages/test-runner-mocha/src/autorun.ts
- packages/test-runner-mocha/src/standalone.ts
Exposes mocha runnable to retrieve the current test name.
> feat(test-runner-mocha): expose mocha runnable

- .changeset/gorgeous-donkeys-enjoy.md
- packages/test-runner-commands/src/snapshotPlugin.ts
- packages/test-runner-commands/test/snapshot/__snapshots__/browser-test.snap.js
- packages/test-runner-commands/test/snapshot/src/__snapshots__/nested-test.snap.js
- packages/test-runner-commands/test/snapshot/src/nested-test.js
> chore(test-runner-commands): improve snapshot formatting

- .changeset/twenty-needles-drive.md
- packages/test-runner-saucelabs/package.json
- packages/test-runner-saucelabs/src/createSauceLabsLauncher.ts
- packages/test-runner-webdriver/package.json
- yarn.lock
1. Updated `webdriver` and `webdriverio` dependencies to latest versions.
> feat: bump webdriverio to 7.7.4

- .changeset/cold-forks-explain.md
- packages/test-runner-core/src/cli/TestRunnerCli.ts
- packages/test-runner-core/src/config/TestRunnerCoreConfig.ts
- packages/test-runner/src/index.ts
- packages/test-runner/src/reporter/getCodeCoverage.ts
1. make the contents of `TestRunnerCoreConfig` and `CoverageConfig` optional
> fix(test-runner): allow partial configs

- packages/test-runner-core/src/utils/fetchSourceMap.ts
> chore: fix typo in web-test-runner console error

- packages/dev-server-storybook/README.md
> docs: fix typo in web dev server storybook docs

- .changeset/four-owls-smash.md
- packages/dev-server-storybook/package.json
- yarn.lock
1. Used latest Storybook Prebuilt and Markdown Docs Addon dependencies.
> Use latest upstream dependencies

- docs/docs/dev-server/middleware.md
1. Added details on how to add the koa-range middleware.
> docs: add example of using koa-range middleware

- .github/workflows/verify-node.yml
- .github/workflows/verify-windows.yml
1. Replace deprecated `microsoft/playwright-github-action`
> Replace deprecated `microsoft/playwright-github-action`

- .github/workflows/release.yml
- .github/workflows/verify-browserstack.yml
- .github/workflows/verify-node.yml
- .github/workflows/verify-saucelabs.yml
- .github/workflows/verify-windows.yml
1. Update to actions/setup-node@v2
2. Use the built-in cache
> Update to actions/setup-node@v2 and use the built-in cache

- docs/_assets/style.css
1. fix homepage colors. a better fix would be to find instances of `--text-color` in rocket and replace with `--primary-text-color`
> docs: fix homepage colors

- docs/guides/going-buildless/serving.md
> docs: fix misspelling in serving article

- .changeset/sixty-turkeys-brush.md
- packages/dev-server-rollup/package.json
- packages/test-runner-chrome/package.json
- packages/test-runner-commands/package.json
- packages/test-runner-coverage-v8/package.json
- packages/test-runner-junit-reporter/package.json
- packages/test-runner-mocha/package.json
- packages/test-runner-playwright/package.json
- packages/test-runner-puppeteer/package.json
- packages/test-runner-selenium/package.json
- packages/test-runner-visual-regression/package.json
- packages/test-runner-webdriver/package.json
- packages/test-runner/package.json
1. Updated all the packages to use the latest version of `@web/test-runner-core` for consistency.
> fix: align @web/test-runner-core version

- packages/test-runner-selenium/package.json
- packages/test-runner-selenium/test/seleniumLauncher.test.ts
- packages/test-runner-webdriver/package.json
- packages/test-runner-webdriver/test/webdriverLauncher.test.ts
- packages/test-runner/demo/runSelenium.mjs
- yarn.lock
1. Updated `selenium-standalone` to v7 - #1574 
2. Tried to unskip selenium and webdriver test suites 🤞 
3. Had to skip `locationChanged` as it timed out for both
Closes #1574
> chore(deps): update dependency selenium-standalone to v7

- .changeset/khaki-boxes-pretend.md
- packages/dev-server-core/package.json
- packages/dev-server-core/test/middleware/etagCacheMiddleware.test.ts
- packages/test-runner-browserstack/package.json
- packages/test-runner-browserstack/src/browserstackManager.ts
- packages/test-runner-core/package.json
- packages/test-runner-core/src/runner/createDebugSessions.ts
- packages/test-runner-core/src/runner/createSessionGroups.ts
- packages/test-runner-saucelabs/package.json
- packages/test-runner-saucelabs/src/createSauceLabsLauncher.ts
- yarn.lock
1. Replaced `uuid` dependency with `nanoid`
See the README for this package: https://github.com/ai/nanoid#nano-id
> refactor: replace uuid with nanoid

- packages/test-runner-selenium/test/seleniumLauncher.test.ts
1. Uncommented tests in Firefox, they seem to pass now.
> test: uncomment test-runner-selenium tests

- docs/docs/test-runner/browser-launchers/webdriver.md
1. Updated webdriver launcher docs to align with #1731
> docs: update Chrome args for latest selenium

- .changeset/wicked-steaks-tickle.md
- packages/test-runner-saucelabs/package.json
- packages/test-runner-webdriver/package.json
- yarn.lock
1. Updated `webdriver` and `webdriverio` to the latest versions.
> feat: update webdriver dependency to 7.16.0

- .changeset/olive-shoes-pay.md
- packages/test-runner-saucelabs/package.json
- yarn.lock
1. See https://github.com/saucelabs/node-saucelabs/issues/129
> fix: pin saucelabs version to 6.1.0 minor

- packages/test-runner-selenium/test/seleniumLauncher.test.ts
1. Uncommented `@web/test-runner-selenium` tests to see if they work on Windows now.
> test: enable Selenium tests on Windows

- packages/test-runner-commands/test/a11y-snapshot/a11ySnapshotPlugin.test.ts
- packages/test-runner-commands/test/emulate-media/emulateMediaPlugin.test.ts
- packages/test-runner-commands/test/send-keys/sendKeysPlugin.test.ts
- packages/test-runner-commands/test/set-viewport/setViewportPlugin.test.ts
- packages/test-runner-playwright/test/playwrightLauncher.test.ts
1. Uncommented `@web/test-runner-playwright` and `@web/test-runner-commands` tests.
> test: enable Playwright launcher tests on Windows

- packages/test-runner-webdriver/test/webdriverLauncher.test.ts
1. Uncommented `@web/test-runner-webdriver` tests to see if they work on Windows now.
> test: enable Webdriver launcher tests on Windows

- packages/test-runner-playwright/test/playwrightLauncher.test.ts
1. Had to skip some Playwright tests again as they seem to be flaky on Windows 😕
> test: skip flaky Playwright tests on Windows

- .github/workflows/canary.yml
- .github/workflows/release.yml
Update `github.repository` check.
> chore(ci): update github repository check

- docs/guides/going-buildless/es-modules.md
> docs: fix typo in going buildless guide

- packages/dev-server-core/src/server/DevServer.ts
> chore: remove duplicate word from the comment

- packages/test-runner-selenium/test/seleniumLauncher.test.ts
- packages/test-runner-webdriver/test/webdriverLauncher.test.ts
1. Updated the Chromedriver version as builds started to fail in GitHub Actions. Let's see if this helps.
> test: update Chromedriver to 96.0.4664.18

- docs/docs/test-runner/browser-launchers/playwright.md
> docs: update Playwright browser context examples

- .github/workflows/verify-browserstack.yml
- .github/workflows/verify-saucelabs.yml
Simplify the workflow condition on forks.
Related: https://github.com/modernweb-dev/web/pull/824#discussion_r785821800
> Update the workflow condition

- docs/guides/going-buildless/serving.md
1. Added a missing white space after a comma
> Add missing space

- .changeset/blue-moles-occur.md
- packages/test-runner-chrome/package.json
- yarn.lock
…0235
1. increased version of puppeteer to 13.1.3 to fix a security vulnerability in node-fetch.
> fix: update puppeteer-core dependency to 13.1.3

- .github/workflows/verify-windows.yml
- packages/test-runner-commands/test/send-mouse/sendMousePlugin.test.ts
- packages/test-runner-selenium/test/seleniumLauncher.test.ts
- packages/test-runner-webdriver/test/webdriverLauncher.test.ts
1. Removed hardcoded version which no longer works on GitHub Actions
2. Updated Windows image to `windows-2022` (the one that works)
> chore: use latest browser drivers and Windows 2022 image

- .changeset/smooth-dodos-return.md
- packages/test-runner-browserstack/package.json
- packages/test-runner-browserstack/src/browserstackLauncher.ts
1. This is a PR with the change from #1651 to trigger Browserstack CI workflow.
> feat: use Webdriver as base for BrowserstackLauncher

- .changeset/plenty-jeans-hide.md
- packages/rollup-plugin-polyfills-loader/src/rollupPluginPolyfillsLoader.ts
- packages/rollup-plugin-polyfills-loader/test/snapshots/customize-filetype-multi-output.html
- packages/rollup-plugin-polyfills-loader/test/snapshots/customize-filetype.html
- packages/rollup-plugin-polyfills-loader/test/snapshots/flattened.html
- packages/rollup-plugin-polyfills-loader/test/snapshots/multiple-entrypoints-retain-attributes.html
- packages/rollup-plugin-polyfills-loader/test/snapshots/multiple-entrypoints.html
- packages/rollup-plugin-polyfills-loader/test/snapshots/multiple-outputs.html
- packages/rollup-plugin-polyfills-loader/test/snapshots/no-polyfills-retain-attributes.html
- packages/rollup-plugin-polyfills-loader/test/snapshots/no-polyfills.html
- packages/rollup-plugin-polyfills-loader/test/snapshots/non-flattened.html
- packages/rollup-plugin-polyfills-loader/test/snapshots/polyfills.html
- packages/rollup-plugin-polyfills-loader/test/snapshots/single-output.html
- packages/rollup-plugin-polyfills-loader/test/snapshots/systemjs.html
1. Preload modules using modulepreload-shim when using es-module-shims
> fix preloading of module shims

- docs/docs/dev-server/overview.md
Update suggestions on setting up Web Dev Server by suggesting the use of --watch flag.
I feel like this flag is as important as the currently present suggested flags and therefore should be included
> Update Web Dev Server documentation suggestions

- CONTRIBUTING.md
Add note about building the project before running tests
1. Updated docs
> Improve test information

- .changeset/fuzzy-onions-juggle.md
- packages/dev-server-storybook/src/shared/config/readStorybookConfig.ts
- packages/dev-server-storybook/src/shared/stories/findStories.ts
1. Allow custom logic to be passed for `stories` in main.js
Related issue: https://github.com/modernweb-dev/web/issues/1833
> feat(dev-server-storybook): custom stories logic

- .changeset/sharp-ravens-confess.md
- packages/polyfills-loader/src/createPolyfillsData.ts
> fix: use correct property

- .changeset/many-seas-begin.md
- packages/polyfills-loader/package.json
- yarn.lock
Adds missing dependency to @web/polyfills-loader
> add missing dependency

- packages/dev-server-esbuild/demo/ts/.gitignore
- packages/dev-server-esbuild/demo/ts/app.ts
- packages/dev-server-esbuild/demo/ts/index.html
- packages/dev-server-esbuild/demo/ts/package.json
- packages/dev-server-esbuild/demo/ts/server.config.js
- packages/dev-server-esbuild/demo/ts/tsconfig.json
- packages/dev-server-esbuild/demo/ts/web-dev-server.config.js
I noticed the demo app for the ESBuild plugin was not finished. It had a syntax error, the config file had the wrong name, etc.
> fix / finish the demo app for esbuild plugin

- docs/docs/test-runner/cli-and-configuration.md
> docs: fix guide comment

- .changeset/tasty-panthers-breathe.md
- packages/polyfills-loader/src/createPolyfillsLoader.ts
1. Changed the function param of `loadScriptFunction` from `attr` to `att`.
> fix(create polyfills loader): changed attr func param to att

- docs/docs/dev-server/plugins/esbuild.md
- packages/dev-server-esbuild/src/EsbuildPlugin.ts
- packages/dev-server-esbuild/src/esbuildPluginFactory.ts
- packages/dev-server-esbuild/test/fixture/a/b/foo.ts
- packages/dev-server-esbuild/test/fixture/tsconfig.json
- packages/dev-server-esbuild/test/ts.test.ts
1. Added an option to specify the path to the tsconfig.json file (#1921)
2. Added a unit test
> dev-server-esbuild: option to specify path to tsconfig file

- docs/docs/dev-server/writing-plugins/hooks.md
1. add an example of how to add multiple files to the dev-server file watcher with `glob`
> docs: add file globbing example to serverStart

- docs/docs/dev-server/cli-and-configuration.md
1. Remove repeated word - "set" occurring twice
> docs: update cli-and-configuration.md

- .changeset/witty-windows-hug.md
- packages/test-runner-saucelabs/package.json
- yarn.lock
1. Updated pinned `saucelabs` version to the latest one.
See https://github.com/saucelabs/node-saucelabs/issues/129
> feat: update SauceLabs version to 7.2.0

- .changeset/cool-panthers-fail.md
- docs/docs/test-runner/commands.md
- packages/test-runner-commands/browser/commands.d.ts
- packages/test-runner-commands/src/emulateMediaPlugin.ts
- packages/test-runner-commands/test/emulate-media/emulateMediaPlugin.test.ts
- packages/test-runner-commands/test/emulate-media/forced-colors-test.js
- packages/test-runner-playwright/package.json
- yarn.lock
1. Add support for `forcedColors` in `emulateMedia` command.
2. Included tests.
3. Expanded `.d.ts` delivered documentation.
With this I can start testing on my end how to get VRTs in this context as I think some docs in this area to support better accessible delivery of elements will be 🧑‍🍳💋
> Add "forcedColors" support to "emulateMedia" command

- .changeset/green-bananas-sip.md
> chore: add changeset to release esbuild plugin

- .changeset/cuddly-mayflies-invent.md
- packages/test-runner-browserstack/package.json
- packages/test-runner-commands/package.json
- packages/test-runner-saucelabs/package.json
- packages/test-runner-visual-regression/package.json
- yarn.lock
This updates all local packages depending on `@web/test-runner-webdriver` to `^0.5.1`.
> fix(deps): update dependency @web/test-runner-webdriver to ^0.5.1

- .changeset/wise-ties-knock.md
- packages/test-runner/src/reporter/summaryReporter.ts
1. Added the browser name to the output of the summaryReporter
> feat(test-runner): update summary reporter to include browser name

- .changeset/shaggy-pigs-raise.md
- packages/dev-server-core/package.json
- yarn.lock
1. Updated `es-module-lexer` to `1.0.0` stable version which was released 9 days ago.
> feat: update es-module-lexer to 1.0.0

- .changeset/wise-weeks-type.md
> chore: changeset

- docs/docs/test-runner/browser-launchers/overview.md
1. enhanced a code example with a missing plugin integration
> Also mention `@web/test-runner-webdriver`

- docs/docs/test-runner/browser-launchers/webdriver.md
> Missing comma in `webdriver` docs

- .changeset/polite-monkeys-wink.md
- packages/dev-server-esbuild/src/EsbuildPlugin.ts
- packages/dev-server-esbuild/src/esbuildPluginFactory.ts
- packages/dev-server-esbuild/test/banner-footer.test.ts
Fixes #1676 
simple one but handy to expose
> feat (dev-server-esbuild): accept banner/footer setting to esbuild transformer

- packages/test-runner-visual-regression/README.md
1. Added missing parameters to package README
> Adds missing parameters from #1879

- package.json
- yarn.lock
1. Updated Lion components to matching versions to fix search field (currently, it's broken).
> chore: update Lion components to fix search input

- docs/docs/building/rollup-plugin-html.md
Fixes #1415 
1. Replaced imports in Rollup Plugin HTML doc
> docs: fix imports in rollupPluginHTML docs examples

- .changeset/quiet-dancers-tickle.md
- packages/polyfills-loader/README.md
- packages/polyfills-loader/package.json
- packages/polyfills-loader/src/createPolyfillsData.ts
- packages/polyfills-loader/src/types.ts
- packages/polyfills-loader/test/createPolyfillsData.test.ts
- yarn.lock
> feat(polyfills-loader): add URLPattern polyfill

- packages/dev-server-rollup/src/rollupAdapter.ts
1. revert https://github.com/modernweb-dev/web/commit/ab27e502ce2a2941ea02bc5523af1ef5826a5844, it seems to have been a breaking change
> fix: rollup adapter

- .changeset/heavy-foxes-teach.md
> ci: release

- .changeset/happy-adults-guess.md
- packages/test-runner/src/reporter/summaryReporter.ts
1. report browser logs when using summary reporter
> fix(test-runner): browser logs in summary reporter

- docs/docs/dev-server/writing-plugins/hooks.md
I added a missing ) to the docs.
> Add a missing )

- packages/dev-server-rollup/test/node/fixtures/commonjs/commonjs-browser-test.js
- packages/dev-server-rollup/test/node/plugins/commonjs.test.ts
- packages/rollup-plugin-html/test/rollup-plugin-html.test.ts
1. Cleaned up some `console.log()`s for @koddsson 
2. Updated how we configure the CJS plugin and corrected consumption of it's values for @43081j 
This is looking much nicer!!
> Configure for expected CJS importing

- .changeset/little-otters-clap.md
1. created a changset for the puppeteer-core bump
Should we use patch or minor here?
> chore: add puppeteer-core changeset

- .changeset/famous-pens-flash.md
- packages/test-runner-core/src/server/TestRunnerServer.ts
> fix(test-runner-core): enable file watcher in manual mode

- .changeset/curly-poems-jam.md
- packages/test-runner-chrome/src/ChromeLauncherPage.ts
> fix(test-runner-chrome): fix broken test coverage. fixes #2186

- docs/index.md
Just some grammar tweaks.
1. Main idea is to make it clear that both the skills and code remain relevant, rather than just the skills; and that they do so because they track the standards/platform (rather than some 'here today, gone tomorrow' library).
> grammar tweaks

- yarn.lock
> Run `npm upgrade`

- package.json
- packages/test-runner-commands/test/send-mouse/sendMousePlugin.test.ts
- packages/test-runner-junit-reporter/test/fixtures/multiple/expected.xml
- packages/test-runner-junit-reporter/test/fixtures/nested/expected.xml
- packages/test-runner-junit-reporter/test/fixtures/simple/expected.xml
- packages/test-runner-junit-reporter/test/junitReporter.test.ts
1. update jsunit reporter snapshots
2. Disable any failing webdriver selenium-standalone tests that are blocking master, see https://github.com/webdriverio/selenium-standalone/issues/788 for more info
> Disable webdriver selenium-standalone tests to unblock CI on master

- .changeset/twelve-flowers-prove.md
- packages/dev-server-storybook/src/build/rollup/createRollupConfig.ts
- packages/rollup-plugin-workbox/src/index.ts
- rollup.browser.config.mjs
> fix: terser import

- .changeset/great-walls-work.md
- packages/rollup-plugin-workbox/README.md
- packages/rollup-plugin-workbox/demo/injectManifestSwSrc.js
- packages/rollup-plugin-workbox/demo/rollup.config.mjs
- packages/rollup-plugin-workbox/demo/some-module.js
- packages/rollup-plugin-workbox/package.json
- packages/rollup-plugin-workbox/src/index.ts
- yarn.lock
1. Update workbox to v7
2. Removed the `mode` option in favour of just always bundling/removing `process.env` for the service worker when using `injectManifest`
> feat: update workbox v7

- .changeset/light-cars-roll.md
- packages/rollup-plugin-workbox/src/index.ts
> fix: generate sw arg

- .changeset/swift-wombats-learn.md
- packages/mocks/msw.js
- packages/mocks/package.json
> fix: missing file

- packages/mocks/package.json
- packages/mocks/storybook-decorator.js
> fix: mocks missing file and type: module

- .changeset/silly-donuts-shout.md
- packages/mocks/rollup-plugin.js
> fix: mock rollup plugin

- .changeset/strange-ads-think.md
- packages/mocks/msw.js
> feat: bypass sw

- .changeset/angry-turtles-enjoy.md
- packages/mocks/README.md
- packages/mocks/rollup-plugin.js
> feat: request interceptor

- .changeset/calm-kings-perform.md
- packages/mocks/README.md
- packages/mocks/rollup-plugin.js
> chore: add comment to injected code

- .changeset/serious-beers-beam.md
- packages/mocks/polyfills.js
> fix: default value for opts

- packages/mocks/package.json
- packages/mocks/polyfills.js
> chore: bump msw

- .changeset/sour-grapes-rest.md
- .changeset/tender-poems-add.md
- package-lock.json
- packages/dev-server-storybook/package.json
- packages/mocks/CHANGELOG.md
- packages/mocks/package.json
> Version Packages

- packages/dev-server-rollup/src/createRollupPluginContexts.ts
> fix: broken type

- .changeset/foo-bar-baz.md
> ci: trigger pipeline

- .changeset/late-dolphins-thank.md
- packages/mocks/storybook/decorator.js
> fix: content type

- .changeset/young-beans-grab.md
- packages/mocks/storybook/decorator.js
> fix: flatten mocks correctly

- .changeset/tidy-goats-sin.md
> fix: changeset

- .changeset/tender-tips-relax.md
- package-lock.json
- packages/dev-server-legacy/test/transform-js.test.ts
1. Ran `npm update`.
2. Ran `npm audit fix`.
> run npm update

- .changeset/mean-bats-care.md
- packages/mocks/browser.js
- packages/mocks/sw.js
> fix: msw improvements

- packages/dev-server-import-maps/tsconfig.json
- packages/dev-server-legacy/tsconfig.json
- packages/rollup-plugin-workbox/tsconfig.override.json
- packages/test-runner-browserstack/tsconfig.json
- packages/test-runner-saucelabs/tsconfig.json
- packages/test-runner-visual-regression/tsconfig.json
- packages/test-runner/tsconfig.json
- tsconfig.json
Just
```
npm run update:tsconfigs
```
> chore: update:tsconfigs

- .changeset/purple-mirrors-clap.md
- package-lock.json
- tsconfig.json
Added `dev-server-storybook` to the root `tsconfig.json`.
> Publish dist lol

- package-lock.json
- package.json
Reverts modernweb-dev/web#2388
> Revert "chore(deps): bump pug and @rocket/cli"

- .changeset/quick-readers-trade.md
- package-lock.json
- packages/dev-server-storybook/package.json
- packages/dev-server-storybook/src/shared/mdx/transformMdxToCsf.ts
- packages/dev-server-storybook/types/mdx-js__mdx/index.d.ts
_Hopefully_ this is the last change to make version 1.x of `@web/dev-server-storybook`.
> Revert changes to mdx compilers

- .changeset/twelve-hats-press.md
- packages/mocks/registerMockRoutes.js
> fix: add missing handler message

- .changeset/small-countries-double.md
- packages/mocks/registerMockRoutes.js
> fix: error message

- .changeset/thick-parents-march.md
- package-lock.json
- packages/rollup-plugin-import-meta-assets/README.md
- packages/rollup-plugin-import-meta-assets/package.json
- packages/rollup-plugin-import-meta-assets/src/rollup-plugin-import-meta-assets.js
- packages/rollup-plugin-import-meta-assets/test/fixtures/backticks.js
- packages/rollup-plugin-import-meta-assets/test/fixtures/dynamic-assets/one.svg
- packages/rollup-plugin-import-meta-assets/test/fixtures/dynamic-assets/three.svg
- packages/rollup-plugin-import-meta-assets/test/fixtures/dynamic-assets/two.svg
- packages/rollup-plugin-import-meta-assets/test/fixtures/dynamic-vars.js
- packages/rollup-plugin-import-meta-assets/test/integration.test.js
- packages/rollup-plugin-import-meta-assets/test/snapshots/backticks.js
- packages/rollup-plugin-import-meta-assets/test/snapshots/dynamic-vars.js
1. Allow dynamic vars when using `new URL` re-using code from https://github.com/rollup/plugins/blob/master/packages/dynamic-import-vars. 
2. Updated tests
3. Updated documentation
> Dynamic import meta assets

- .changeset/polite-fans-tie.md
- packages/storybook-framework-web-components/package.json
1. Add an export that yelled at me when I tried to build Storybook
> Include package.json in exports

- .changeset/red-bears-deliver.md
- packages/dev-server-storybook/src/shared/config/readStorybookConfig.ts
> fix: storybook import for windows

- packages/mocks/http.js
- packages/mocks/types.ts
> fix: revert types fix

- .changeset/lovely-worms-cheer.md
- package-lock.json
- packages/mocks/package.json
> fix: lock dep

- .changeset/shaggy-dancers-act.md
- packages/polyfills-loader/src/index.ts
> fix: export polyfills data

- .changeset/empty-ads-agree.md
- package-lock.json
- packages/config-loader/package.json
- packages/config-loader/src/importConfig.js
- packages/config-loader/test/index.test.js
We don't support this old of a node runtime.
> Remove old node runtime specific code

- .changeset/twenty-eels-fry.md
- package-lock.json
- packages/rollup-plugin-copy/package.json
- packages/rollup-plugin-copy/src/listFiles.js
- packages/rollup-plugin-copy/test/integration.test.js
- packages/rollup-plugin-copy/test/listFiles.test.js
- packages/rollup-plugin-copy/test/patternsToFiles.test.js
- packages/rollup-plugin-html/package.json
- packages/rollup-plugin-html/src/input/getInputData.ts
- packages/rollup-plugin-html/test/src/input/InputData.test.ts
> update glob to latest version

- .changeset/tame-ants-mate.md
- package-lock.json
- packages/dev-server-esbuild/package.json
- packages/dev-server/package.json
Not sure why this wasn't updated before.
> update @web/dev-server-rollup in more places

- .changeset/witty-ladybugs-collect.md
- package-lock.json
- packages/dev-server-storybook/src/shared/mdx/transformMdxToCsf.ts
1. MDX stories would yield many errors stating require not being defined
> fix: create a require for mdx stories

- .changeset/strong-sheep-agree.md
- packages/mocks/sw.js
> fix: sw ts

- package-lock.json
- package.json
1. fixes browser tests because a wrong version (the fetch.rc) of msw was installed, still need to fix the node tests though, but merging this one now
> fix browser tests

- .changeset/metal-humans-clean.md
1. A changeset for https://github.com/modernweb-dev/web/commit/fa46b6cb6556421721f7a5dbc4589cfe376536da
> chore: Add changeset to bump @web/dev-server version

- .changeset/sweet-sloths-crash.md
- packages/storybook-builder/src/generate-iframe-html.ts
- packages/storybook-builder/src/index.ts
- packages/storybook-builder/src/rollup-plugin-prebundle-modules.ts
- packages/storybook-builder/static/iframe-template.html
Reverts modernweb-dev/web#2653
Sorry for that, I was too quick with the prebundling update. The security part is needed, so gonna implement it in a different PR.
> Revert "fix(storybook-builder): define only necessary process.env globally"

- package-lock.json
- package.json
- packages/storybook-builder/package.json
- packages/storybook-framework-web-components/package.json
1. removed generic dev deps which I forgot to remove when moving code to the monorepo here https://github.com/modernweb-dev/web/pull/2437
> chore: clean up dev dependencies

- .changeset/clean-peaches-develop.md
- packages/rollup-plugin-html/src/output/emitAssets.ts
- packages/rollup-plugin-html/test/rollup-plugin-html.test.ts
> fix: output assets

- packages/rollup-plugin-html/src/output/emitAssets.ts
> refactor: var naming

- .changeset/tricky-sloths-retire.md
- package-lock.json
- packages/storybook-builder/package.json
- packages/storybook-builder/src/index.ts
1. automatically extract assets from the preview iframe html
2. bundle assets referenced in the CSS that are included in the preview iframe html
> feat(storybook-builder): bundle preview assets

- .changeset/tame-forks-complain.md
- package-lock.json
- packages/storybook-builder/package.json
- packages/storybook-builder/src/rollup-plugin-prebundle-modules.ts
- packages/storybook-framework-web-components/package.json
- packages/storybook-framework-web-components/tests/all-in-one.spec.js
- packages/storybook-framework-web-components/tests/fixtures/all-in-one/.storybook/main.js
> fix(storybook-builder): support @storybook/addon-a11y

- .changeset/rude-lies-share.md
- packages/dev-server-storybook/src/shared/config/readStorybookConfig.ts
> fix: sb windows path

- .changeset/funny-days-judge.md
- packages/mocks/browser.js
fixes https://github.com/modernweb-dev/web/issues/2400
> fix: sw path

- .changeset/friendly-crabs-sneeze.md
- packages/mocks/browser.js
- packages/mocks/package.json
- packages/mocks/sw-path/build.js
- packages/mocks/sw-path/dev.js
> fix: sw path again

- .github/workflows/verify-node.yml
1. Updated `playwright install` command to use the new syntax.
> chore: update playwright install command in GitHub Actions

- package-lock.json
- packages/mocks/package.json
- packages/mocks/registerMockRoutes.js
> fix: msw again

- .changeset/weak-parrots-push.md
- package-lock.json
- packages/storybook-builder/src/esbuild-plugin-commonjs-named-exports.ts
1. fix relative path by starting with ./
> fix(storybook-builder): start relative path with ./

- .changeset/nervous-bananas-know.md
- package-lock.json
- packages/storybook-builder/package.json
> fix(storybook-builder): include missing dependency on @web/config-loader

- .changeset/mean-chairs-search.md
- package-lock.json
- packages/browser-logs/package.json
- packages/dev-server-hmr/package.json
- packages/dev-server/package.json
- packages/test-runner-chrome/package.json
- packages/test-runner-chrome/src/ChromeLauncher.ts
- packages/test-runner-chrome/src/index.ts
- packages/test-runner-puppeteer/package.json
- packages/test-runner-puppeteer/src/puppeteerLauncher.ts
1. Upgraded `puppeteer` and `puppeteer-core` version to v24
> feat!: upgrade puppeteer version to v24

- .changeset/red-ligers-eat.md
- package-lock.json
- packages/polyfills-loader/package.json
1. update version of SCER polyfill
> fix: update scer polyfill version

- .changeset/rude-swans-sneeze.md
- package-lock.json
- packages/dev-server-polyfill/package.json
> chore: update polyfill plugin

- .changeset/green-peas-sit.md
- packages/rollup-plugin-polyfills-loader/src/rollupPluginPolyfillsLoader.ts
> fix: dont call path.join on external urls, it breaks them

- .changeset/thin-wombats-nail.md
- packages/mocks/storybook/addon.js
- packages/mocks/storybook/addon/manager.js
- packages/mocks/storybook/addon/register-addon.js
- packages/storybook-framework-web-components/tests/all-in-one.spec.js
- packages/storybook-framework-web-components/tests/fixtures/all-in-one/.storybook/main.js
1. fix Storybook 8 compatibility in `@web/mocks`
2. add a regression test for this
> fix(mocks): Storybook 8 compatibility
